#config_version=5
mode:
    start_events: ball_started
    stop_events:
        - skill_success
        - skill_failed
    priority: 500

shots:
    skill_scoup:
        switch: s_scoup
        profile: flash
        advance_events: mode_skill_shot_started
        show_tokens:
            light: gi_scoup
            color: red

variable_player:
    skill_success:
        score: 100000

shot_profiles:
    flash:
        states:
          - name: unlit
            show: "flash"
            show_tokens:
              color: red
            speed: 10
          - name: lit
            show: "flash"
            speed: 10

state_machines:
   skill_shot_success:
        states:
            start:
                label: Skill shot ready
            success:
                label: Skill successful
                events_when_started: skill_success
            failed:
                label: Skill failed
                events_when_started: skill_failed
        transitions:
            - source: start
              target: success
              events: skill_scoup_hit
            - source: start
              target: failed
              events: s_spinner_active, s_loopright_active, s_loopleft_active, s_leftsling_active, s_rightsling_active, s_popbumper1_active, s_popbumper2_active, s_popbumper3_active
