#config_version=5
mode:
    start_events: ball_started
    stop_events: ball_ended
    priority: 200

timers:
  open_left_gate:
    start_value: 0
    end_value: 1
    direction: up
    tick_interval: 1s
    control_events:
      - action: restart
        event: leftgate_open

#   warn_gate:
#     start_value: 0
#     end_value: 6
#     direction: up
#     tick_interval: 1s
#     control_events:
#       - action: restart
#         event: outlanegate_open
#       - action: stop
#         event: outlanegate_close



event_player:
  mode_outlanegate_started{machine.game_mode=="EASY"}:
    outlanegate_close
  mode_outlanegate_started{machine.game_mode=="NORMAL"}:
    outlanegate_close
  mode_outlanegate_started{machine.game_mode=="HARDCORE"}:
    outlanegate_open
  mode_outlanegate_started{machine.game_mode=="COMPETITION"}:
    outlanegate_open
  mode_outlanegate_started{machine.game_mode=="COOP"}:
    outlanegate_close
  mode_outlanegate_started{machine.game_mode=="STORY"}:
    outlanegate_close
  s_leftinlane_active{current_player.gate_open==1}:
    leftgate_open

coil_player:
  timer_warn_gate_complete:
    c_rightinlanegate:
      action: enable
  outlanegate_close:
    c_rightinlanegate:
      action: disable
    c_leftinlanegate:
      action: disable 
  outlanegate_open:    #request to open gate, but not yet finished
    c_rightinlanegate:
      action: enable
    c_leftinlanegate:
      action: disable  
  leftgate_open:
    c_leftinlanegate:
      action: enable 
  timer_open_left_gate_complete:
    c_leftinlanegate:
      action: disable

sound_player:
  timer_warn_gate_tick: clock_tick

variable_player:
  outlanegate_close:      #request to close gate, but not yet finished
    gate_open:
      int: 0
      action: set
  outlanegate_open:    
    gate_open:
      int: 1
      action: set
  # timer_warn_gate_complete:
  #   gate_open:
  #     int: 1
  #     action: set

light_player:
  outlanegate_close:
    l_rightoutlane:
      color: green
    l_leftgate:
      color: green
  outlanegate_open:
    l_rightoutlane:
      color: red
    l_leftgate:
      color: red
  # timer_warn_gate_complete:
  #   l_rightoutlane: 
  #     color: red 
  #     fade: 200ms
  #   l_leftgate: 
  #     color: red 
  #     fade: 200ms

# show_player:
#   timer_warn_gate_started:
#     show_blinklight:
#       loops: 9 
#       speed: 1
#       show_tokens:
#         led: l_rightoutlane
#         color: orange
  