#config_version=5
mode:
    start_events: world4_started
    stop_events: world4_completed
    priority: 300

show_player:
  mode_world4_started:  #Setup GI Light Show
    show_world4gi:
      loops: -1
      speed: 1

light_player:
  mode_world4_started:
    lbackbox: brown
    lundercab: brown

sound_player:
  mode_world4_started:
    world4mode_music:
      action: play
      loops: -1
      mode_end_action: stop
  worldmultiball_ended:
    world4mode_music:
      action: play
      loops: -1
      mode_end_action: stop
  world4_collected: travel_ready
  
variable_player:
  #setup environment variables
  mode_world4_started{current_player.world4_setup==0}:  
    #World Settings
    world_id:
      int: 4
      action: set
    world_name: 
      string: "World 4"
      action: set
    world_color: 
      string: "BROWN"
      action: set

    #Item 1 Settings
    world_item1_name:
      string: "Leaves"
      action: set 
    world_item1_color:
      string: "GREEN"
      action: set 
    world_item1_remaining:
      int: 16
      action: set

    #Item 2 Settings
    world_item2_name:
      string: "Stone"
      action: set 
    world_item2_color:
      string: "GRAY"
      action: set 
    world_item2_remaining:
      int: 16
      action: set

    #Item 3 Settings
    world_item3_name:
      string: "Ore"
      action: set 
    world_item3_color:
      string: "BROWN"
      action: set 
    world_item3_remaining:
      int: 16
      action: set

    #Item 4 Settings
    world_item4_name:
      string: "Wood"
      action: set 
    world_item4_color:
      string: "SLATEGRAY"
      action: set 
    world_item4_remaining:
      int: 16
      action: set

    #Mark World as Setup
    world4_setup: 1

widget_player:
  mode_world4_started:
    widget_screenbackground:
      action: update
      slide: world_slide
      widget_settings:
        image: world4_background
  #   widget_videobackground:
  #     action: add
  #     slide: world_slide
  #     widget_settings:
  #       video: world4_overview
    widget_item1icon:
      action: update
      slide: world_slide
      widget_settings:
        image: Podzol_Small
    widget_item2icon:
      action: update
      slide: world_slide
      widget_settings:
        image: MossyCobblestone_Small
    widget_item3icon:
      action: update
      slide: world_slide
      widget_settings:
        image: EmeraldOre_Small
    widget_item4icon:
      action: update
      slide: world_slide
      widget_settings:
        image: WoodJungle_Small

event_player:
  world_collected:
    world4_collected
  mode_villagercontroller_stopped:
    worldmultiball_ended
  mode_nightcontroller_stopped:
    worldmultiball_ended
  mode_nightvillagercontroller_stopped:
    worldmultiball_ended