#config_version=5
mode:
    start_events: multiball_villagermb_started
    stop_events: multiball_villagermb_ended, ball_ending
    priority: 1000

show_player:
  mode_villagermb_started:
    villagembshow:
      loops: -1
      speed: 10

variable_player:
  mode_villagermb_started:
    villager_jackpot:
      int: 1000000
      action: set
  villager_jackpot_hit:
    score: 
      int: current_player.villager_jackpot * current_player.sword
      block: true
    villager_jackpot:
      int: 1000000
      action: set
  spinner_hit:
    score: 
      int: 10000
      block: true
    villager_jackpot:
      int: 100000
      action: add

shots:
  villager_jackpot:
    switch: s_captiveball
    profile: flash
    show_tokens:
      leds: l_captivejackpot
    
event_player:
  mode_villagermb_started:
    outlanegate_close
  villager_jackpot_hit:
    outlanegate_open
    
#play hurry up sound effect
sound_player:
  villager_jackpot_hit:
    villager_jackpot
  mode_villagermb_started{current_player.world_id==1}:
    world1mode_music:
      action: stop
  mode_villagermb_started{current_player.world_id==2}:
    world2mode_music:
      action: stop
  mode_villagermb_started{current_player.world_id==3}:
    world3mode_music:
      action: stop
  mode_villagermb_started{current_player.world_id==4}:
    world4mode_music:
      action: stop
  mode_villagermb_started{current_player.world_id==5}:
    world5mode_music:
      action: stop
  mode_villagermb_started:
    villagermb_music:
      action: play
      loops: -1
      mode_end_action: stop
  mode_villagermb_started.1:
    villager_multiball:
      action: play
      loops: 0
  sw_playfield_active_active:
    villagersp: 
      action: play
      loops: 1




