#config_version=5
mode:
    start_events: mode_villagercontroller_started, mode_nightvillagercontroller_started
    stop_events: mode_villagercontroller_stopped, mode_nightvillagercontroller_stopped
    priority: 1000

variable_player:
  mode_villagermb_started:
    villager_jackpot:
      int: 1000000
      action: set
  villager_jackpot_hit:
    score: 
      int: current_player.villager_jackpot * current_player.sword
      block: true
    villager_jackpot:
      int: 1000000
      action: set
  spinner_hit:
    score: 
      int: 10000
      block: true
    villager_jackpot:
      int: 100000
      action: add

shot_profiles:
  sp_villagerjackpot:
    states:
      - name: lit
        show: "flash"

shots:
  villager_jackpot:
    switch: s_captiveball
    profile: sp_villagerjackpot
    show_tokens:
      leds: l_captivejackpot
    
event_player:
  mode_villagermb_started:
    show_multiplier
    
#play hurry up sound effect
sound_player:
  mode_villagermb_started.1:
    villager_multiball:
      action: play
      loops: 0
  sw_playfield_active_active:
    villagersp: 
      action: play
      loops: 1
  villager_jackpot_hit:
    villager_jackpot

