#config_version=5
mode:
    start_events: mode_villagercontroller_started, mode_nightvillagercontroller_started
    stop_events: mode_villagercontroller_stopped, mode_nightvillagercontroller_stopped
    priority: 1000

variable_player:
  mode_villagermb_started:
    villager_jackpot:
      int: 1000000
      action: set
  villager_jackpot_hit:
    score: 
      int: current_player.villager_jackpot * current_player.sword
      block: true
    villager_jackpot:
      int: 1000000
      action: set
  spinner_hit:
    score: 
      int: 10000
      block: true
    villager_jackpot:
      int: 100000
      action: add

shot_profiles:
  sp_villagerjackpot:
    states:
      - name: lit
        show: "flash"

shots:
  villager_jackpot:
    switch: s_captiveball
    profile: sp_villagerjackpot
    show_tokens:
      leds: l_captivejackpot
    
event_player:
  mode_villagermb_started:
    show_multiplier

widget_player:
  mode_villagermb_started:
    widget_villagerjackpot:
      action: add

widgets:
  widget_villagerjackpot:
    - type: image        #ITEM BACKGROUND
      image: jackpot_villager
      anchor_x: center
      anchor_y: center
      y: bottom+150
      x: center+35
      z: 15    
    - type: text        #PLAYER 1 SCORE
      text: (player|villager_jackpot)
      number_grouping: true
      min_digits: 2
      font_name: ARLRDBD
      font_size: 24
      y: bottom+125
      x: center+35
      z: 100
      anchor_x: center
      anchor_y: center
    
#play hurry up sound effect
sound_player:
  mode_villagermb_started.1:
    villager_multiball:
      action: play
      loops: 0
  sw_playfield_active_active:
    villagersp: 
      action: play
      loops: 1
  villager_jackpot_hit:
    villager_jackpot

