#config_version=5
mode:
    start_events: multiball_villagermb_started
    stop_events: multiball_villagermb_ended, ball_ending
    priority: 1000

show_player:
  mode_villagermb_started:
    villagembshow:
      loops: -1
      speed: 10

variable_player:
  mode_villagermb_started:
    villager_jackpot:
      int: 1000000
      action: set
  villager_jackpot_hit:
    score: 
      int: current_player.villager_jackpot
      block: true
    villager_jackpot:
      int: 1000000
      action: set
  villager_spinner_hit:
    score: 
      int: 10000
      block: true
    villager_jackpot:
      int: 100000
      action: add

shots:
  villager_jackpot:
    switch: s_captiveball
    profile: flash
    show_tokens:
      leds: l_captivejackpot
  villager_spinner:
    switch: s_spinner
    
event_player:
  mode_villagermb_started:
    outlanegate_restart

#play hurry up sound effect
sound_player:
  villager_jackpot_hit:
    villager_jackpot
  mode_villagermb_started:
    basemode_music:
      action: stop
    world1mode_music:
      action: stop
    world2mode_music:
      action: stop
    world3mode_music:
      action: stop
    world4mode_music:
      action: stop
    world5mode_music:
      action: stop
    world6mode_music:
      action: stop
    villagermb_music:
      action: play
      loops: -1
      mode_end_action: stop
      priority: 1
  sw_playfield_active_active:
    villagersp: 
      action: play
      loops: 1




