#config_version=5
mode:
    start_events: ball_starting
    priority: 100

#Shots
shots:
  spinner:
    switch: s_spinner
  captiveball:
    switch: s_captiveball
  centertarget:
    switch: s_centertarget
  collectitem1:
    switch: s_collectitem1
    show_tokens:
      leds: l_collectitem1
  collectitem2:
    switch: s_collectitem2
    show_tokens:
      leds: l_collectitem2
  collectitem3:
    switch: s_collectitem3
    show_tokens:
      leds: l_collectitem3
  collectitem4:
    switch: s_collectitem4
    show_tokens:
      leds: l_collectitem4
  collectitem5:
    switch: s_collectitem5
    show_tokens:
      leds: l_collectitem5

event_player:
  collectitem1_hit:
    item_collected
  collectitem2_hit:
    item_collected
  collectitem4_hit:
    item_collected
  collectitem5_hit:
    item_collected
  logicblock_counter_villagermultiball_complete:
    villagermultiball_ready
  sw_playfield_active_active{device.multiball_locks.villagerlock.locked_balls==1 and device.multiball_locks.villagerlock.enabled}:
    villagermultiball_start
  ball_started:
    item_collected

counters:
   counter_villagermultiball:
      count_events: spinner_hit
      starting_count: 0
      count_interval: 1
      count_complete_value: 20
      restart_events: multiball_villagermb_ended, ball_started
      persist_state: true

multiball_locks:
   villagerlock:
     balls_to_lock: 1
     locked_ball_counting_strategy: physical_only
     lock_devices: bd_topkicker 
     enable_events: villagermultiball_ready
     disable_events: villagermultiball_start

multiballs:
   villagermb:
     ball_count: 2
     ball_locks: bd_topkicker
     enable_events: villagermultiball_ready
     start_events: villagermultiball_start
     shoot_again: 0s

#Player Variables
variable_player:
  #MULTIBALL MULTIPLIER
  ball_started:     #RESET ON BALL START
    multiplier_mb:
      int: 1
      action: set
  multiball_villagermb_started: #VILLAGER MULTIBALL STARTED
    multiplier_mb:
      int: 2
      action: set
  multiball_villagermb_ended: #VILLAGER MULTIBALL ENDED
    multiplier_mb:
      int: 1
      action: set

  #SPINNER SCORING
  spinner_hit{device.counters.counter_villagermultiball.value<4}: #LEVEL 100
    score: 100 * current_player.multiplier_mb
  spinner_hit{device.counters.counter_villagermultiball.value>=4 and device.counters.counter_villagermultiball.value<8}: #LEVEL 1000
    score: 1000 * current_player.multiplier_mb
  spinner_hit{device.counters.counter_villagermultiball.value>=8 and device.counters.counter_villagermultiball.value<12}: #LEVEL 2000
    score: 2000 * current_player.multiplier_mb
  spinner_hit{device.counters.counter_villagermultiball.value>=12 and device.counters.counter_villagermultiball.value<16}: #LEVEL 3000
    score: 3000 * current_player.multiplier_mb
  spinner_hit{device.counters.counter_villagermultiball.value>=16}: #LEVEL 4000
    score: 4000 * current_player.multiplier_mb

  collectitem1_hit:
    score: 10000 * current_player.multiplier_mb
    bonus_items: 1
  collectitem2_hit:
    score: 10000 * current_player.multiplier_mb
    bonus_items: 1
  collectitem3_hit:
    score: 10000 * current_player.multiplier_mb
  collectitem4_hit:
    score: 10000 * current_player.multiplier_mb
    bonus_items: 1
  collectitem5_hit:
    score: 10000 * current_player.multiplier_mb
    bonus_items: 1

  s_right_outlane_active:
    score: 5000 * current_player.multiplier_mb
  s_centertarget_active:
    score: 10000 * current_player.multiplier_mb
  s_rightsling_active:
    score: 100 * current_player.multiplier_mb
  s_leftsling_active:
    score: 100 * current_player.multiplier_mb
  s_bumperrail_active:
    score: 50 * current_player.multiplier_mb
  s_scoup_active:
    score: 5000 * current_player.multiplier_mb
 
  s_topkicker_active:
    score: 5000 * current_player.multiplier_mb
  s_whitedot1_active:
    score: 100 * current_player.multiplier_mb
  s_whitedot2_active:
    score: 100 * current_player.multiplier_mb
  s_whitedot3_active:
    score: 100 * current_player.multiplier_mb
  s_whitedot4_active:
    score: 100 * current_player.multiplier_mb
  s_bluetarget1_active:
    score: 5000 * current_player.multiplier_mb
  s_bluetarget2_active:
    score: 5000 * current_player.multiplier_mb
  s_bluetarget3_active:
    score: 5000 * current_player.multiplier_mb
  s_collectitem1_active:
    score: 1000 * current_player.multiplier_mb
  s_collectitem2_active:
    score: 1000 * current_player.multiplier_mb
  s_collectitem3_active:
    score: 5000 * current_player.multiplier_mb
  s_collectitem4_active:
    score: 1000 * current_player.multiplier_mb
  s_collectitem5_active:
    score: 1000 * current_player.multiplier_mb
  s_collect_active:
    score: 1000 * current_player.multiplier_mb

sound_player:
  s_collectitem1_active: collect_tool
  s_collectitem2_active: collect_tool
  s_collectitem3_active: collect_tool
  s_collectitem4_active: collect_tool
  s_collectitem5_active: collect_tool
  s_rightinlane_active: lane_swish
  s_rightoutlane_active: lane_swish
  s_leftinlane_active: lane_swish
  s_leftoutlane_active: lane_swish
  s_spinner_active: 
    villagersp: 
      action: play
      loops: 1
  #VILLAGER MULTIBALL
  villagermultiball_ready:
    villager_multiball_ready
  #multiball_lock_villagerlock_locked_ball:     #COMMENTED OUT SINCE I DONT THINK THIS DOES ANYTHING
  #  villager_multiball
      
show_player:
  mode_base_started:
    show_dropcreepers:  #Drop the Creepers
      loops: 0
      speed: 1
    
light_player:
  mode_base_started:
    lgi:
      color: white
    lfeature: off
  spinner_hit{device.counters.counter_villagermultiball.value>=4 and device.counters.counter_villagermultiball.value<8}: #LEVEL 1000
    l_spinner1: green
  spinner_hit{device.counters.counter_villagermultiball.value>=8 and device.counters.counter_villagermultiball.value<12}: #LEVEL 1000
    l_spinner2: green
    l_spinner1: off
  spinner_hit{device.counters.counter_villagermultiball.value>=12 and device.counters.counter_villagermultiball.value<16}: #LEVEL 1000
    l_spinner3: green
    l_spinner2: off
    l_spinner1: off
  spinner_hit{device.counters.counter_villagermultiball.value>=16}:
    l_spinner3: off 
    l_spinner2: off 
    l_spinner1: off
    l_spinner4: green 
  multiball_villagermb_started:
    l_spinner1: green
    l_spinner2: green
    l_spinner3: green
    l_spinner4: green
  multiball_villagermb_ended:
    l_spinner1: off
    l_spinner2: off
    l_spinner3: off
    l_spinner4: off

#This is for achieving the worlds
achievements:
  world1:
    show_tokens:
      light: l_world1
      color: green
    show_when_selected: show_flashcolor 
    show_when_started: show_fadecolor
    show_when_completed: show_solidcolor 
    events_when_started: world1_start
    reset_events: reset_worlds
    enable_events: mode_base_started
    complete_events: world1_completed
    events_when_completed: rotate_mission_rotator, start_world
    restart_on_next_ball_when_started: true
    enable_on_next_ball_when_enabled: true
  world2:
    show_tokens:
      light: l_world2
      color: yellow
    show_when_selected: show_flashcolor 
    show_when_started: show_fadecolor
    show_when_completed: show_solidcolor 
    events_when_started: award_world2
    reset_events: reset_worlds
    enable_events: world1_completed
    complete_events: world2_completed
    events_when_completed: rotate_mission_rotator, start_world
    restart_on_next_ball_when_started: true
    enable_on_next_ball_when_enabled: true
  world3:
    show_tokens:
      light: l_world3
      color: blue
    show_when_selected: show_flashcolor 
    show_when_started: show_fadecolor
    show_when_completed: show_solidcolor 
    events_when_started: award_world3
    reset_events: reset_worlds
    enable_events: world2_completed
    complete_events: world3_completed
    events_when_completed: rotate_mission_rotator, start_world
    restart_on_next_ball_when_started: true
    enable_on_next_ball_when_enabled: true
  world4:
    show_tokens:
      light: l_world4
      color: brown
    show_when_selected: show_flashcolor 
    show_when_started: show_fadecolor
    show_when_completed: show_solidcolor 
    events_when_started: award_world4
    reset_events: reset_worlds
    enable_events: world3_completed
    complete_events: world4_completed
    events_when_completed: rotate_mission_rotator, start_world
    restart_on_next_ball_when_started: true
    enable_on_next_ball_when_enabled: true
  world5:
    show_tokens:
      light: l_world5
      color: red
    show_when_selected: show_flashcolor 
    show_when_started: show_fadecolor
    show_when_completed: show_solidcolor 
    events_when_started: award_world5
    reset_events: reset_worlds
    enable_events: world4_completed
    complete_events: world5_completed
    events_when_completed: rotate_mission_rotator, start_world
    restart_on_next_ball_when_started: true
    enable_on_next_ball_when_enabled: true
  world6:
    show_tokens:
      light: l_world6
      color: purple
    show_when_selected: show_flashcolor 
    show_when_started: show_fadecolor
    show_when_completed: show_solidcolor 
    events_when_started: award_world6
    reset_events: reset_worlds
    enable_events: world5_completed
    complete_events: world6_completed
    events_when_completed: rotate_mission_rotator, start_world
    restart_on_next_ball_when_started: true
    enable_on_next_ball_when_enabled: true

achievement_groups:
  worlds:
    achievements: world1, world2, world3, world4, world5, world6
    start_selected_events: mode_base_started, start_world
    events_when_enabled: mission_rotator_ready
    auto_select: true
    enable_while_no_achievement_started: true
    rotate_right_events: rotate_mission_rotator


slides:
  base_pincraft_slide:
    priority: 100
    widgets:
      - type: text        #VILLAGER JACKPOT
        text: Villager Jackpot - (player|villager_jackpot)
        number_grouping: true
        min_digits: 2
        font_name: ARLRDBD
        font_size: 25
        y: top-50
        x: left+100
        z: 100
        anchor_x: left
        anchor_y: top
      - type: text        #WORLD JACKPOT
        text: World Jackpot - (player|world_jackpot)
        number_grouping: true
        min_digits: 2
        font_name: ARLRDBD
        font_size: 25
        y: top-100
        x: left+100
        z: 100
        anchor_x: left
        anchor_y: top
      - type: text        #MULTIBALL MULTIPLIER
        text: MB - (player|multiplier_mb)x
        number_grouping: true
        min_digits: 2
        font_name: ARLRDBD
        font_size: 25
        y: top-50
        x: right-100
        z: 100
        anchor_x: left
        anchor_y: top
      - type: text        #PLAYER 1 SCORE
        text: PLAYER 1 - (player1|score)
        number_grouping: true
        min_digits: 2
        font_name: ARLRDBD
        font_size: 25
        y: bottom+260
        x: left+50
        z: 100
        anchor_x: left
        anchor_y: top
      - type: text        #PLAYER 2 SCORE
        text: PLAYER 2 - (player2|score)
        number_grouping: true
        min_digits: 2
        font_name: ARLRDBD
        font_size: 25
        y: bottom+200
        x: left+50
        z: 100
        anchor_x: left
        anchor_y: top
      - type: text        #PLAYER 3 SCORE
        text: PLAYER 3 - (player3|score)
        number_grouping: true
        min_digits: 2
        font_name: ARLRDBD
        font_size: 25
        y: bottom+140
        x: left+50
        z: 100
        anchor_x: left
        anchor_y: top
      - type: text        #PLAYER 4 SCORE
        text: PLAYER 4 - (player4|score)
        number_grouping: true
        min_digits: 2
        font_name: ARLRDBD
        font_size: 25
        y: bottom+80
        x: left+50
        z: 100
        anchor_x: left
        anchor_y: top
      - type: text        #TOOL 1 MULTIPLIER
        text: 1x
        font_name: ARLRDBD
        font_size: 25
        y: top-188
        x: right-60
        z: 100
        anchor_x: center
        anchor_y: top
      - type: text        #TOOL 2 MULTIPLIER
        text: 1x
        font_name: ARLRDBD
        font_size: 25
        y: top-302
        x: right-60
        z: 100
        anchor_x: center
        anchor_y: top
      - type: text        #TOOL 3 MULTIPLIER
        text: 1x
        font_name: ARLRDBD
        font_size: 25
        y: top-416
        x: right-60
        z: 100
        anchor_x: center
        anchor_y: top
      - type: text        #TOOL 3 MULTIPLIER
        text: 1x
        font_name: ARLRDBD
        font_size: 25
        y: top-530
        x: right-60
        z: 100
        anchor_x: center
        anchor_y: top
      - type: text        #ITEM 1 NEEDED
        text: (player|world_item1_remaining)
        font_name: ARLRDBD
        font_size: 25
        y: bottom+24
        x: right-462
        z: 100
        anchor_x: center
        anchor_y: bottom
      - type: text        #ITEM 2 NEEDED
        text: (player|world_item2_remaining)
        font_name: ARLRDBD
        font_size: 25
        y: bottom+24
        x: right-373
        z: 100
        anchor_x: center
        anchor_y: bottom
      - type: text        #ITEM 3 NEEDED
        text: (player|world_item3_remaining)
        font_name: ARLRDBD
        font_size: 25
        y: bottom+24
        x: right-284
        z: 100
        anchor_x: center
        anchor_y: bottom
      - type: text        #ITEM 4 NEEDED
        text: (player|world_item4_remaining)
        font_name: ARLRDBD
        font_size: 25
        y: bottom+24
        x: right-196
        z: 100
        anchor_x: center
        anchor_y: bottom
      - type: text        #BALL TEXT
        text: BALL (ball)
        font_name: ARLRDBD
        font_size: 25
        y: bottom+50
        x: right-60
        z: 100
        anchor_x: center
        anchor_y: bottom
      - type: image        #BALL1
        image: heart_empty
        anchor_x: right
        anchor_y: bottom
        y: bottom+15
        x: right-15
        z: 10
      - type: image        #BALL2
        image: heart_full
        anchor_x: right
        anchor_y: bottom
        y: bottom+15
        x: right-45 
        z: 10
      - type: image        #BALL3
        image: heart_full
        anchor_x: right
        anchor_y: bottom
        y: bottom+15
        x: right-75 
        z: 10
      - type: image        #TOOL BACKGROUND
        image: tool_background
        anchor_x: right
        anchor_y: bottom
        y: bottom+200
        x: right-15
        z: 10
      - type: image        #ITEM BACKGROUND
        image: item_background
        anchor_x: left
        anchor_y: bottom
        y: bottom+15
        x: left+860
        z: 10
      - type: image        #SCORE BACKGROUND
        image: score_background
        anchor_x: left
        anchor_y: bottom
        y: bottom+15
        x: left+15
        z: 10
      - type: image        #WORLD BACKGROUND
        image: world1_background
        z: 0

slide_player:
  mode_base_started: base_pincraft_slide

