#config_version=5
mode:
    start_events: ball_started
    priority: 100


#Extra Balls
extra_balls:
  meatextraball:
    enabled: true
    award_events: meatextraball_award
    max_per_game: 2



#Shots
shots:
  spinner:
    switch: s_spinner
  captiveball:
    switch: s_captiveball
 
 
  # Collect Item Special moved to Extra Ball Mode

event_player:
  #BALL STARTING EVENTS
  mode_base_started:
    outlanegate_close
    # show_ball_count
    # show_player_score
    # show_debug

  mode_nightcontroller_stopped:
    event_nightorvillagermultiball_ended
  mode_villagercontroller_stopped:
    event_nightorvillagermultiball_ended
  mode_nightvillagercontroller_stopped:
    event_nightorvillagermultiball_ended
 
  player_multiplier_mb:
    show_multiplier
    
  # -- MULTIBALL START LOGIC

  #START STRONGHOLD MULTIBALL ON PLUNGE
  sw_playfield_active_active{device.multiball_locks.strongholdlock.locked_balls==1 and device.multiball_locks.strongholdlock.enabled}:
    stronghold_start


  #=========== CONTROLS WHEN WORLDS ARE STARTED ============
  #START WORLD 1
  mode_base_started{current_player.world_id==0}:
    world1_start
    #world5_start
    #theend_start

  #ENABLE NEXT WORLDS WHEN NETHER MODE RETURNS
  multiball_nethermb_ended:
    outlanegate_open

  multiball_nethermb_ended{current_player.world_id==1}:
    world2_start   
  multiball_nethermb_ended{current_player.world_id==2}:
    world3_start   
  multiball_nethermb_ended{current_player.world_id==3}:
    world4_start
  multiball_nethermb_ended{current_player.world_id==4}:
    world5_start
  stronghold_completed:
    theend_start

  world1_collected{current_player.multiplier_mb==1}:
    nethermode_ready
    villagerornightmb_disable
  world2_collected{current_player.multiplier_mb==1}:
    nethermode_ready
    villagerornightmb_disable
  world3_collected{current_player.multiplier_mb==1}:
    nethermode_ready
    villagerornightmb_disable
  world4_collected{current_player.multiplier_mb==1}:
    nethermode_ready
    villagerornightmb_disable
  world5_collected{current_player.multiplier_mb==1}:
    stronghold_ready
    villagerornightmb_disable

  event_nightorvillagermultiball_ended{current_player.world_id != 5 and current_player.world_item1_remaining == 0 and current_player.world_item2_remaining == 0 and current_player.world_item3_remaining == 0 and current_player.world_item4_remaining == 0}:
    nethermode_ready
    villagerornightmb_disable

  event_nightorvillagermultiball_ended{current_player.world_id == 5 and current_player.world_item1_remaining == 0 and current_player.world_item2_remaining == 0 and current_player.world_item3_remaining == 0 and current_player.world_item4_remaining == 0}:
    stronghold_ready
    villagerornightmb_disable

  event_nightorvillagermultiball_ended{current_player.world_jackpot_worlds>1}:
    outlanegate_open

  event_nightorvillagermultiball_ended{current_player.world_jackpot_worlds==1}:
    outlanegate_close



multiball_locks:
  strongholdlock:
    balls_to_lock: 1
    locked_ball_counting_strategy: physical_only
    lock_devices: bd_scoop 
    enable_events: stronghold_ready
    disable_events: stronghold_start, stronghold_disable

multiballs:
  strongholdmb:
    ball_count: 2
    ball_locks: bd_scoop
    enable_events: stronghold_ready
    start_events: stronghold_start
    shoot_again: 0s


#Player Variables
variable_player:
  balls_in_play{balls==1}:
    multiplier_mb:
      int: 1
      action: set
  balls_in_play{balls==2}:
    multiplier_mb:
      int: 2
      action: set
  balls_in_play{balls==3}:
    multiplier_mb:
      int: 3
      action: set



  #MULTIBALL MULTIPLIER
  mode_base_started:     #RESET ON BALL START
    bonus_items:  #RESET BONUS COUNT ON END OF EACH BALL
      int: 0
      action: set

  #BASE ITEM SCORING
  s_right_outlane_active:
    score: 5000 * current_player.multiplier_mb
  s_rightsling_active:
    score: 100 * current_player.multiplier_mb
  s_leftsling_active:
    score: 100 * current_player.multiplier_mb
  s_bumperrail_active:
    score: 50 * current_player.multiplier_mb
  s_scoup_active:
    score: 5000 * current_player.multiplier_mb
 
  s_topkicker_active:
    score: 5000 * current_player.multiplier_mb
  s_whitedot1_active:
    score: 100 * current_player.multiplier_mb
  s_whitedot2_active:
    score: 100 * current_player.multiplier_mb
  s_whitedot3_active:
    score: 100 * current_player.multiplier_mb
  s_whitedot4_active:
    score: 100 * current_player.multiplier_mb
  s_bluetarget1_active:
    score: 5000 * current_player.multiplier_mb
  s_bluetarget2_active:
    score: 5000 * current_player.multiplier_mb
  s_bluetarget3_active:
    score: 5000 * current_player.multiplier_mb
  s_collect_active:
    score: 1000 * current_player.multiplier_mb

sound_player:
  skill_success: skillshot_awarded
  s_rightinlane_active: lane_swish
  s_rightoutlane_active: lane_swish
  s_leftinlane_active: lane_swish
  s_leftoutlane_active: lane_swish
     
show_player:
  mode_base_started:
    show_dropcreepers:  #Drop the Creepers
      loops: 0
      speed: 1
  multiball_nethermb_ended:
    show_dropcreepers:  #Drop the Creepers
      loops: 0
      speed: 1
      
light_player:
  mode_base_started:
    lgi:
      color: white
    lfeature: off

#This is for achieving the worlds
achievements:
  world1:
    show_tokens:
      light: l_world1
      color: green
    show_when_selected: show_flashcolor 
    show_when_started: show_fadecolor
    show_when_completed: show_solidcolor 
    events_when_started: world1_started
    reset_events: reset_worlds
    enable_events: world1_start
    complete_events: world1_completed
    events_when_completed: rotate_mission_rotator
    restart_on_next_ball_when_started: true
    enable_on_next_ball_when_enabled: true
  world2:
    show_tokens:
      light: l_world2
      color: yellow
    show_when_selected: show_flashcolor 
    show_when_started: show_fadecolor
    show_when_completed: show_solidcolor 
    events_when_started: world2_started
    reset_events: reset_worlds
    enable_events: world2_start
    complete_events: world2_completed
    events_when_completed: rotate_mission_rotator
    restart_on_next_ball_when_started: true
    enable_on_next_ball_when_enabled: true
  world3:
    show_tokens:
      light: l_world3
      color: blue
    show_when_selected: show_flashcolor 
    show_when_started: show_fadecolor
    show_when_completed: show_solidcolor 
    events_when_started: world3_started
    reset_events: reset_worlds
    enable_events: world3_start
    complete_events: world3_completed
    events_when_completed: rotate_mission_rotator
    restart_on_next_ball_when_started: true
    enable_on_next_ball_when_enabled: true
  world4:
    show_tokens:
      light: l_world4
      color: brown
    show_when_selected: show_flashcolor 
    show_when_started: show_fadecolor
    show_when_completed: show_solidcolor 
    events_when_started: world4_started
    reset_events: reset_worlds
    enable_events: world4_start
    complete_events: world4_completed
    events_when_completed: rotate_mission_rotator
    restart_on_next_ball_when_started: true
    enable_on_next_ball_when_enabled: true
  world5:
    show_tokens:
      light: l_world5
      color: red
    show_when_selected: show_flashcolor 
    show_when_started: show_fadecolor
    show_when_completed: show_solidcolor 
    events_when_started: world5_started
    reset_events: reset_worlds
    enable_events: world5_start
    complete_events: world5_completed
    events_when_completed: rotate_mission_rotator
    restart_on_next_ball_when_started: true
    enable_on_next_ball_when_enabled: true
  stronghold:
    show_tokens:
      light: l_world5
      color: red
    show_when_selected: show_flashcolor 
    show_when_started: show_fadecolorfaster
    show_when_completed: show_solidcolor 
    events_when_started: stronghold_started
    reset_events: reset_worlds
    enable_events: stronghold_start
    complete_events: stronghold_completed
    events_when_completed: rotate_mission_rotator
    restart_on_next_ball_when_started: true
    enable_on_next_ball_when_enabled: true
  world6:
    show_tokens:
      light: l_world6
      color: purple
    show_when_selected: show_flashcolor 
    show_when_started: show_fadecolor
    show_when_completed: show_solidcolor 
    events_when_started: theend_started
    reset_events: reset_worlds
    enable_events: theend_start
    complete_events: theend_completed
    events_when_completed: rotate_mission_rotator
    restart_on_next_ball_when_started: true
    enable_on_next_ball_when_enabled: true

achievement_groups:
  worlds:
    achievements: world1, world2, world3, world4, world5, stronghold, world6
    start_selected_events: world_start, world1_start, world2_start, world3_start, world4_start, stronghold_start, world5_start, theend_start
    events_when_enabled: mission_rotator_ready
    auto_select: true
    enable_while_no_achievement_started: true
    rotate_right_events: rotate_mission_rotator

widgets:
  widget_multiplier:
    - type: image        #TOOL BACKGROUND
      image: multiball_2x
      anchor_x: center
      anchor_y: bottom
      y: bottom+690
      x: right-65
      z: 100
  widget_debug:
    - type: image        #SCORE BACKGROUND
      image: score_background
      anchor_x: left
      anchor_y: top
      y: top-15
      x: left+15
      z: 200
    - type: text        #GAME MODE
      text: GAME MODE (player|game_mode)
      number_grouping: true
      min_digits: 2
      font_name: ARLRDBD
      font_size: 18
      y: top-25
      x: left+50
      z: 210
      anchor_x: left
      anchor_y: top
    - type: text        #VILLAGER JACKPOT
      text: VILLAGER | Ready=(player|villagermb_ready) / Jackpot=(player|villager_jackpot) x S(player|sword)
      number_grouping: true
      min_digits: 2
      font_name: ARLRDBD
      font_size: 18
      y: top-50
      x: left+50
      z: 210
      anchor_x: left
      anchor_y: top
    - type: text        #WORLD JACKPOT
      text: WORLD | Jackpot B(player|world_jackpot_base) x I(player|world_jackpot_items) x W(player|world_jackpot_worlds) x S(player|sword)=(player|world_jackpot)
      number_grouping: true
      min_digits: 2
      font_name: ARLRDBD
      font_size: 18
      y: top-75
      x: left+50
      z: 210
      anchor_x: left
      anchor_y: top
    - type: text        #Crafting
      text: CRAFT | Enabled=(player|crafting_enabled) / Full=(player|crafting_full) / Ready=(player|crafting_ready)
      number_grouping: true
      min_digits: 2
      font_name: ARLRDBD
      font_size: 18
      y: top-100
      x: left+50
      z: 210
      anchor_x: left
      anchor_y: top
    - type: text        #Travel and Diverter
      text: DIVERTER | Diverter=(player|diverter_state)
      number_grouping: true
      min_digits: 2
      font_name: ARLRDBD
      font_size: 18
      y: top-125
      x: left+50
      z: 210
      anchor_x: left
      anchor_y: top
    - type: text        #EARNED EB COUNT
      text: EXTRABALL | Earned=(player|earned_ebcount)
      number_grouping: true
      min_digits: 2
      font_name: ARLRDBD
      font_size: 18
      y: top-150
      x: left+50
      z: 210
      anchor_x: left
      anchor_y: top
    - type: text        #STRONGHOLD PROGRESS
      text: STRONGHOLD | Progress=(player|stronghold_progress) / Jackpot=(player|stronghold_jackpot)
      number_grouping: true
      min_digits: 2
      font_name: ARLRDBD
      font_size: 18
      y: top-175
      x: left+50
      z: 210
      anchor_x: left
      anchor_y: top
    - type: text        #MULTIBALL MULTIPLIER
      text: MULTIBALL | Multiplier=(player|multiplier_mb)
      number_grouping: true
      min_digits: 2
      font_name: ARLRDBD
      font_size: 18
      y: top-200
      x: left+50
      z: 210
      anchor_x: left
      anchor_y: top
    - type: text        #NIGHT MULTIBALL
      text: NIGHT | Ready=(player|nightmb_ready)
      number_grouping: true
      min_digits: 2
      font_name: ARLRDBD
      font_size: 18
      y: top-225
      x: left+50
      z: 210
      anchor_x: left
      anchor_y: top
    - type: text        #debug variable
      text: DEBUG | Variable=NONE
      number_grouping: true
      min_digits: 2
      font_name: ARLRDBD
      font_size: 18
      y: top-250
      x: left+50
      z: 210
      anchor_x: left
      anchor_y: top
     

  widget_scorebackground:
    - type: image        #SCORE BACKGROUND
      image: score_background
      anchor_x: left
      anchor_y: bottom
      y: bottom+15
      x: left+15
      z: 10

  widget_ball1:
    - type: text        #BALL TEXT
      text: BALL (ball)
      font_name: ARLRDBD
      font_size: 25
      y: bottom+50
      x: right-60
      z: 100
      anchor_x: center
      anchor_y: bottom
    - type: image        #BALL1
      image: heart_full
      anchor_x: right
      anchor_y: bottom
      y: bottom+15
      x: right-15
      z: 100
    - type: image        #BALL2
      image: heart_full
      anchor_x: right
      anchor_y: bottom
      y: bottom+15
      x: right-45 
      z: 100
    - type: image        #BALL3
      image: heart_full
      anchor_x: right
      anchor_y: bottom
      y: bottom+15
      x: right-75 
      z: 100

  widget_ball2:
    - type: text        #BALL TEXT
      text: BALL (ball)
      font_name: ARLRDBD
      font_size: 25
      y: bottom+50
      x: right-60
      z: 100
      anchor_x: center
      anchor_y: bottom
    - type: image        #BALL1
      image: heart_empty
      anchor_x: right
      anchor_y: bottom
      y: bottom+15
      x: right-15
      z: 100
    - type: image        #BALL2
      image: heart_full
      anchor_x: right
      anchor_y: bottom
      y: bottom+15
      x: right-45 
      z: 100
    - type: image        #BALL3
      image: heart_full
      anchor_x: right
      anchor_y: bottom
      y: bottom+15
      x: right-75 
      z: 100

  widget_ball3:
    - type: text        #BALL TEXT
      text: BALL (ball)
      font_name: ARLRDBD
      font_size: 25
      y: bottom+50
      x: right-60
      z: 100
      anchor_x: center
      anchor_y: bottom
    - type: image        #BALL1
      image: heart_empty
      anchor_x: right
      anchor_y: bottom
      y: bottom+15
      x: right-15
      z: 100
    - type: image        #BALL2
      image: heart_empty
      anchor_x: right
      anchor_y: bottom
      y: bottom+15
      x: right-45 
      z: 100
    - type: image        #BALL3
      image: heart_full
      anchor_x: right
      anchor_y: bottom
      y: bottom+15
      x: right-75 
      z: 100
  widget_player1score:
    - type: text        #PLAYER 1 SCORE
      text: PLAYER 1 - (player1|score)
      number_grouping: true
      min_digits: 2
      font_name: ARLRDBD
      font_size: 24
      y: bottom+250
      x: left+50
      z: 100
      anchor_x: left
      anchor_y: center
  widget_player2score:
    - type: text        #PLAYER 2 SCORE
      text: PLAYER 2 - (player2|score)
      number_grouping: true
      min_digits: 2
      font_name: ARLRDBD
      font_size: 24
      y: bottom+190
      x: left+50
      z: 100
      anchor_x: left
      anchor_y: center
  widget_player3score:
    - type: text        #PLAYER 3 SCORE
      text: PLAYER 3 - (player3|score)
      number_grouping: true
      min_digits: 2
      font_name: ARLRDBD
      font_size: 24
      y: bottom+130
      x: left+50
      z: 100
      anchor_x: left
      anchor_y: center
  widget_player4score:
    - type: text        #PLAYER 4 SCORE
      text: PLAYER 4 - (player4|score)
      number_grouping: true
      min_digits: 2
      font_name: ARLRDBD
      font_size: 24
      y: bottom+70
      x: left+50
      z: 100
      anchor_x: left
      anchor_y: center
  widget_screenbackground:
    - type: image        #WORLD BACKGROUND
      image: world1_background
      z: 5




widget_player:
  s_maint_active:
    widget_debug:
      action: add

  show_debug:
    widget_debug:
      action: add

  #MULTIPLIER MULTIBALL
  show_multiplier{current_player.multiplier_mb==1}:
    widget_multiplier:
      action: remove
  show_multiplier{current_player.multiplier_mb==2}:
    widget_multiplier:
      action: update
      widget_settings:
          image: multiball_2x
  show_multiplier{current_player.multiplier_mb==3}:
    widget_multiplier:
      action: update
      widget_settings:
          image: multiball_3x

  #BALL COUNT WIDGETS
  show_ball_count{current_player.ball==1}:
    widget_ball1:
      action: add
    widget_ball2:
      action: remove
    widget_ball3:
      action: remove
  show_ball_count{current_player.ball==2}:
    widget_ball1:
      action: remove
    widget_ball2:
      action: add
    widget_ball3:
      action: remove
  show_ball_count{current_player.ball==3}:
    widget_ball1:
      action: remove
    widget_ball2:
      action: remove
    widget_ball3:
      action: add

  #ADD PLAYERS IF PLAYERS ARE ADDED
  player_added{num==2}:
    widget_player2score:
      action: add
  player_added{num==3}:
    widget_player3score:
      action: add
  player_added{num==4}:
    widget_player4score:
      action: add

  #SHOW SCORE BACKGROUND
  show_player_score: 
    widget_scorebackground:
      action: add

  #DISPLAY ONLY SCORES FOR ADDED PLAYERS AND BOLD CURRENT PLAYER
  show_player_score{current_player.number!=1}:
    widget_player1score:
      action: update
      widget_settings:
        font_size: 24

  show_player_score{current_player.number!=2 and game.num_players>=2}:
    widget_player2score:
      action: update
      widget_settings:
        font_size: 24

  show_player_score{current_player.number!=3 and game.num_players>=3}:
    widget_player3score:
      action: update
      widget_settings:
        font_size: 24

  show_player_score{current_player.number!=4 and game.num_players>=4}:
    widget_player4score:
      action: update
      widget_settings:
        font_size: 24

  #MAKE LARGER PLAYER BOLD
  show_player_score{current_player.number==1}:
    widget_player1score:
      action: update
      widget_settings:
        font_size: 36

  show_player_score{current_player.number==2 and game.num_players>=2}:
    widget_player2score:
      action: update
      widget_settings:
        font_size: 36

  show_player_score{current_player.number==3 and game.num_players>=3}:
     widget_player3score:
      action: update
      widget_settings:
        font_size: 36

  show_player_score{current_player.number==4 and game.num_players>=4}:
    widget_player4score:
      action: update
      widget_settings:
        font_size: 36



