#config_version=5
mode:
    start_events: multiball_lock_netherlock_locked_ball
    stop_events: multiball_nethermb_started, ball_ending
    priority: 1000

#play hurry up sound effect
sound_player:
  mode_netherready_started:
    heatbeat_music:
      action: play
      loops: -1
      track: music
      mode_end_action: stop
    # night_mode_ready:
    #   action: play
    #   loops: 0
    #   priority: 100
    #   track: voice
 
slides:
  netherready_slide:
    widgets:
      - type: text
        font_name: lazer84
        font_size: 70
        text: "Nether Ready"
        anchor_x: center
        anchor_y: center
        y: center+75
        z: 0
      - type: Text
        text: Plunge The Ball
        anchor_x: center
        anchor_y: center
        y: center-75
        z: 0
        font_name: lazer84
        font_size: 70
        animations:
          pre_show_slide:
            - property: opacity
              value: 0
              duration: .5s
            - property: opacity
              value: 1
              duration: .5s
              repeat: true   

slide_player:
  mode_netherready_started: netherready_slide
