#config_version=5
mode:
    start_events: stronghold_ready
    stop_events: multiball_strongholdmb_started, ball_ending
    priority: 1000

event_player:

#play hurry up sound effect
sound_player:
  mode_strongholdready_started:
    heatbeat_music:
      action: play
      loops: -1
      track: music
      mode_end_action: stop
    stronghold_ready:
      action: play
      loops: 0
      priority: 100
      track: voice
 
slides:
  strongholdready_slide:
    widgets:
      - type: text
        font_name: lazer84
        font_size: 70
        text: "Stronghold Ready"
        anchor_x: center
        anchor_y: center
        y: center+75
        z: 100
      - type: Text
        text: Plunge The Ball
        anchor_x: center
        anchor_y: center
        y: center-75
        z: 100
        font_name: lazer84
        font_size: 70
        animations:
          pre_show_slide:
            - property: opacity
              value: 0
              duration: .5s
            - property: opacity
              value: 1
              duration: .5s
              repeat: true   

widget_player:
  slide_strongholdready_slide_active:
    widget_screenbackground:
      action: add
      slide: strongholdready_slide
      widget_settings:
        image: stronghold_background

slide_player:
  mode_strongholdready_started: strongholdready_slide
