#config_version=5
mode:
    start_events: world2_started
    stop_events: world2_completed
    priority: 500

show_player:
  mode_world2_started:  #Setup GI Light Show
    show_world2gi:
      loops: -1
      speed: 1

light_player:
  mode_world2_started:
    lbackboxeven: yellow
    lundercab: yellow

sound_player:
  mode_world2_started:
    world2mode_music:
      action: play
      loops: -1
      mode_end_action: stop
  mode_villagermb_stopped:
    world2mode_music:
      action: play
      loops: -1
      mode_end_action: stop
  world2_collected: travel_ready  
  
variable_player:
  #setup environment variables
  mode_world2_started{current_player.world2_setup==0}:  
    #World Settings
    world_id:
      int: 2
      action: set
    world_name: 
      string: "World 2"
      action: set
    world_color: 
      string: "YELLOW"
      action: set

    #Item 1 Settings
    world_item1_name:
      string: "Sand"
      action: set 
    world_item1_color:
      string: "Yellow"
      action: set 
    world_item1_remaining:
      int: 4
      action: set

    #Item 2 Settings
    world_item2_name:
      string: "Stone"
      action: set 
    world_item2_color:
      string: "GRAY"
      action: set 
    world_item2_remaining:
      int: 4
      action: set

    #Item 3 Settings
    world_item3_name:
      string: "Ore"
      action: set 
    world_item3_color:
      string: "BROWN"
      action: set 
    world_item3_remaining:
      int: 4
      action: set

    #Item 4 Settings
    world_item4_name:
      string: "Wood"
      action: set 
    world_item4_color:
      string: "SLATEGRAY"
      action: set 
    world_item4_remaining:
      int: 4
      action: set

    #Mark World as Setup
    world2_setup: 1

widget_player:
  mode_world2_started:
    widget_screenbackground:
      action: update
      slide: world_slide
      widget_settings:
        image: world2_background
    widget_item1icon:
      action: update
      slide: world_slide
      widget_settings:
        image: Sand_Small
    widget_item2icon:
      action: update
      slide: world_slide
      widget_settings:
        image: SandStone_Small
    widget_item3icon:
      action: update
      slide: world_slide
      widget_settings:
        image: Coal_Small
    widget_item4icon:
      action: update
      slide: world_slide
      widget_settings:
        image: WoodAcadia_Small

event_player:
  world_collected:
    world2_collected
