#config_version=5
mode:
    start_events: world2_started
    stop_events: world2_completed
    priority: 500

show_player:
  mode_world2_started:  #Setup GI Light Show
    show_world2gi:
      loops: -1
      speed: 1

sound_player:
  mode_world2_started:
    world2mode_music:
      action: play
      loops: -1
      mode_end_action: stop
  mode_villagermb_stopped:
    world2mode_music:
      action: play
      loops: -1
      mode_end_action: stop
  world2_collected: travel_ready  
  
variable_player:
  #setup environment variables
  mode_world2_started:  
    #World Settings
    world_id:
      int: 2
      action: set
    world_name: 
      string: "World 2"
      action: set
    world_color: 
      string: "YELLOW"
      action: set

    #Item 1 Settings
    world_item1_name:
      string: "Sand"
      action: set 
    world_item1_color:
      string: "Yellow"
      action: set 
    world_item1_needed:
      int: 2
      action: set

    #Item 2 Settings
    world_item2_name:
      string: "Stone"
      action: set 
    world_item2_color:
      string: "GRAY"
      action: set 
    world_item2_needed:
      int: 2
      action: set

    #Item 3 Settings
    world_item3_name:
      string: "Ore"
      action: set 
    world_item3_color:
      string: "BROWN"
      action: set 
    world_item3_needed:
      int: 2
      action: set

    #Item 4 Settings
    world_item4_name:
      string: "Wood"
      action: set 
    world_item4_color:
      string: "SLATEGRAY"
      action: set 
    world_item4_needed:
      int: 2
      action: set

  logicblock_wc2_item1_counter_updated:
    world_item1_remaining:
      int: value
      action: set
  logicblock_wc2_item2_counter_updated:
    world_item2_remaining:
      int: value
      action: set
  logicblock_wc2_item3_counter_updated:
    world_item3_remaining:
      int: value
      action: set
  logicblock_wc2_item4_counter_updated:
    world_item4_remaining:
      int: value
      action: set

counters:
  wc2_item1_counter:
    count_events: collectitem1_hit
    reset_on_complete: False
    starting_count: 2
    count_complete_value: 0
    direction: down
    persist_state: true
    events_when_complete: w2_itemcheckcomplete
    multiple_hit_window: 500ms
    enable_events: mode_world2_started
  wc2_item2_counter:
    count_events: collectitem2_hit
    reset_on_complete: False
    starting_count: 2
    count_complete_value: 0
    direction: down
    persist_state: true
    events_when_complete: w2_itemcheckcomplete
    multiple_hit_window: 500ms
    enable_events: mode_world2_started
  wc2_item3_counter:
    count_events: collectitem3_hit
    reset_on_complete: False
    starting_count: 2
    count_complete_value: 0
    direction: down
    persist_state: true
    events_when_complete: w2_itemcheckcomplete
    multiple_hit_window: 500ms
    enable_events: mode_world2_started
  wc2_item4_counter:
    count_events: collectitem4_hit
    reset_on_complete: False
    starting_count: 2
    count_complete_value: 0
    direction: down
    persist_state: true
    events_when_complete: w2_itemcheckcomplete
    multiple_hit_window: 500ms
    enable_events: mode_world2_started

event_player:
  mode_world2_started:
    world2_started
    w2_itemcheckcomplete

  w2_itemcheckcomplete{current_player.world_item1_remaining == 0 and current_player.world_item2_remaining == 0 and current_player.world_item3_remaining == 0 and current_player.world_item4_remaining == 0}:
    world2_collected

  w2_itemcheckcomplete{current_player.world_item1_remaining > 0}:
    collectitem1_enabled
  w2_itemcheckcomplete{current_player.world_item1_remaining == 0}:
    collectitem1_disabled
  
  w2_itemcheckcomplete{current_player.world_item2_remaining > 0}:
    collectitem2_enabled
  w2_itemcheckcomplete{current_player.world_item2_remaining == 0}:
    collectitem2_disabled

  w2_itemcheckcomplete{current_player.world_item3_remaining > 0}:
    collectitem3_enabled
  w2_itemcheckcomplete{current_player.world_item3_remaining == 0}:
    collectitem3_disabled

  w2_itemcheckcomplete{current_player.world_item4_remaining > 0}:
    collectitem4_enabled
  w2_itemcheckcomplete{current_player.world_item4_remaining == 0}:
    collectitem4_disabled