#config_version=5
mode:
    start_events: mode_base_started
    stop_events: mode_base_ended
    priority: 2000
    code: divertercontrol.Base

# DIVERTER CONTROL STATES:
# ======== ======= ======

# START ("start")
#   - Diverter control has just started and state is not yet determined

# WORLD TRAVEL ("worldtravel")
#   - Left Loop Open / Drop Down Down
#   - Right Loop Open
#   - Travel Diverter Enabled 

# WORLD VILLAGER MB READY ("worldvillager")
#   - Left Loop Closed / Drop Down Down
#   - Right Loop Closed

# WORLD TOOLS FULL AND READY TO BE COLLECTED ("worldtoolsfull")
#    - Left Loop Closed / Drop Down Down
#    - Right Loop Open 

# WORLD TOOLS PARTIAL AND READY TO BE COLLECTED ("worldtools")
#    - Left Loop Closed / Drop Down Up
#    - Right Loop Closed 

# WORLD IDLE ("worldidle")
#    - Left Loop Closed / Drop Down Up
#    - Right Loop Open

# MULTIBALL VILLAGER RUNNING ("multiballvillager")
#   - Left Loop Closed / Drop Down Up
#   - Right Loop Open

# MULTIBALL NIGHT RUNNING ("multiballnight")
#   - Left Loop Open / Drop Down Down
#   - Right Loop Open

# MULTIBALL END RUNNING ("theend")
#   - Left Loop Open / Drop Down Down
#   - Right Loop Open


light_player:
  #Villager MB
  divertercontrol_statechanged{current_player.diverter_state=="multiballvillager"}:
    gi_loopupperleft: red
    gi_loopupperright: green

  #Night MB
  divertercontrol_statechanged{current_player.diverter_state=="multiballnight"}:
    gi_loopupperleft: green
    gi_loopupperright: green

  #THE END
  divertercontrol_statechanged{current_player.diverter_state=="theend"}:
    gi_loopupperleft: green
    gi_loopupperright: green

  #WORLD TRAVEL
  divertercontrol_statechanged{current_player.diverter_state=="worldtravel"}:
    gi_loopupperleft: blue
    gi_loopupperright: red

  #WORLD VILLAGER MB
  divertercontrol_statechanged{current_player.diverter_state=="worldvillager"}:
    gi_loopupperleft: purple
    gi_loopupperright: purple

  #WORLD TOOLS FULL
  divertercontrol_statechanged{current_player.diverter_state=="worldtoolsfull"}:
    gi_loopupperleft: yellow
    gi_loopupperright: yellow

  #WORLD TOOLS PARTIAL
  divertercontrol_statechanged{current_player.diverter_state=="worldtools"}:
    gi_loopupperleft: red
    gi_loopupperright: yellow

  #WORLD IDLE
  divertercontrol_statechanged{current_player.diverter_state=="worldidle"}:
    gi_loopupperleft: red
    gi_loopupperright: green
  

timers:
  #CHECK STATE EVERY SECOND TO ADJUST DIVERTERS
  checkdiverterstate:
    start_value: 0
    end_value: 1000
    direction: up
    control_events:
      - action: start
        event: mode_divertercontrol_started
      - action: restart
        event: timer_checkdiverterstate_complete

  #Left Drop Target Down
  leftdropreset:
    start_value: 0
    end_value: 1
    direction: up
    control_events:
      - action: restart
        event: drop_target_dt_upperdrop_down
      - action: restart
        event: diverter_rightloophit

  #Right Loop Events
  leftgateclose:
    start_value: 0
    end_value: 1
    direction: up
    control_events:
      - action: restart
        event: diverter_rightloophit
      
  #Left Loop Events
  rightgateclose:
    start_value: 0
    end_value: 1
    direction: up
    control_events:
      - action: restart
        event: diverter_leftloophit

coil_player:
  diverter_rightloophit:
    c_upperleftgate: enable
  timer_leftgateclose_complete:
    c_upperleftgate: disable

  diverter_leftloophit:
    c_upperrightgate: enable
  timer_rightgateclose_complete:
    c_upperrightgate: disable

shots:
  loopright:
    switch: s_loopright
  loopleft:
    switch: s_loopleft

event_player:
  #======================================================
  # LOOP CONTROL EVENTS    
  #======================================================

  #Left Loop Drop Reset Events
  timer_leftdropreset_complete{current_player.diverter_state=="worldidle"}: diverter_resetupperdrop
  timer_leftdropreset_complete{current_player.diverter_state=="worldtools"}: diverter_resetupperdrop
  timer_leftdropreset_complete{current_player.diverter_state=="multiballvillager"}: diverter_resetupperdrop
  
  #Left Loop Drop Up Events
  divertercontrol_statechanged{current_player.diverter_state=="worldidle"}: diverter_resetupperdrop
  divertercontrol_statechanged{current_player.diverter_state=="worldtools"}: diverter_resetupperdrop
  divertercontrol_statechanged{current_player.diverter_state=="multiballvillager"}: diverter_resetupperdrop

  #Left Loop Drop Down Events
  divertercontrol_statechanged{current_player.diverter_state=="worldtravel"}: diverter_dropupperdrop
  divertercontrol_statechanged{current_player.diverter_state=="worldvillager"}: diverter_dropupperdrop
  divertercontrol_statechanged{current_player.diverter_state=="worldtoolsfull"}: diverter_dropupperdrop
  divertercontrol_statechanged{current_player.diverter_state=="multiballnight"}: diverter_dropupperdrop

  #Right Loop Hit Events:
  loopright_hit{current_player.diverter_state=="worldidle"}: diverter_rightloophit, diverter_dropupperdrop
  loopright_hit{current_player.diverter_state=="multiballnight"}: diverter_rightloophit, diverter_dropupperdrop
  loopright_hit{current_player.diverter_state=="multiballvillager"}: diverter_rightloophit, diverter_dropupperdrop
 
  #Left Loop Hit Events:
  loopleft_hit{current_player.diverter_state=="multiballnight"}: diverter_leftloophit
  loopleft_hit{current_player.diverter_state=="worldtravel"}: diverter_leftloophit, diverter_leftlooptravelhit

  #DIVERTER CONTROLS
  divertercontrol_statechanged.1{current_player.diverter_state=="worldtravel"}:
    diverter_travel_enabled

  divertercontrol_statechanged.2{current_player.diverter_state!="worldtravel"}:
    diverter_travel_disabled


  mode_divertercontrol_started:
    - divertercontrol_checkworldstate

  #CHECK STATE AT INTERVAL
  timer_checkdiverterstate_tick:
    - divertercontrol_checkworldstate
    - divertercontrol_adjustlights

 



