#config_version=5
mode:
  priority: 20000
  
mode_settings:
  display_delay_ms: 2s
  hurry_up_delay_ms: 0
  bonus_entries:
  - event: bonus_items
    score: 1000
    player_score_entry: bonus_items

slide_player:
   mode_bonus_started: bonus_start_slide
   bonus_items: bonus_items_slide
   bonus_total: bonus_total_slide

slides:
  bonus_start_slide:
    widgets:
      - type: text
        text: BONUS
        number_grouping: true
        min_digits: 2
        font_name: lazer84
        font_size: 100
  bonus_items_slide:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_name: lazer84
        font_size: 100
      - type: text
        text: Collected Items (player|bonus_items)
        font_name: lazer84
        font_size: 50
        y: 200
        anchor_x: center
        anchor_y: bottom
  bonus_total_slide:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_name: lazer84
        font_size: 100
      - type: text
        text: Total Bonus
        font_name: lazer84
        font_size: 50
        y: 200
        anchor_x: center
        anchor_y: bottom