#config_version=5
mode:
    start_events: world6_started
    stop_events: world6_completed
    priority: 500

show_player:
  mode_world6_started:  #Setup GI Light Show
    show_world6gi:
      loops: -1
      speed: 1

light_player:
  mode_world6_started:
    lbackbox: purple
    lundercab: purple

sound_player:
  mode_world6_started:
    world6mode_music:
      action: play
      loops: -1
      mode_end_action: stop
  mode_villagermb_stopped:
    world6mode_music:
      action: play
      loops: -1
      mode_end_action: stop

#variable_player:
 #setup environment variables
 




event_player:
  mode_world6_started:
    world6_started
   