#config_version=5
mode:
    start_events: multiball_nethermb_started
    stop_events: multiball_nethermb_ended, ball_ending
    priority: 1000

#play hurry up sound effect


track_player:
  mode_nether_started:
    music:
      action: play
      fade: 1 sec

sound_player:
  mode_nether_started:
    nether_music:
      action: play
      loops: -1
      track: music
      mode_end_action: stop 
  mbnether_drop2_hit: zombie_death
  mbnether_drop5_hit: zombie_death
  mbnether_drop3_hit: creeper_death
  mbnether_drop4_hit: creeper_death

  nethermb_phase1_active: voice_nether_arrival
  nethermb_phase2_active: voice_nether_skeletonjackpot
  nethermb_phase3_active: voice_nether_ghastjackpot
  nethermb_jackpot_active: voice_nether_jackpot
  #mbnether_jackpot_hit: voice_nether_superjackpot
  #mbnether_superjackpot_hit: voice_nether_supermegajackpot


show_player:
  
  mbnether_drop2_hit:
    show_flashactionbarodd:
      show_tokens:
        color: purple
      loops: 0
      speed: 4
  
  mbnether_drop3_hit:
    show_flashactionbareven:
      show_tokens:
        color: red
      loops: 0
      speed: 4

  mbnether_drop4_hit:
    show_flashactionbareven:
      show_tokens:
        color: red
      loops: 0
      speed: 4

  mbnether_drop5_hit:
    show_flashactionbarodd:
      show_tokens:
        color: purple
      loops: 0
      speed: 4
    
  mode_nether_started:
    show_nethersetup:
      loops: -1
      speed: 4

  nethermb_phase1_started:
    show_netherphase1setup:
      loops: 0
      speed: 1
    show_nethersetup:
      loops: -1
      speed: 4

  nethermb_phase2_started:
    show_netherphase2setup:
      loops: 0
      speed: 1
    show_nethersetup:
      loops: -1
      speed: 2

  nethermb_phase3_started:
    show_netherphase3setup:
      loops: 0
      speed: 1
    show_nethersetup:
      loops: -1
      speed: 1
      
  nethermb_jackpot_active:
    show_netherjackpotready:
      loops: -1
      speed: 1

  mbnether_jackpot_hit: 
    show_nethersuperjackpot_lightshow:
      loops: 3
      speed: 2
    show_nethersuperjackpot_collected:
      loops: 0
      speed: 1
  mbnether_superjackpot_hit:
    show_nethersuperjackpot_lightshow:
      loops: 8
      speed: 5
    show_nethersupermegajackpot_collected:
      loops: 0
      speed: 1

light_player:
  nethermb_phase1_active:
    l_droparrow: green
  nethermb_phase2_active:
    l_droparrow: yellow
  nethermb_phase3_active:
    l_droparrow: red

state_machines:
  nethermb_state:
    states:
      start:
        label: Nether Mode Started
      phase1started:
        events_when_started: nethermb_phase1_started
      phase1running:
        events_when_started: nethermb_phase1_active
      phase2start:
        events_when_started: nethermb_phase2_started
      phase2running:
        events_when_started: nethermb_phase2_active
      phase3start:
        events_when_started: nethermb_phase3_started
      phase3running:
        events_when_started: nethermb_phase3_active
      jackpotrunning:
        events_when_started: nethermb_jackpot_active
    transitions:
      - source: start
        target: phase1started 
        events: mode_nether_started
      - source: phase1started
        target: phase1running 
        events: netherphase1setup_complete
      - source: phase1running
        target: phase2start 
        events: mbskeletons_complete
      - source: phase2start
        target: phase2running 
        events: netherphase2setup_complete
      - source: phase2running
        target: phase3start
        events: mbghast_complete
      - source: phase3start
        target: phase3running 
        events: netherphase3setup_complete
      - source: phase3running
        target: jackpotrunning
        events: mballdrops_complete
      - source: jackpotrunning
        target: phase1started
        events: mbnether_jackpot_hit, mbnether_superjackpot_hit

shot_profiles:
  mbtarget:
    states:
      - name: flashing  # step 2
        show: flash
      - name: lit  # step 3
        show: on
    loop: no

variable_player:
  mbskeletons_complete:
    score: 200000 * current_player.sword 
  mbghast_complete:
    score: 300000 *  current_player.sword 
  nethermb_alldrops_complete:
    score: 400000 * current_player.sword 

  mbnether_jackpot_hit:
    score: 500000 * current_player.sword 
  mbnether_superjackpot_hit:
    score: 1000000 *  current_player.sword 

shots:
  mbnether_jackpot:
    switch: s_collectitem3
    profile: mbtarget
    show_tokens:
      light: l_collectitem3
    disable_events: mode_nether_started, nethermb_phase1_started
    enable_events: nethermb_jackpot_active
  mbnether_superjackpot:
    switch: s_captiveball
    profile: mbtarget
    show_tokens:
      light: l_captivejackpot
    disable_events: mode_nether_started, nethermb_phase1_started
    enable_events: nethermb_jackpot_active
  mbnether_drop2:
    switch: s_drop2
    profile: mbtarget
    show_tokens:
      light: l_drop2
    reset_events: nethermb_phase1_started, nethermb_phase2_started, nethermb_phase3_started
  mbnether_drop3:
    switch: s_drop3
    profile: mbtarget
    show_tokens:
      light: l_drop3
    reset_events: nethermb_phase1_started, nethermb_phase2_started, nethermb_phase3_started
  mbnether_drop4:
    switch: s_drop4
    profile: mbtarget
    show_tokens:
      light: l_drop4
    reset_events: nethermb_phase1_started, nethermb_phase2_started, nethermb_phase3_started
  mbnether_drop5:
    switch: s_drop5
    profile: mbtarget
    show_tokens:
      light: l_drop5
    reset_events: nethermb_phase1_started, nethermb_phase2_started, nethermb_phase3_started

shot_groups:
  mbskeletons:
    shots: mbnether_drop2, mbnether_drop5
    disable_events: mode_nether_started, nethermb_phase2_started
    enable_events: nethermb_phase1_started
  mbghast:
    shots: mbnether_drop3, mbnether_drop4
    disable_events: mode_nether_started, nethermb_phase3_started
    enable_events: nethermb_phase2_started
  mballdrops:
    shots: mbnether_drop2, mbnether_drop3, mbnether_drop4, mbnether_drop5
    disable_events: mode_nether_started, nethermb_jackpot_active
    enable_events: nethermb_phase3_started

widgets:
  widget_netherswordplayer:
    - type: image        #SCORE BACKGROUND
      image: Sword_FullScreen_Dark_1x
      anchor_x: right
      anchor_y: bottom
      y: bottom
      x: right
      z: 10
  widget_nethervideobackground:
    - type: video
      video: video_nether_overview
      auto_play: true
      end_behavior: loop
      z: 6

  widget_superjackpot_collected:  #WORLD JACKPOT
    - type: text       
      text: SUPER JACKPOT
      font_name: ARLRDBD
      font_size: 36
      color: white
      y: center + 75
      x: center + 75
      z: 205
      anchor_x: center
      anchor_y: center   
    - type: text       
      text: 500000 x (player|sword) sword
      number_grouping: true
      font_name: ARLRDBD
      font_size: 52
      color: white
      y: center + 25
      x: center + 50
      z: 205
      anchor_x: center
      anchor_y: center     
    - type: image       
      image: popup_background
      anchor_x: center
      anchor_y: center
      y: center + 50
      x: center
      z: 200
    - type: image       
      image: chest_large
      anchor_x: center
      anchor_y: center
      y: center + 50
      x: center - 300
      z: 205

  widget_supermegajackpot_collected:  #WORLD JACKPOT
    - type: text       
      text: MEGA SUPER JACKPOT
      font_name: ARLRDBD
      font_size: 36
      color: white
      y: center + 75
      x: center + 75
      z: 205
      anchor_x: center
      anchor_y: center   
    - type: text       
      text: 1000000 x (player|sword) sword
      number_grouping: true
      font_name: ARLRDBD
      font_size: 52
      color: white
      y: center + 25
      x: center + 50
      z: 205
      anchor_x: center
      anchor_y: center     
    - type: image       
      image: popup_background
      anchor_x: center
      anchor_y: center
      y: center + 50
      x: center
      z: 200
    - type: image       
      image: chest_large
      anchor_x: center
      anchor_y: center
      y: center + 50
      x: center - 300
      z: 205

slides:
  nether_slide:
    widgets:
      - type: text
        font_name: lazer84
        font_size: 70
        text: "Nether Mode"
        z: 0


slide_player:
  mode_nether_started: nether_slide

widget_player:
  slide_nether_slide_active:
    widget_nethervideobackground:
      action: add
      slide: nether_slide
  
  #SHOW LARGE SWORD
  slide_nether_slide_active{current_player.sword==1}:
    widget_netherswordplayer:
      action: update
      slide: nether_slide
      widget_settings:
        image: Sword_FullScreen_1x
  slide_nether_slide_active{current_player.sword==2}:
    widget_netherswordplayer:
      action: update
      slide: nether_slide
      widget_settings:
        image: Sword_FullScreen_2x
  slide_nether_slide_active{current_player.sword==3}:
    widget_netherswordplayer:
      action: update
      slide: nether_slide
      widget_settings:
        image: Sword_FullScreen_3x
  slide_nether_slide_active{current_player.sword==4}:
    widget_netherswordplayer:
      action: update
      slide: nether_slide
      widget_settings:
        image: Sword_FullScreen_4x
  slide_nether_slide_active{current_player.sword==5}:
    widget_netherswordplayer:
      action: update
      slide: nether_slide
      widget_settings:
        image: Sword_FullScreen_5x
  

event_player:
  mode_nether_started:
    outlanegate_close

  slide_nether_slide_active:
    show_ball_count
    show_player_score
    show_multiplier
    #show_debug
  mbnether_jackpot_hit:
    outlanegate_open
  mb_super_jackpot_hit:
    outlanegate_open