#config_version=5
mode:
    start_events: nether_started
    stop_events: multiball_nethermb_ended
    priority: 1000

track_player:
  mode_nethercontroller_started:    #Clear Any Queued Sounds
    music:
      action: stop_all_sounds  
    sfx:
      action: stop_all_sounds 
    voice:
      action: stop_all_sounds 

event_player:
  #START NETHER MULTIBALL ON PLUNGE
  sw_playfield_active_active{device.multiball_locks.netherlock.locked_balls==1 and device.multiball_locks.netherlock.enabled}:
    nethermode_start

multiballs:
  nethermb:
    ball_count: 2
    ball_locks: bd_scoop
    enable_events: mode_nethercontroller_started
    start_events: nethermode_start
    shoot_again: 0s

multiball_locks:
  netherlock:
    balls_to_lock: 1
    locked_ball_counting_strategy: physical_only
    lock_devices: bd_scoop 
    enable_events: mode_nethercontroller_started
    disable_events: nethermode_start, nethermode_disable, multiball_villagermb_started, multiball_nightmb_started, multiball_nightvillagermb_started, multiball_lock_nightvillagerlock1_full
  
show_player:
  balldevice_bd_trough_ball_eject_attempt{num_attempts==0 and device.multiball_locks.netherlock.locked_balls==1 and current_player.world_id==1}:
    show_travelworld1:
      loops: 0
      speed: 1
      block_queue: true
      events_when_completed: nether_ready
  balldevice_bd_trough_ball_eject_attempt{num_attempts==0 and device.multiball_locks.netherlock.locked_balls==1 and current_player.world_id==2}:
    show_travelworld2:
      loops: 0
      speed: 1
      block_queue: true
      events_when_completed: nether_ready
  balldevice_bd_trough_ball_eject_attempt{num_attempts==0 and device.multiball_locks.netherlock.locked_balls==1 and current_player.world_id==3}:
    show_travelworld3:
      loops: 0
      speed: 1
      block_queue: true
      events_when_completed: nether_ready
  balldevice_bd_trough_ball_eject_attempt{num_attempts==0 and device.multiball_locks.netherlock.locked_balls==1 and current_player.world_id==4}:
    show_travelworld4:
      loops: 0
      speed: 1
      block_queue: true
      events_when_completed: nether_ready