#config_version=5
mode:
    start_events: world5_started
    stop_events: world5_completed
    priority: 300

show_player:
  mode_world5_started:  #Setup GI Light Show
    show_world5gi:
      loops: -1
      speed: 1
  collectitem1_hit: 
    show_itemcollected_world5item1:
      loops: 0
  collectitem2_hit:
    show_itemcollected_world5item2:
      loops: 0
  collectitem3_hit:
    show_itemcollected_world5item3:
      loops: 0
  collectitem4_hit:
    show_itemcollected_world5item4:
      loops: 0

light_player:
  mode_world5_started:
    lbackbox: red
    lundercab: red

sound_player:
  mode_world5_started:
    world5mode_music:
      action: play
      loops: -1
      mode_end_action: stop
  worldmultiball_ended:
    world5mode_music:
      action: play
      loops: -1
      mode_end_action: stop

variable_player:
 #setup environment variables
  mode_world5_started{current_player.world5_setup==0}:  
    #World Settings
    world_id:
      int: 5
      action: set
    world_name: 
      string: "World 5"
      action: set
    world_color: 
      string: "RED"
      action: set

    #Item 1 Settings
    world_item1_name:
      string: "Soul Sand"
      action: set 
    world_item1_color:
      string: "BROWN"
      action: set 
    world_item1_remaining:
      int: 25
      action: set

    #Item 2 Settings
    world_item2_name:
      string: "Smooth Stone"
      action: set 
    world_item2_color:
      string: "BLUE"
      action: set 
    world_item2_remaining:
      int: 25
      action: set

    #Item 3 Settings
    world_item3_name:
      string: "Gold Ore"
      action: set 
    world_item3_color:
      string: "YELLOW"
      action: set 
    world_item3_remaining:
      int: 25
      action: set

    #Item 4 Settings
    world_item4_name:
      string: "Crimson Wood"
      action: set 
    world_item4_color:
      string: "PURPLE"
      action: set 
    world_item4_remaining:
      int: 25
      action: set

    #Mark World as Setup
    world5_setup: 1

widgets:
  widget_world5videobackground:
    - type: video
      video: video_world5_overview
      auto_play: true
      end_behavior: loop
      z: 6

widget_player:
  mode_world5_started:
    widget_world5videobackground:
      action: add
      slide: world_slide
    widget_item1icon:
      action: update
      slide: world_slide
      widget_settings:
        image: SoulSand_Small
    widget_item2icon:
      action: update
      slide: world_slide
      widget_settings:
        image: NetherGold_Small
    widget_item3icon:
      action: update
      slide: world_slide
      widget_settings:
        image: Netherrack_Small
    widget_item4icon:
      action: update
      slide: world_slide
      widget_settings:
        image: WoodNether_Small

event_player:
  world_collected:
    world5_collected
  mode_villagercontroller_stopped:
    worldmultiball_ended
  mode_nightcontroller_stopped:
    worldmultiball_ended
  mode_nightvillagercontroller_stopped:
    worldmultiball_ended
  