#config_version=5
mode:
    start_events: world5_started
    stop_events: world5_completed
    priority: 500

show_player:
  mode_world5_started:  #Setup GI Light Show
    show_world5gi:
      loops: -1
      speed: 1

sound_player:
  mode_world5_started:
    world5mode_music:
      action: play
      loops: -1
      mode_end_action: stop
  mode_villagermb_stopped:
    world5mode_music:
      action: play
      loops: -1
      mode_end_action: stop

variable_player:
 #setup environment variables
  mode_world5_started:  
    #World Settings
    world_id:
      int: 5
      action: set
    world_name: 
      string: "World 5"
      action: set
    world_color: 
      string: "RED"
      action: set

    #Item 1 Settings
    world_item1_name:
      string: "Dirt"
      action: set 
    world_item1_color:
      string: "GREEN"
      action: set 
    world_item1_needed:
      int: 5
      action: set

    #Item 2 Settings
    world_item2_name:
      string: "Stone"
      action: set 
    world_item2_color:
      string: "GRAY"
      action: set 
    world_item2_needed:
      int: 5
      action: set

    #Item 3 Settings
    world_item3_name:
      string: "Ore"
      action: set 
    world_item3_color:
      string: "BROWN"
      action: set 
    world_item3_needed:
      int: 5
      action: set

    #Item 4 Settings
    world_item4_name:
      string: "Wood"
      action: set 
    world_item4_color:
      string: "SLATEGRAY"
      action: set 
    world_item4_needed:
      int: 5
      action: set

  logicblock_wc5_item1_counter_updated:
    world_item1_remaining:
      int: value
      action: set
  logicblock_wc5_item2_counter_updated:
    world_item2_remaining:
      int: value
      action: set
  logicblock_wc5_item3_counter_updated:
    world_item3_remaining:
      int: value
      action: set
  logicblock_wc5_item4_counter_updated:
    world_item4_remaining:
      int: value
      action: set

counters:
  wc5_item1_counter:
    count_events: collectitem1_hit
    reset_on_complete: False
    starting_count: 5
    count_complete_value: 0
    direction: down
    persist_state: true
    events_when_complete: w5_itemcheckcomplete
    multiple_hit_window: 500ms
    enable_events: mode_world5_started
  wc5_item2_counter:
    count_events: collectitem2_hit
    reset_on_complete: False
    starting_count: 5
    count_complete_value: 0
    direction: down
    persist_state: true
    events_when_complete: w5_itemcheckcomplete
    multiple_hit_window: 500ms
    enable_events: mode_world5_started
  wc5_item3_counter:
    count_events: collectitem3_hit
    reset_on_complete: False
    starting_count: 5
    count_complete_value: 0
    direction: down
    persist_state: true
    events_when_complete: w5_itemcheckcomplete
    multiple_hit_window: 500ms
    enable_events: mode_world5_started
  wc5_item4_counter:
    count_events: collectitem4_hit
    reset_on_complete: False
    starting_count: 5
    count_complete_value: 0
    direction: down
    persist_state: true
    events_when_complete: w5_itemcheckcomplete
    multiple_hit_window: 500ms
    enable_events: mode_world5_started

event_player:
  mode_world5_started:
    world5_started
    w5_itemcheckcomplete

  w5_itemcheckcomplete{current_player.world_item1_remaining == 0 and current_player.world_item2_remaining == 0 and current_player.world_item3_remaining == 0 and current_player.world_item4_remaining == 0}:
    world5_collected

  w5_itemcheckcomplete{current_player.world_item1_remaining > 0}:
    collectitem1_enabled
  w5_itemcheckcomplete{current_player.world_item1_remaining == 0}:
    collectitem1_disabled
  
  w5_itemcheckcomplete{current_player.world_item2_remaining > 0}:
    collectitem2_enabled
  w5_itemcheckcomplete{current_player.world_item2_remaining == 0}:
    collectitem2_disabled

  w5_itemcheckcomplete{current_player.world_item3_remaining > 0}:
    collectitem3_enabled
  w5_itemcheckcomplete{current_player.world_item3_remaining == 0}:
    collectitem3_disabled

  w5_itemcheckcomplete{current_player.world_item4_remaining > 0}:
    collectitem4_enabled
  w5_itemcheckcomplete{current_player.world_item4_remaining == 0}:
    collectitem4_disabled