#config_version=5
mode:
    start_events: mode_world1_started, mode_world2_started, mode_world3_started, mode_world4_started, mode_world5_started, mode_world6_started
    stop_events: world1_completed, world2_completed, world3_completed, world4_completed, world5_completed, world6_completed
    priority: 550

shots:
  #these are world specific, maybe move to world controller
  collectitem1:
    switch: s_collectitem1
  collectitem2:
    switch: s_collectitem2
  collectitem3:
    switch: s_collectitem3
  collectitem4:
    switch: s_collectitem4
  collectitem5:
    switch: s_collectitem5

counters:
  wc_item1_counter:
    count_events: collectitem1_hit
    reset_on_complete: False
    starting_count: current_player.world_item1_needed
    count_complete_value: 0
    direction: down
    persist_state: true
    events_when_complete: itemcheckcomplete
    multiple_hit_window: 500ms
    reset_events: world_started
    enable_events: mode_worldcontroller_started
  wc_item2_counter:
    count_events: collectitem2_hit
    reset_on_complete: False
    starting_count: current_player.world_item2_needed
    count_complete_value: 0
    direction: down
    persist_state: true
    events_when_complete: itemcheckcomplete
    multiple_hit_window: 500ms
    reset_events: world_started
    enable_events: mode_worldcontroller_started
  wc_item3_counter:
    count_events: collectitem4_hit
    reset_on_complete: False
    starting_count: current_player.world_item3_needed
    count_complete_value: 0
    direction: down
    persist_state: true
    events_when_complete: itemcheckcomplete
    multiple_hit_window: 500ms
    reset_events: world_started
    enable_events: mode_worldcontroller_started
  wc_item4_counter:
    count_events: collectitem5_hit
    reset_on_complete: False
    starting_count: current_player.world_item4_needed
    count_complete_value: 0
    direction: down
    persist_state: true
    events_when_complete: itemcheckcomplete
    multiple_hit_window: 500ms
    reset_events: world_started
    enable_events: mode_worldcontroller_started

variable_player:
  logicblock_wc_item1_counter_updated:
    wc_item1_counter_count:
      int: value
      action: set
  logicblock_wc_item2_counter_updated:
    wc_item2_counter_count:
      int: value
      action: set
  logicblock_wc_item3_counter_updated:
    wc_item3_counter_count:
      int: value
      action: set
  logicblock_wc_item4_counter_updated:
    wc_item4_counter_count:
      int: value
      action: set
  


event_player:
  itemcheckcomplete{current_player.world_id==1 and current_player.wc_item1_counter_count == 0 and current_player.wc_item2_counter_count == 0 and current_player.wc_item3_counter_count == 0 and current_player.wc_item4_counter_count == 0}:
    world1_completed
  itemcheckcomplete{current_player.world_id==2 and current_player.wc_item1_counter_count == 0 and current_player.wc_item2_counter_count == 0 and current_player.wc_item3_counter_count == 0 and current_player.wc_item4_counter_count == 0}:
    world2_completed
  itemcheckcomplete{current_player.world_id==3 and current_player.wc_item1_counter_count == 0 and current_player.wc_item2_counter_count == 0 and current_player.wc_item3_counter_count == 0 and current_player.wc_item4_counter_count == 0}:
    world3_completed
  itemcheckcomplete{current_player.world_id==4 and current_player.wc_item1_counter_count == 0 and current_player.wc_item2_counter_count == 0 and current_player.wc_item3_counter_count == 0 and current_player.wc_item4_counter_count == 0}:
    world4_completed
  itemcheckcomplete{current_player.world_id==5 and current_player.wc_item1_counter_count == 0 and current_player.wc_item2_counter_count == 0 and current_player.wc_item3_counter_count == 0 and current_player.wc_item4_counter_count == 0}:
    world5_completed
  itemcheckcomplete{current_player.world_id==6 and current_player.wc_item1_counter_count == 0 and current_player.wc_item2_counter_count == 0 and current_player.wc_item3_counter_count == 0 and current_player.wc_item4_counter_count == 0}:
    world6_completed


light_player:
 mode_worldcontroller_started:
    l_collectitem1: GREEN
    l_collectitem2: GRAY
    l_collectitem3: RED
    l_collectitem4: BROWN
    l_collectitem5: SLATEGRAY
  
#play hurry up sound effect
sound_player:
  mode_worldcontroller_started:
    basemode_music:
      action: stop
  mode_worldcontroller_started{current_player.world_id==1}:
    world1mode_music:
      action: play
      loops: -1
      mode_end_action: stop 
  mode_worldcontroller_started{current_player.world_id==2}:
    world2mode_music:
      action: play
      loops: -1
      mode_end_action: stop 

slides:
  wc_slide_world:
    priority: 100
    widgets:
      # - type: text
      #   text: (score)
      #   number_grouping: true
      #   min_digits: 2
      #   font_name: lazer84
      #   font_size: 100
      # - type: text
      #   text: (player|world_name)
      #   font_name: lazer84
      #   font_size: 50
      #   y: 200
      #   anchor_x: center
      #   anchor_y: bottom
      # - type: text
      #   text: PLAYER (number)
      #   y: 10
      #   x: 10
      #   font_name: lazer84
      #   font_size: 50
      #   anchor_x: left
      #   anchor_y: bottom
      # - type: text
      #   text: BALL (ball)
      #   y: 10
      #   x: right-10
      #   anchor_x: right
      #   anchor_y: bottom
      #   font_name: lazer84
      #   font_size: 50
      # - type: text
      #   text: (player|world_item1_name)
      #   anchor_y: bottom
      #   anchor_x: middle
      #   y: 75
      #   x: center-300
      #   font_name: Arial
      #   font_size: 40
      # - type: text
      #   text: (player|wc_item1_counter_count)
      #   anchor_y: bottom
      #   anchor_x: middle
      #   y: 125
      #   x: center-300
      #   font_name: Arial
      #   font_size: 40
      # - type: text
      #   text: (player|world_item2_name)
      #   anchor_y: bottom
      #   anchor_x: middle
      #   y: 75
      #   x: center-150
      #   font_name: Arial
      #   font_size: 40
      # - type: text
      #   text: (player|wc_item2_counter_count)
      #   anchor_y: bottom
      #   anchor_x: middle
      #   y: 125
      #   x: center-150
      #   font_name: Arial
      #   font_size: 40
      # - type: text
      #   text: (player|world_item3_name)
      #   anchor_y: bottom
      #   anchor_x: middle
      #   y: 75
      #   x: center
      #   font_name: Arial
      #   font_size: 40
      # - type: text
      #   text: (player|wc_item3_counter_count)
      #   anchor_y: bottom
      #   anchor_x: middle
      #   y: 125
      #   x: center
      #   font_name: Arial
      #   font_size: 40
      # - type: text
      #   text: (player|world_item4_name)
      #   anchor_y: bottom
      #   anchor_x: middle
      #   y: 75
      #   x: center+150
      #   font_name: Arial
      #   font_size: 40
      # - type: text
      #   text: (player|wc_item4_counter_count)
      #   anchor_y: bottom
      #   anchor_x: middle
      #   y: 125
      #   x: center+150
      #   font_name: Arial
      #   font_size: 40
      - type: image
        image: item_background
        anchor_x: left
        anchor_y: top
        y: top+625
        x: left+860

      - type: image
        image: score_background
        anchor_x: left
        anchor_y: top
        y: top+500
        x: left+5
      - type: image
        image: world1_background

slide_player:
  mode_worldcontroller_started: wc_slide_world


