#config_version=5
mode:
    start_events:  mode_world1_started, mode_world2_started, mode_world3_started, mode_world4_started, mode_world5_started
    stop_events:  mode_world1_stopped, mode_world2_stopped, mode_world3_stopped, mode_world4_stopped, mode_world5_stopped
    priority: 550


# TODO: Travel was disable between balls

shot_profiles:
  collectshot:
    states:
      - name: lit
        show: on

shots:
  collectitem1:
    switch: s_collectitem1
    profile: collectshot
    show_tokens:
      leds: l_collectitem1
    enable_events: collectitem1_enabled
    disable_events: collectitem1_disabled
  collectitem2:
    switch: s_collectitem2
    profile: collectshot
    show_tokens:
      leds: l_collectitem2
    enable_events: collectitem2_enabled
    disable_events: collectitem2_disabled
  collectitem3:
    switch: s_collectitem4
    profile: collectshot
    show_tokens:
      leds: l_collectitem4
    enable_events: collectitem3_enabled
    disable_events: collectitem3_disabled
  collectitem4:
    switch: s_collectitem5
    profile: collectshot
    show_tokens:
      leds: l_collectitem5
    enable_events: collectitem4_enabled
    disable_events: collectitem4_disabled


variable_player:
 #COLLECT ITEM 1 HIT
  collectitem1_hit:
    world_item1_remaining: -1 * current_player.shovel
    score: 10000 * current_player.shovel * current_player.multiplier_mb
    bonus_items: 1 * current_player.shovel
    world_jackpot_items: 1 * current_player.shovel
    world_jackpot_base: 1000 * current_player.shovel

  collectitem1_hit{current_player.world_item1_remaining < 0}:
    world_item1_remaining:
      int: 0
      action: set

  #COLLECT ITEM 2 HIT
  collectitem2_hit:
    world_item2_remaining: -1 * current_player.pickaxe
    score: 10000 * current_player.pickaxe * current_player.multiplier_mb 
    bonus_items: 1  * current_player.pickaxe 
    world_jackpot_items: 1  * current_player.pickaxe 
    world_jackpot_base: 1000 * current_player.pickaxe 

  collectitem2_hit{current_player.world_item2_remaining < 0}:
    world_item2_remaining:
      int: 0
      action: set

  #COLLECT ITEM 3 HIT
  collectitem3_hit:
    world_item3_remaining: -1 * current_player.pickaxe
    score: 10000 * current_player.pickaxe * current_player.multiplier_mb
    bonus_items: 1 * current_player.pickaxe
    world_jackpot_items: 1 * current_player.pickaxe
    world_jackpot_base: 1000 * current_player.pickaxe

  collectitem3_hit{current_player.world_item3_remaining < 0}:
    world_item3_remaining:
      int: 0
      action: set

  #COLLECT ITEM 4 HIT
  collectitem4_hit:
    world_item4_remaining: -1 * current_player.axe
    score: 10000 * current_player.axe * current_player.multiplier_mb
    bonus_items: 1 * current_player.axe
    world_jackpot_items: 1 * current_player.axe
    world_jackpot_base: 1000 * current_player.axe
    
  collectitem4_hit{current_player.world_item4_remaining < 0}:
    world_item4_remaining:
      int: 0
      action: set

  #TODO: Bug - Will receive move items and points than available items 


event_player:
  mode_worldcontroller_started:
    world_itemcheckcomplete

  collectitem1_hit:
    world_itemcheckcomplete

  collectitem2_hit:
    world_itemcheckcomplete

  collectitem3_hit:
    world_itemcheckcomplete

  collectitem4_hit:
    world_itemcheckcomplete


  world_itemcheckcomplete{current_player.world_item1_remaining == 0 and current_player.world_item2_remaining == 0 and current_player.world_item3_remaining == 0 and current_player.world_item4_remaining == 0}:
    world_collected

  world_itemcheckcomplete{current_player.world_item1_remaining > 0}:
    collectitem1_enabled
  world_itemcheckcomplete{current_player.world_item1_remaining == 0}:
    collectitem1_disabled
  
  world_itemcheckcomplete{current_player.world_item2_remaining > 0}:
    collectitem2_enabled
  world_itemcheckcomplete{current_player.world_item2_remaining == 0}:
    collectitem2_disabled

  world_itemcheckcomplete{current_player.world_item3_remaining > 0}:
    collectitem3_enabled
  world_itemcheckcomplete{current_player.world_item3_remaining == 0}:
    collectitem3_disabled

  world_itemcheckcomplete{current_player.world_item4_remaining > 0}:
    collectitem4_enabled
  world_itemcheckcomplete{current_player.world_item4_remaining == 0}:
    collectitem4_disabled


