#config_version=5
mode:
    start_events: mode_world1_started, mode_world2_started, mode_world3_started, mode_world4_started, mode_world5_started, mode_world6_started
    stop_events: mode_world1_ending, mode_world2_ending, mode_world3_ending, mode_world4_ending, mode_world5_ending, mode_world6_ending
    priority: 550

shots:
  collectitem1:
    switch: s_collectitem1
  collectitem2:
    switch: s_collectitem2
  collectitem3:
    switch: s_collectitem3
  collectitem4:
    switch: s_collectitem4
  collectitem5:
    switch: s_collectitem5

counters:
  wc_item1_counter:
    count_events: collectitem1_hit
    reset_on_complete: False
    starting_count: current_player.world_item1_needed
    count_complete_value: 0
    direction: down
    persist_state: true
    events_when_complete: itemcheckcomplete
    multiple_hit_window: 500ms
    reset_events: world_started
    enable_events: world_started
  wc_item2_counter:
    count_events: collectitem2_hit
    reset_on_complete: False
    starting_count: current_player.world_item2_needed
    count_complete_value: 0
    direction: down
    persist_state: true
    events_when_complete: itemcheckcomplete
    multiple_hit_window: 500ms
    reset_events: world_started
    enable_events: world_started
  wc_item3_counter:
    count_events: collectitem4_hit
    reset_on_complete: False
    starting_count: current_player.world_item3_needed
    count_complete_value: 0
    direction: down
    persist_state: true
    events_when_complete: itemcheckcomplete
    multiple_hit_window: 500ms
    reset_events: world_started
    enable_events: world_started
  wc_item4_counter:
    count_events: collectitem5_hit
    reset_on_complete: False
    starting_count: current_player.world_item4_needed
    count_complete_value: 0
    direction: down
    persist_state: true
    events_when_complete: itemcheckcomplete
    multiple_hit_window: 500ms
    reset_events: world_started
    enable_events: world_started

variable_player:
  logicblock_wc_item1_counter_updated:
    wc_item1_counter_count:
      int: value
      action: set
  logicblock_wc_item2_counter_updated:
    wc_item2_counter_count:
      int: value
      action: set
  logicblock_wc_item3_counter_updated:
    wc_item3_counter_count:
      int: value
      action: set
  logicblock_wc_item4_counter_updated:
    wc_item4_counter_count:
      int: value
      action: set
  


event_player:
  itemcheckcomplete{current_player.world_id==1 and current_player.wc_item1_counter_count == 0 and current_player.wc_item2_counter_count == 0 and current_player.wc_item3_counter_count == 0 and current_player.wc_item4_counter_count == 0}:
    #divertercontrol_leftloop_travel
    world1_completed
  itemcheckcomplete{current_player.world_id==2 and current_player.wc_item1_counter_count == 0 and current_player.wc_item2_counter_count == 0 and current_player.wc_item3_counter_count == 0 and current_player.wc_item4_counter_count == 0}:
    world2_completed
  itemcheckcomplete{current_player.world_id==3 and current_player.wc_item1_counter_count == 0 and current_player.wc_item2_counter_count == 0 and current_player.wc_item3_counter_count == 0 and current_player.wc_item4_counter_count == 0}:
    world3_completed
  itemcheckcomplete{current_player.world_id==4 and current_player.wc_item1_counter_count == 0 and current_player.wc_item2_counter_count == 0 and current_player.wc_item3_counter_count == 0 and current_player.wc_item4_counter_count == 0}:
    world4_completed
  itemcheckcomplete{current_player.world_id==5 and current_player.wc_item1_counter_count == 0 and current_player.wc_item2_counter_count == 0 and current_player.wc_item3_counter_count == 0 and current_player.wc_item4_counter_count == 0}:
    world5_completed
  itemcheckcomplete{current_player.world_id==6 and current_player.wc_item1_counter_count == 0 and current_player.wc_item2_counter_count == 0 and current_player.wc_item3_counter_count == 0 and current_player.wc_item4_counter_count == 0}:
    world6_completed


# light_player:
#  mode_worldcontroller_started:
#     l_collectitem1: GREEN
#     l_collectitem2: GRAY
#     l_collectitem3: RED
#     l_collectitem4: BROWN
#     l_collectitem5: SLATEGRAY
  





