#config_version=5
mode:
    start_events:  mode_world1_starting, mode_world2_starting, mode_world3_starting, mode_world4_starting, mode_world5_starting
    stop_events:  mode_world1_stopped, mode_world2_stopped, mode_world3_stopped, mode_world4_stopped, mode_world5_stopped
    priority: 200

shot_profiles:
  collectshot:
    states:
      - name: lit
        show: on

counters:
  counter_villagermultiball:
    count_events: worldspinner_hit
    starting_count: 0
    count_interval: 1
    count_complete_value: 20
    persist_state: true
    restart_events: multiball_villagermb_ended, multiball_nightvillagermb_ended
    disable_events: villagermb_disable, multiball_nightmb_started
    enable_events: mode_worldcontroller_started, multiball_nightmb_ended

  counter_nightmultiball:
    count_events: popbumper1_hit, popbumper2_hit, popbumper3_hit
    starting_count: 0
    count_interval: 1
    count_complete_value: 10
    persist_state: true
    restart_events: multiball_nightmb_ended, multiball_nightvillagermb_ended
    disable_events: nightmb_disable, multiball_villagermb_started
    enable_events: mode_worldcontroller_started, multiball_villagermb_ended

multiball_locks:
  villagerlock:
    balls_to_lock: 1
    locked_ball_counting_strategy: physical_only
    lock_devices: bd_topkicker 
    enable_events: villagermultiball_ready
    disable_events: nightvillagermultiball_ready, villagermultiball_start, villagermb_disable, villagerornightmb_disable

  nightlock:
    balls_to_lock: 1
    locked_ball_counting_strategy: physical_only
    lock_devices: bd_scoop 
    enable_events: nightmultiball_ready
    disable_events: nightvillagermultiball_ready, nightmultiball_start, nightmb_disable, villagerornightmb_disable

  nightvillagerlock1:
    balls_to_lock: 1
    locked_ball_counting_strategy: physical_only
    lock_devices: bd_topkicker 
    enable_events: nightvillagermultiball_ready
    disable_events: nightvillagermultiball_disable, nightvillagermultiball_start, villagerornightmb_disable

  nightvillagerlock2:
    balls_to_lock: 1
    locked_ball_counting_strategy: physical_only
    lock_devices: bd_scoop 
    enable_events: nightvillagermultiball_enablelock2
    disable_events: nightvillagermultiball_disable, nightvillagermultiball_start, villagerornightmb_disable

multiballs:
  villagermb:
    ball_count: 2
    ball_locks: bd_topkicker
    enable_events: villagermultiball_ready
    disable_events: nightvillagermultiball_ready
    start_events: villagermultiball_start
    shoot_again: 0s

  nightmb:
    ball_count: 2
    ball_locks: bd_scoop
    enable_events: nightmultiball_ready
    disable_events: nightvillagermultiball_ready
    start_events: nightmultiball_start
    shoot_again: 0s

  nightvillagermb:
    ball_count: 3
    ball_locks: bd_topkicker, bd_scoop
    enable_events: nightvillagermultiball_ready
    start_events: nightvillagermultiball_start
    shoot_again: 0s


shots:
  worldspinner:
    switch: s_spinner

  collectitem1:
    switch: s_collectitem1
    profile: collectshot
    show_tokens:
      leds: l_collectitem1
    enable_events: collectitem1_enabled
    disable_events: collectitem1_disabled
  collectitem2:
    switch: s_collectitem2
    profile: collectshot
    show_tokens:
      leds: l_collectitem2
    enable_events: collectitem2_enabled
    disable_events: collectitem2_disabled
  collectitem3:
    switch: s_collectitem4
    profile: collectshot
    show_tokens:
      leds: l_collectitem4
    enable_events: collectitem3_enabled
    disable_events: collectitem3_disabled
  collectitem4:
    switch: s_collectitem5
    profile: collectshot
    show_tokens:
      leds: l_collectitem5
    enable_events: collectitem4_enabled
    disable_events: collectitem4_disabled

sound_player:
  #VILLAGER MULTIBALL
  s_spinner_active: 
    villagersp: 
      action: play
      loops: 1

  villagermultiball_ready:
    villager_multiball_ready

  nightmultiball_ready:
    night_mode_ready
  
  collectitem1_hit: collect_tool
  collectitem2_hit: collect_tool
  collectitem3_hit: collect_tool
  collectitem4_hit: collect_tool
  collectitem5_hit: collect_tool

light_player:
  show_spinner_progress{device.counters.counter_villagermultiball.value>=4 and device.counters.counter_villagermultiball.value<8}: #LEVEL 1000
    l_spinner1: green
    l_spinner2: off
    l_spinner3: off
    l_spinner4: off
  show_spinner_progress{device.counters.counter_villagermultiball.value>=8 and device.counters.counter_villagermultiball.value<12}: #LEVEL 1000
    l_spinner1: off
    l_spinner2: green
    l_spinner3: off
    l_spinner4: off
  show_spinner_progress{device.counters.counter_villagermultiball.value>=12 and device.counters.counter_villagermultiball.value<16}: #LEVEL 1000
    l_spinner1: off
    l_spinner2: off
    l_spinner3: green
    l_spinner4: off
  show_spinner_progress{device.counters.counter_villagermultiball.value>=16}:
    l_spinner3: off 
    l_spinner2: off 
    l_spinner1: off
    l_spinner4: green 
  multiball_nightvillagermb_started:
    l_spinner1: green
    l_spinner2: green
    l_spinner3: green
    l_spinner4: green
  multiball_villagermb_started:
    l_spinner1: green
    l_spinner2: green
    l_spinner3: green
    l_spinner4: green
  multiball_villagermb_ended:
    l_spinner1: off
    l_spinner2: off
    l_spinner3: off
    l_spinner4: off
  multiball_nightvillager_ended:
    l_spinner1: off
    l_spinner2: off
    l_spinner3: off
    l_spinner4: off

  nightmultiball_ready:
    lgi: 
      color: purple
      fade: 5000ms
    lactionbar: 
      color: purple
      fade: 5000ms

  multiball_nightmb_ended:
    lgi:
      color: white
      fade: 5000ms
    lactionbar: off

  multiball_nightvillagermb_ended:
    lgi:
      color: white
      fade: 5000ms
    lactionbar: off



variable_player:

  #RESET VARIABLES
  mode_worldcontroller_started:
    multiball_mb:
      int: 1
      action: set 

  #SPINNER SCORING
  worldspinner_hit{device.counters.counter_villagermultiball.value<4}: #LEVEL 100
    score: 100 * current_player.multiplier_mb
    world_jackpot_base: 1000
  worldspinner_hit{device.counters.counter_villagermultiball.value>=4 and device.counters.counter_villagermultiball.value<8}: #LEVEL 1000
    score: 1000 * current_player.multiplier_mb
    world_jackpot_base: 1000
  worldspinner_hit{device.counters.counter_villagermultiball.value>=8 and device.counters.counter_villagermultiball.value<12}: #LEVEL 2000
    score: 2000 * current_player.multiplier_mb
    world_jackpot_base: 1000
  worldspinner_hit{device.counters.counter_villagermultiball.value>=12 and device.counters.counter_villagermultiball.value<16}: #LEVEL 3000
    score: 3000 * current_player.multiplier_mb
    world_jackpot_base: 1000
  worldspinner_hit{device.counters.counter_villagermultiball.value>=16}: #LEVEL 4000
    score: 4000 * current_player.multiplier_mb
    world_jackpot_base: 1000

 

  #MULTIBALL VARIABLES

  multiball_villagermb_started: #VILLAGER MULTIBALL STARTED
    multiplier_mb:
      int: 2
      action: set
    villagermb_ready:
      int: 0
      action: set

  multiball_villagermb_ended: #VILLAGER MULTIBALL ENDED
    multiplier_mb:
      int: 1
      action: set

  multiball_nightmb_started:
    multiplier_mb:
      int: 2
      action: set
    nightmb_ready:
      int: 0
      action: set

  multiball_nightmb_ended:
    multiplier_mb:
      int: 1
      action: set

  multiball_nightvillagermb_started:
    multiplier_mb:
      int: 3
      action: set
    nightmb_ready:
      int: 0
      action: set
    villagermb_ready:
      int: 0
      action: set

  multiball_nightvillagermb_ended:
    multiplier_mb:
      int: 1
      action: set

  multiball_nightvillagermb_lost_ball:
    multiplier_mb:
      int: 2
      action: set

  multiball_lost_ball{current_player.multiplier_mb==3}:
    multiplier_mb:
      int: 2
      action: set

  villagermb_disable:
    villagermb_ready:
      int: 0
      action: set

  villagermultiball_ready:
    villagermb_ready:
      int: 1
      action: set

  nightmultiball_ready:
    nightmb_ready:
      int: 1
      action: set

  nightvillagermultiball_ready:
    nightmb_ready:
      int: 1
      action: set
    villagermb_ready:
      int: 1
      action: set

  nightmb_disable:
    nightmb_ready:
      int: 0
      action: set

 #COLLECT ITEM 1 HIT
  collectitem1_hit:
    world_item1_remaining: -1 * current_player.shovel
    score: 10000 * current_player.shovel * current_player.multiplier_mb
    bonus_items: 1 * current_player.shovel
    world_jackpot_items: 1 * current_player.shovel
    world_jackpot_base: 1000 * current_player.shovel

  collectitem1_hit{current_player.world_item1_remaining < 0}:
    world_item1_remaining:
      int: 0
      action: set

  #COLLECT ITEM 2 HIT
  collectitem2_hit:
    world_item2_remaining: -1 * current_player.pickaxe
    score: 10000 * current_player.pickaxe * current_player.multiplier_mb 
    bonus_items: 1  * current_player.pickaxe 
    world_jackpot_items: 1  * current_player.pickaxe 
    world_jackpot_base: 1000 * current_player.pickaxe 

  collectitem2_hit{current_player.world_item2_remaining < 0}:
    world_item2_remaining:
      int: 0
      action: set

  #COLLECT ITEM 3 HIT
  collectitem3_hit:
    world_item3_remaining: -1 * current_player.pickaxe
    score: 10000 * current_player.pickaxe * current_player.multiplier_mb
    bonus_items: 1 * current_player.pickaxe
    world_jackpot_items: 1 * current_player.pickaxe
    world_jackpot_base: 1000 * current_player.pickaxe

  collectitem3_hit{current_player.world_item3_remaining < 0}:
    world_item3_remaining:
      int: 0
      action: set

  #COLLECT ITEM 4 HIT
  collectitem4_hit:
    world_item4_remaining: -1 * current_player.axe
    score: 10000 * current_player.axe * current_player.multiplier_mb
    bonus_items: 1 * current_player.axe
    world_jackpot_items: 1 * current_player.axe
    world_jackpot_base: 1000 * current_player.axe
    
  collectitem4_hit{current_player.world_item4_remaining < 0}:
    world_item4_remaining:
      int: 0
      action: set

  #TODO: Bug - Will receive move items and points than available items 


widgets:
  widget_item1needed:
    - type: text        #ITEM 1 NEEDED
      text: (player|world_item1_remaining)
      font_name: ARLRDBD
      font_size: 25
      y: bottom+24
      x: right-462
      z: 100
      anchor_x: center
      anchor_y: bottom
  widget_item2needed:
    - type: text        #ITEM 2 NEEDED
      text: (player|world_item2_remaining)
      font_name: ARLRDBD
      font_size: 25
      y: bottom+24
      x: right-373
      z: 100
      anchor_x: center
      anchor_y: bottom
  widget_item3needed:
    - type: text        #ITEM 3 NEEDED
      text: (player|world_item3_remaining)
      font_name: ARLRDBD
      font_size: 25
      y: bottom+24
      x: right-284
      z: 100
      anchor_x: center
      anchor_y: bottom
  widget_item4needed:
    - type: text        #ITEM 4 NEEDED
      text: (player|world_item4_remaining)
      font_name: ARLRDBD
      font_size: 25
      y: bottom+24
      x: right-196
      z: 100
      anchor_x: center
      anchor_y: bottom
  widget_itembackground:
    - type: image        #ITEM BACKGROUND
      image: item_background
      anchor_x: left
      anchor_y: bottom
      y: bottom+15
      x: left+860
      z: 10
  widget_item1icon:
    - type: image       #ITEM 1 ICON
      image: Grass_Small
      anchor_x: center
      anchor_y: center
      y: bottom+ 93
      x: left + 904
      z: 100
  widget_item2icon:
    - type: image       #ITEM 2 ICON
      image: Grass_Small
      anchor_x: center
      anchor_y: center
      y: bottom+ 93
      x: left + 993
      z: 100
  widget_item3icon:
    - type: image       #ITEM 3 ICON
      image: Grass_Small
      anchor_x: center
      anchor_y: center
      y: bottom+ 93
      x: left + 1082
      z: 100
  widget_item4icon:
    - type: image       #ITEM 4 ICON
      image: Grass_Small
      anchor_x: center
      anchor_y: center
      y: bottom+ 93
      x: left + 1171
      z: 100

  # widget_videobackground:
  #   - type: video
  #     video: world1_overview
  #     auto_play: true
  #     volume: 0
  #     end_behavior: loop
  #     z: 6



slides:
  world_slide:
    widgets:
      - type: text
        font_name: lazer84
        font_size: 70
        text: "Pincraft\nLoading"
        z: 0

slide_player:
  mode_worldcontroller_started:
    world_slide

widget_player:
  mode_worldcontroller_started:
    widget_itembackground:
      slide: world_slide
    widget_item1needed:
      slide: world_slide
    widget_item2needed:
      slide: world_slide
    widget_item3needed:
      slide: world_slide
    widget_item4needed:
      slide: world_slide


event_player:
  mode_base_started:
    world_itemcheckcomplete

  mode_worldcontroller_started:
    world_itemcheckcomplete
    show_player_score
    show_ball_count
    show_tools
    show_extraball
    show_debug
    show_spinner_progress
    show_bonus_items

  worldspinner_hit:
    show_spinner_progress

  mode_worldcontroller_started{current_player.villagermb_ready==1 and current_player.nightmb_ready==0}:
    villagermultiball_ready

  mode_worldcontroller_started{current_player.nightmb_ready==1 and current_player.villagermb_ready==0}:
    nightmultiball_ready

  mode_worldcontroller_started{current_player.nightmb_ready==1 and current_player.villagermb_ready==1}:
    villagermultiball_ready
    nightmultiball_ready
    nightvillagermultiball_ready

  collectitem1_hit:
    world_itemcheckcomplete
    show_bonus_items  #Used for Bonus Display

  collectitem2_hit:
    world_itemcheckcomplete
    show_bonus_items  #Used for Bonus Display

  collectitem3_hit:
    world_itemcheckcomplete
    show_bonus_items  #Used for Bonus Display

  collectitem4_hit:
    world_itemcheckcomplete
    show_bonus_items  #Used for Bonus Display

  world_itemcheckcomplete{current_player.world_item1_remaining <= 0 and current_player.world_item2_remaining <= 0 and current_player.world_item3_remaining <= 0 and current_player.world_item4_remaining <= 0}:
    show_bonus_items

  world_itemcheckcomplete{current_player.world_item1_remaining > 0}:
    collectitem1_enabled
  world_itemcheckcomplete{current_player.world_item1_remaining == 0}:
    collectitem1_disabled
  
  world_itemcheckcomplete{current_player.world_item2_remaining > 0}:
    collectitem2_enabled
  world_itemcheckcomplete{current_player.world_item2_remaining == 0}:
    collectitem2_disabled

  world_itemcheckcomplete{current_player.world_item3_remaining > 0}:
    collectitem3_enabled
  world_itemcheckcomplete{current_player.world_item3_remaining == 0}:
    collectitem3_disabled

  world_itemcheckcomplete{current_player.world_item4_remaining > 0}:
    collectitem4_enabled
  world_itemcheckcomplete{current_player.world_item4_remaining == 0}:
    collectitem4_disabled


  #ENABLE VILLAGER MULTIBALL 
  logicblock_counter_villagermultiball_complete:
    villagermultiball_ready

  logicblock_counter_nightmultiball_complete:
    nightmultiball_ready

  #STACK MULTIBALLS
  nightmultiball_ready{current_player.villagermb_ready==1}:
    nightvillagermultiball_ready

  villagermultiball_ready{current_player.nightmb_ready==1}:
    nightvillagermultiball_ready  
  

  #START VILLAGER MULTIBALL ON PLUNGE
  sw_playfield_active_active{device.multiball_locks.villagerlock.locked_balls==1 and device.multiball_locks.villagerlock.enabled}:
    villagermultiball_start

  #START NIGHT MULTIBALL ON PLUNGE
  sw_playfield_active_active{device.multiball_locks.nightlock.locked_balls==1 and device.multiball_locks.nightlock.enabled}:
    nightmultiball_start

  #START NIGHT/VILLAGER MULTIBALL ON PLUNGE
  sw_playfield_active_active{device.multiball_locks.nightvillagerlock1.locked_balls==1 and device.multiball_locks.nightvillagerlock1.enabled and device.multiball_locks.nightvillagerlock2.locked_balls==1 and device.multiball_locks.nightvillagerlock2.enabled}:
    nightvillagermultiball_start

  multiball_lock_nightvillagerlock1_full:
    nightvillagermultiball_enablelock2

  # ball_drain{device.multiball_locks.nightvillagerlock1.locked_balls==1}:
  #   eject_topkicker
  #   nightvillagermultiball_disable

  balldevice_bd_trough_ball_count_changed{device.ball_devices.bd_trough.balls==1}:
    multiball_lost_ball

  balldevice_bd_trough_ball_count_changed{device.ball_devices.bd_trough.balls==3}:
    trough_allballs

queue_relay_player:
  ball_ending{device.multiball_locks.nightvillagerlock1.locked_balls==1}:
    post: eject_topkicker
    wait_for: trough_allballs