#config_version=5
mode:
  start_events: mode_base_started
  stop_events: mode_base_stopped
  priority: 300

shots:
  tool1:
    switch: s_tooltarget1
    show_tokens:
      light: l_toolcollect1
  tool2:
    switch: s_tooltarget2
    show_tokens:
      light: l_toolcollect2
  tool3:
    switch: s_tooltarget3
    show_tokens:
      light: l_toolcollect3

  craft1: 
    switch: s_whitedot1
    show_tokens:
      light: l_craft1
  craft2:
    switch: s_whitedot2
    show_tokens:
      light: l_craft2
  craft3:
    switch: s_whitedot3
    show_tokens:
      light: l_craft3
  craft4:
    switch: s_whitedot4
    show_tokens:
      light: l_craft4


shot_groups:
  toolcollect:
    shots: tool1, tool2, tool3
    enable_events: start_collect_tools
    restart_events: restart_collect_tools
    disable_events: disable_collect_tools
  craftcollect:
    shots: craft1, craft2, craft3, craft4
    enable_events: crafting_enabled
    disable_events: mode_tools_started

sound_player:
  s_tooltarget1_active: collect_tool
  s_tooltarget2_active: collect_tool
  s_tooltarget3_active: collect_tool
  crafting_enabled: craft_ready

light_player:
  light_onetool:
    l_tool1ready: darkblue
  light_twotools:
    l_tool2ready: darkblue
  light_threetools:
    l_tool3ready: darkblue
  light_fourtools:
    l_toolcollect1: darkblue
    l_toolcollect2: darkblue
    l_toolcollect3: darkblue
  crafting_enabled:
    l_craftlit: white

  display_tools{current_player.shovel==1}:
    l_tool1: Brown
  display_tools{current_player.axe==1}:
    l_tool2: Brown
  display_tools{current_player.pickaxe==1}:
    l_tool3: Brown
  display_tools{current_player.sword==1}:
    l_tool4: Brown

  display_tools{current_player.shovel==2}:
    l_tool1: MidnightBlue
  display_tools{current_player.axe==2}:
    l_tool2: MidnightBlue
  display_tools{current_player.pickaxe==2}:
    l_tool3: MidnightBlue
  display_tools{current_player.sword==2}:
    l_tool4: MidnightBlue

  display_tools{current_player.shovel==3}:
    l_tool1: Silver
  display_tools{current_player.axe==3}:
    l_tool2: Silver
  display_tools{current_player.pickaxe==3}:
    l_tool3: Silver
  display_tools{current_player.sword==3}:
    l_tool4: Silver

  display_tools{current_player.shovel==4}:
    l_tool1: Yellow
  display_tools{current_player.axe==4}:
    l_tool2: Yellow
  display_tools{current_player.pickaxe==4}:
    l_tool3: Yellow
  display_tools{current_player.sword==4}:
    l_tool4: Yellow

  display_tools{current_player.shovel==5}:
    l_tool1: Teal
  display_tools{current_player.axe==5}:
    l_tool2: Teal
  display_tools{current_player.pickaxe==5}:
    l_tool3: Teal
  display_tools{current_player.sword==5}:
    l_tool4: Teal

  display_tools{current_player.bonus_multiplier==2}:
    l_bonus2x: MidnightBlue
    l_bonus3x: off
    l_bonus4x: off
    l_bonus5x: off
  display_tools{current_player.bonus_multiplier==3}:
    l_bonus2x: MidnightBlue
    l_bonus3x: Silver
    l_bonus4x: off
    l_bonus5x: off
  display_tools{current_player.bonus_multiplier==4}:
    l_bonus2x: MidnightBlue
    l_bonus3x: Silver
    l_bonus4x: Yellow
    l_bonus5x: off
  display_tools{current_player.bonus_multiplier==5}:
    l_bonus2x: MidnightBlue
    l_bonus3x: Silver
    l_bonus4x: Yellow
    l_bonus5x: Teal

event_player:
  mode_tools_started:
    display_tools

state_machines:
  tools_ready:
    states:
      start:
        label: No Tools Are Ready
        events_when_started: start_collect_tools
      onetoolready:
        label: One Tool Is Ready
        events_when_started: tool_collected, restart_collect_tools, light_onetool
      twotoolsready:
        label: Two Tools Are Ready
        events_when_started: restart_collect_tools, light_twotools
      threetoolsready:
        label: Three Tools Are Ready
        events_when_started: restart_collect_tools, light_threetools
      fourtoolsready:
        label: Four Tools Are Ready
        events_when_started: disable_collect_tools, light_fourtools
    transitions:
      - source: start
        target: onetoolready
        events: toolcollect_complete 
      - source: onetoolready
        target: twotoolsready
        events: toolcollect_complete
      - source: twotoolsready
        target: threetoolsready
        events: toolcollect_complete
      - source: threetoolsready
        target: fourtoolsready
        events: toolcollect_complete

  craft_ready:
    states:
      start:
        label: Craft Table is not Ready
      craftenabled:
        label: Tool is Ready
        events_when_started: crafting_enabled
      craftready:
        label: Craft Table is Ready
        events_when_started: crafting_ready
    transitions:
      - source: start
        target: craftenabled
        events: tool_collected
      - source: craftenabled
        target: craftready
        events: craftcollect_complete


      