#config_version=5
mode:
  start_events: mode_worldcontroller_started
  stop_events: mode_worldcontroller_stopped
  priority: 500


shot_profiles:
  craftprofile:
    states:
      - name: unlit
        show: off
      - name: lit
        show: on

shots:
  tool1:
    switch: s_tooltarget1
    show_tokens:
      light: l_toolcollect1
  tool2:
    switch: s_tooltarget2
    show_tokens:
      light: l_toolcollect2
  tool3:
    switch: s_tooltarget3
    show_tokens:
      light: l_toolcollect3

  craft1: 
    switch: s_whitedot1
    profile: craftprofile
    hit_events: craft1_collect
    show_tokens:
      light: l_craft1
  craft2:
    switch: s_whitedot2
    profile: craftprofile
    hit_events: craft2_collect
    show_tokens:
      light: l_craft2
  craft3:
    switch: s_whitedot3
    profile: craftprofile
    hit_events: craft3_collect
    show_tokens:
      light: l_craft3
  craft4:
    switch: s_whitedot4
    profile: craftprofile
    hit_events: craft4_collect
    show_tokens:
      light: l_craft4

variable_player:
  #mode_tools_started:

  crafting_awarded{current_player.bonus_multiplier==5 and current_player.tools_ready>=1 and current_player.tools_collected < 1}:
    score: 1000000
    world_jackpot_base: 100000
    tools_collected: 1
  crafting_awarded{current_player.bonus_multiplier==5 and current_player.tools_ready>=2 and current_player.tools_collected < 2}:
    score: 1000000
    world_jackpot_base: 100000
    tools_collected: 1
  crafting_awarded{current_player.bonus_multiplier==5 and current_player.tools_ready>=3 and current_player.tools_collected < 3}:
    score: 1000000
    world_jackpot_base: 100000
    tools_collected: 1   
  crafting_awarded{current_player.bonus_multiplier==5 and current_player.tools_ready==4}:
    score: 1000000
    world_jackpot_base: 100000
    tools_collected: 1

  crafting_awarded{current_player.bonus_multiplier<5 and current_player.tools_ready>=1 and current_player.tools_collected < 1}:
    shovel: 1
    tools_collected: 1
    world_jackpot_base: 1000
  crafting_awarded{current_player.bonus_multiplier<5 and current_player.tools_ready>=2 and current_player.tools_collected < 2}:
    axe: 1
    tools_collected: 1
    world_jackpot_base: 1000
  crafting_awarded{current_player.bonus_multiplier<5 and current_player.tools_ready>=3 and current_player.tools_collected < 3}:
    pickaxe: 1
    tools_collected: 1
    world_jackpot_base: 1000
  crafting_awarded{current_player.bonus_multiplier<5 and current_player.tools_ready==4}:
    sword: 1
    tools_collected: 1
    world_jackpot_base: 1000



  recalculate_tools:
    tools_ready: 1      #increase tool count by 1

  #Lite Crafting Full if all 4 tools are ready to be collected
  recalculate_tools{current_player.tools_ready==4}:
    crafting_full:
      int: 1
      action: set
    

  tool_level_complete{current_player.bonus_multiplier<5}:  #Increase Bonus Multiplier
    bonus_multiplier: 1

  reset_tool_variables:
    tools_ready:
      int: 0
      action: set
    tools_collected:
      int: 0
      action: set

  craftcollect_complete:
   crafting_ready:
      int: 1
      action: set

  crafting_lit:
    crafting_enabled:
      int: 1
      action: set

  crafting_disable:
    crafting_enabled: 
      int: 0
      action: set
    crafting_ready:
      int: 0
      action: set
    crafting_full:
      int: 0
      action: set

shot_groups:
  toolcollect:
    shots: tool1, tool2, tool3
    enable_events: start_collect_tools
    restart_events: restart_collect_tools
    disable_events: disable_collect_tools
  craftcollect:
    shots: craft1, craft2, craft3, craft4
    enable_events: crafting_lit
    reset_events: crafting_awarded
    disable_events: crafting_disable

sound_player:
  tool1_hit: collect_tool
  tool2_hit: collect_tool
  tool3_hit: collect_tool
  crafting_lit{current_player.tools_ready<=1}: craft_ready


show_player:
  crafting_isready:
    show_craftingready:
      loops: -1
      speed: 3
      priority: 501
      action: play
  crafting_disable:
    show_craftingready:
      action: stop

light_player:
  tools_updated:
    l_tool1ready: off
    l_tool2ready: off
    l_tool3ready: off
  tools_updated{current_player.tools_ready==1}:
    l_tool1ready: darkblue
  tools_updated{current_player.tools_ready==2}:
    l_tool2ready: darkblue
  tools_updated{current_player.tools_ready==3}:
    l_tool3ready: darkblue
  tools_updated{current_player.tools_ready==4}:
    l_tool1ready: darkblue
    l_tool2ready: darkblue
    l_tool3ready: darkblue

  crafting_lit:
    l_craftlit: white
  crafting_disable:
    l_craftlit: off
  crafting_isready:
    l_craftlit: yellow

event_player:
  mode_tools_started{current_player.crafting_enabled==0}:
    - crafting_disable
    - tools_updated

  mode_tools_started{current_player.crafting_enabled==1 and current_player.crafting_ready==0}:
    - crafting_lit
    - tools_updated

  mode_tools_started{current_player.crafting_enabled==1 and current_player.crafting_ready==1}:
    - crafting_lit
    - crafting_isready
    - tools_updated

  craftcollect_complete:
    - crafting_isready

  toolcollect_complete:
    - recalculate_tools
    - tool_collected
    - crafting_lit
   

  multiball_nethermb_ended{current_player.crafting_enabled==1}:
    - crafting_lit
    - tools_updated

  multiball_villagermb_ended{current_player.crafting_enabled==1}:
    - crafting_lit
    - tools_updated
  
  #CRAFTING!!!
  balldevice_bd_topkicker_ball_enter{current_player.crafting_ready==1}:
    - crafting_awarded
    - tools_updated
    - crafting_disable
    - check_craftingcomplete


  #LIT A CRAFT LIGHT IF NOT ALL COLLECTED YET
  balldevice_bd_topkicker_ball_enter{current_player.crafting_ready==0 and current_player.crafting_enabled==1 and current_player.shot_craft1==0}:
    craft1_collect
  balldevice_bd_topkicker_ball_enter{current_player.crafting_ready==0 and current_player.crafting_enabled==1 and current_player.shot_craft1==1 and current_player.shot_craft2==0}:
    craft2_collect
  balldevice_bd_topkicker_ball_enter{current_player.crafting_ready==0 and current_player.crafting_enabled==1 and current_player.shot_craft1==1 and current_player.shot_craft2==1  and current_player.shot_craft3==0}:
    craft3_collect
  balldevice_bd_topkicker_ball_enter{current_player.crafting_ready==0 and current_player.crafting_enabled==1 and current_player.shot_craft1==1  and current_player.shot_craft2==1  and current_player.shot_craft3==1  and current_player.shot_craft4==0}:
    craft4_collect



  #Check if all 4 tools are collected
  check_craftingcomplete{current_player.tools_collected==4}:
    - crafting_disable
    - tool_level_complete
    - reset_tool_variables
    - restart_collect_tools
    - tools_updated

  tool_collected:
    - tools_updated
  
  #Allow the user to collect additional tools up to 4
  tool_collected{current_player.tools_ready<4}:
    - restart_collect_tools
  tool_collected{current_player.tools_ready==4}:
    - disable_collect_tools

  



      