#config_version=5
mode:
  start_events: mode_base_started
  stop_events: mode_base_stopped
  priority: 300

#TODO: Should not be able to collect level 6 tools

shots:
  tool1:
    switch: s_tooltarget1
    show_tokens:
      light: l_toolcollect1
  tool2:
    switch: s_tooltarget2
    show_tokens:
      light: l_toolcollect2
  tool3:
    switch: s_tooltarget3
    show_tokens:
      light: l_toolcollect3

  craft1: 
    switch: s_whitedot1
    show_tokens:
      light: l_craft1
  craft2:
    switch: s_whitedot2
    show_tokens:
      light: l_craft2
  craft3:
    switch: s_whitedot3
    show_tokens:
      light: l_craft3
  craft4:
    switch: s_whitedot4
    show_tokens:
      light: l_craft4

variable_player:
  #mode_tools_started:

  crafting_awarded{current_player.bonus_multiplier==5 and current_player.tools_ready>=1 and current_player.tools_collected < 1}:
    score: 1000000
    world_jackpot_base: 100000
    tools_collected: 1
  crafting_awarded{current_player.bonus_multiplier==5 and current_player.tools_ready>=2 and current_player.tools_collected < 2}:
    score: 1000000
    world_jackpot_base: 100000
    tools_collected: 1
  crafting_awarded{current_player.bonus_multiplier==5 and current_player.tools_ready>=3 and current_player.tools_collected < 3}:
    score: 1000000
    world_jackpot_base: 100000
    tools_collected: 1   
  crafting_awarded{current_player.bonus_multiplier==5 and current_player.tools_ready==4}:
    score: 1000000
    world_jackpot_base: 100000
    tools_collected: 1

  crafting_awarded{current_player.bonus_multiplier<5 and current_player.tools_ready>=1 and current_player.tools_collected < 1}:
    shovel: 1
    tools_collected: 1
    world_jackpot_base: 1000
  crafting_awarded{current_player.bonus_multiplier<5 and current_player.tools_ready>=2 and current_player.tools_collected < 2}:
    axe: 1
    tools_collected: 1
    world_jackpot_base: 1000
  crafting_awarded{current_player.bonus_multiplier<5 and current_player.tools_ready>=3 and current_player.tools_collected < 3}:
    pickaxe: 1
    tools_collected: 1
    world_jackpot_base: 1000
  crafting_awarded{current_player.bonus_multiplier<5 and current_player.tools_ready==4}:
    sword: 1
    tools_collected: 1
    world_jackpot_base: 1000



  recalculate_tools:
    tools_ready: 1      #increase tool count by 1

  tool_level_complete{current_player.bonus_multiplier<5}:  #Increase Bonus Multiplier
    bonus_multiplier: 1

  reset_tool_variables:
    tools_ready:
      int: 0
      action: set
    tools_collected:
      int: 0
      action: set

  craftcollect_complete:
   crafting_ready:
      int: 1
      action: set

  crafting_lit:
    crafting_enabled:
      int: 1
      action: set

  crafting_disable:
    crafting_enabled: 
      int: 0
      action: set
    crafting_ready:
      int: 0
      action: set

shot_groups:
  toolcollect:
    shots: tool1, tool2, tool3
    enable_events: start_collect_tools
    restart_events: restart_collect_tools
    disable_events: disable_collect_tools
  craftcollect:
    shots: craft1, craft2, craft3, craft4
    enable_events: crafting_lit
    reset_events: crafting_awarded
    disable_events: crafting_disable

sound_player:
  tool1_hit: collect_tool
  tool2_hit: collect_tool
  tool3_hit: collect_tool
  crafting_lit{current_player.tools_ready<=1}: craft_ready

light_player:
  display_tools:
    l_tool1ready: off
    l_tool2ready: off
    l_tool3ready: off
  display_tools{current_player.tools_ready==1}:
    l_tool1ready: darkblue
  display_tools{current_player.tools_ready==2}:
    l_tool2ready: darkblue
  display_tools{current_player.tools_ready==3}:
    l_tool3ready: darkblue
  display_tools{current_player.tools_ready==4}:
    l_tool1ready: darkblue
    l_tool2ready: darkblue
    l_tool3ready: darkblue

  crafting_lit:
    l_craftlit: white
  crafting_disable:
    l_craftlit: off

  display_tools{current_player.shovel==1}:
    l_tool1: Brown
  display_tools{current_player.axe==1}:
    l_tool2: Brown
  display_tools{current_player.pickaxe==1}:
    l_tool3: Brown
  display_tools{current_player.sword==1}:
    l_tool4: Brown

  display_tools{current_player.shovel==2}:
    l_tool1: MidnightBlue
  display_tools{current_player.axe==2}:
    l_tool2: MidnightBlue
  display_tools{current_player.pickaxe==2}:
    l_tool3: MidnightBlue
  display_tools{current_player.sword==2}:
    l_tool4: MidnightBlue

  display_tools{current_player.shovel==3}:
    l_tool1: Silver
  display_tools{current_player.axe==3}:
    l_tool2: Silver
  display_tools{current_player.pickaxe==3}:
    l_tool3: Silver
  display_tools{current_player.sword==3}:
    l_tool4: Silver

  display_tools{current_player.shovel==4}:
    l_tool1: Yellow
  display_tools{current_player.axe==4}:
    l_tool2: Yellow
  display_tools{current_player.pickaxe==4}:
    l_tool3: Yellow
  display_tools{current_player.sword==4}:
    l_tool4: Yellow

  display_tools{current_player.shovel==5}:
    l_tool1: Teal
  display_tools{current_player.axe==5}:
    l_tool2: Teal
  display_tools{current_player.pickaxe==5}:
    l_tool3: Teal
  display_tools{current_player.sword==5}:
    l_tool4: Teal

  display_tools{current_player.bonus_multiplier==2}:
    l_bonus2x: MidnightBlue
    l_bonus3x: off
    l_bonus4x: off
    l_bonus5x: off
  display_tools{current_player.bonus_multiplier==3}:
    l_bonus2x: off
    l_bonus3x: Silver
    l_bonus4x: off
    l_bonus5x: off
  display_tools{current_player.bonus_multiplier==4}:
    l_bonus2x: off
    l_bonus3x: off
    l_bonus4x: Yellow
    l_bonus5x: off
  display_tools{current_player.bonus_multiplier==5}:
    l_bonus2x: off
    l_bonus3x: off
    l_bonus4x: off
    l_bonus5x: Teal

event_player:
  mode_tools_started{current_player.crafting_enabled==0}:
    - crafting_disable
    - display_tools

  mode_tools_started{current_player.crafting_enabled==1}:
    - crafting_lit
    - display_tools

  toolcollect_complete:
    - recalculate_tools
    - tool_collected
    - crafting_lit
   

  multiball_nightmb_ended{current_player.crafting_enabled==1}:
    - crafting_lit
    - display_tools

  multiball_villagermb_ended{current_player.crafting_enabled==1}:
    - crafting_lit
    - display_tools
  
  #CRAFTING!!!
  balldevice_bd_topkicker_ball_enter{current_player.crafting_ready==1}:
    - crafting_awarded
    - display_tools
    - crafting_disable
    - check_craftingcomplete

  #Check if all 4 tools are collected
  check_craftingcomplete{current_player.tools_collected==4}:
    - crafting_disable
    - tool_level_complete
    - reset_tool_variables
    - restart_collect_tools
    - display_tools

  # check_craftingcomplete{current_player.tools_collected==4 and current_player.bonus_multiplier==5}:
  #   - crafting_disable
  #   - tool_level_complete
  #   - reset_tool_variables
  #   - disable_collect_tools
  #   - display_tools

  tool_collected:
    - display_tools
  
  #Allow the user to collect additional tools up to 4
  tool_collected{current_player.tools_ready<4}:
    - restart_collect_tools
  tool_collected{current_player.tools_ready==4}:
    - disable_collect_tools

  



      