#config_version=5

# COIL CONFIGURATION
#--------------------------------------------
coils:
  # Blue Coil Loom

  #A0-B0-0: Currently Empty
  #A0-B0-1: Currently Empty

  c_flipper_right_main:
    number: A0-B0-3
    default_pulse_ms: 40
  c_flipper_right_hold:
    number: A0-B0-2
    allow_enable: true 
  c_flipper_upper_main:
    number: A0-B0-4
    default_pulse_ms: 40
  c_flipper_upper_hold:
    number: A0-B0-5
    allow_enable: true 
  c_flipper_gate_main:
    number: A0-B0-6
    default_pulse_ms: 10
  c_flipper_gate_hold:
    number: A0-B0-7
    allow_enable: true

  #Orange Coil Loom
    #gates
  c_rightinlanegate:
    number: A0-B1-2
    allow_enable: true
  c_upperleftgate:
    number: A0-B1-1
    allow_enable: true
  c_upperrightgate:
    number: A0-B1-0
    allow_enable: true
  c_flipper_left_main:
    number: A0-B1-3
    default_pulse_ms: 40
  c_flipper_left_hold:
    number: A0-B1-4
    allow_enable: true 
  c_leftinlanegate:
    number: A0-B1-5
    allow_enable: true
  # A0-B1-6: Currently Empty
  # A0-B1-7: Currently Empty

  # Green Coil Loom   
  c_trough_eject:
    number: A1-B1-7
    default_pulse_ms: 25
  c_popbumper1:
    number: A1-B1-0
    default_pulse_ms: 20 
  c_popbumber2:
    number: A1-B1-1
    default_pulse_ms: 20
  c_popbumber3:
    number: A1-B1-2
    default_pulse_ms: 20
  c_upperdrop_drop:
    number: A1-B1-5
    default_pulse_ms: 10
  c_upperdrop_reset:
    number: A1-B1-3
    default_pulse_ms: 20
  c_slingshot:
    number: A1-B1-6
    default_pulse_ms: 30
  c_topkicker:
    number: A1-B1-4
    default_pulse_ms: 35

  #Brown Coil Loom
  c_scoop_eject:
    number: A1-B0-0
    default_pulse_ms: 13
  c_drop_target_reset:
    number: A1-B0-1
    default_pulse_ms: 45
  c_drop_target1_drop:
    number: A1-B0-2
    default_pulse_ms: 30
  c_drop_target2_drop:
    number: A1-B0-3
    default_pulse_ms: 30
  c_drop_target3_drop:
    number: A1-B0-4
    default_pulse_ms: 30
  c_drop_target4_drop:
    number: A1-B0-5
    default_pulse_ms: 30
  c_drop_target5_drop:
    number: A1-B0-6
    default_pulse_ms: 30
  c_drop_target6_drop:
    number: A1-B0-7
    default_pulse_ms: 30

# AUTOFIRE COILS CONFIGURATION
#--------------------------------------------
autofire_coils:
  right_slingshot:
    coil: c_slingshot
    switch: s_rightsling
  popbumper1:
    coil: c_popbumper1
    switch: s_popbumper1
  popbumper2:
    coil: c_popbumber2
    switch: s_popbumper2
  popbumper3:
    coil: c_popbumber3
    switch: s_popbumper3