#config_version=5
# PINCRAFT
# V.03 ALPHA
# WRITTEN BY: BRIAN SMITH, CONNOR SMITH
# KNOWN GOOD VERSION: MPF v0.52.7

# HARDWARE CONFIGURATION
#--------------------------------------------
hardware:
  platform: p3_roc
  driverboards: pdb
  lights: fadecandy

playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger        #this was changed from bd_plunger / reverted back

# p_roc:
#   pd_led_boards:
#     4:       
#       use_ws281x_0: True
#       ws281x_0_first_address: 100
#       ws281x_0_last_address: 350
#     5:
#       use_ws281x_0: True


# DISPLAY CONFIGURATION
#--------------------------------------------
displays:
  lcd:
    width: 1366
    height: 768

window:
  width: 1366
  height: 768
  title: Pincraft
  resizable: false
  fullscreen: false
 # borderless: true
  exit_on_escape: true
  #source_display: lcd

# SWITCH CONFIGURATION
#--------------------------------------------
switches:
  s_left_flipper:
    number: A0-B0-7
    tags: left_flipper
  s_right_flipper:
    number: A0-B0-6
    tags: right_flipper
  s_tilt:
    number: A0-B0-5
  s_start:
    number: A0-B1-7
    tags: start
  s_maint:
    number: A0-B1-6
  s_credit_right:
    number: A0-B1-4

#P1 - Bank 0
  s_drop6:
    number: A1-B0-2
    tags: s_playfield, s_drop
  s_drop5:
    number: A1-B0-5
    tags: s_playfield, s_drop
  s_drop4:
    number: A1-B0-7
    tags: s_playfield, s_drop
  s_drop3:
    number: A1-B0-3
    tags: s_playfield, s_drop
  s_drop2:
    number: A1-B0-6
    tags: s_playfield, s_drop
  s_drop1:
    number: A1-B0-4
    tags: s_playfield, s_drop
  s_leftoutlane:
    number: A1-B0-1
    tags: s_playfield, s_drop
  s_leftinlane:
    number: A1-B0-0
    tags: playfield_active, s_playfield, s_drop

#P1 - Bank 1
  s_collectitem1:
    number: A1-B1-7
    tags: playfield_active
    ignore_window_ms: 100
    debounce: normal
  s_collectitem2:
    number: A1-B1-6
    tags: playfield_active
    ignore_window_ms: 100
    debounce: normal
  s_collectitem3:
    number: A1-B1-5
    tags: playfield_active
    ignore_window_ms: 100
    debounce: normal
  s_collectitem4:
    number: A1-B1-4
    tags: playfield_active
    ignore_window_ms: 100
    debounce: normal
  s_collectitem5:
    number: A1-B1-3
    tags: playfield_active
    ignore_window_ms: 100
    debounce: normal
 
#P2 - Bank 0
  s_plungerlane:
    number: A2-B0-2
  s_trough1:
    number: A2-B0-4
    type: NC
  s_trough2:
    number: A2-B0-5
  s_trough3:
    number: A2-B0-6
  s_trough4:
    number: A2-B0-7
  s_troughjam:
    number: A2-B0-3
    type: NC
  s_rightoutlane:
    number: A2-B0-1
    tags: playfield_active
  s_rightinlane:
    number: A2-B0-0
    tags: playfield_active

#P2 - Bank 1
  s_leftsling:
    number: A2-B1-0
    tags: playfield_active
  s_rightsling:
    number: A2-B1-1
  s_scoup:
    number: A2-B1-2
    type: NC
  s_centertarget:
    number: A2-B1-3
    tags: playfield_active
  s_bumperrail:
    number: A2-B1-4
    tags: playfield_active
  s_popbumper1:
    number: A2-B1-6
  s_popbumper2:
    number: A2-B1-7
  s_popbumper3:
    number: A2-B1-5


#P3 - Bank 0
  s_tooltarget1:
    number: A3-B0-5
    tags: playfield_active
  s_tooltarget2:
    number: A3-B0-6
    tags: playfield_active
  s_tooltarget3:
    number: A3-B0-7
    tags: playfield_active
  s_upperdrop:
    number: A3-B0-1
  s_topbumperleft:
    number: A3-B0-3
    tags: playfield_active
  s_whitedot1:
    number: A3-B0-4
    tags: playfield_active
  s_whitedot2:
    number: A3-B0-2
    tags: playfield_active
  s_loopleft:
    number: A3-B0-0
    type: NC
    tags: playfield_active

#P3 - Bank 1
  s_loopright:
    number: A3-B1-3
    type: NC
    tags: playfield_active
  s_topbumperright:  
    number: A3-B1-5
    tags: playfield_active
  s_whitedot3:
    number: A3-B1-1
    tags: playfield_active
  s_whitedot4:
    number: A3-B1-7
    tags: playfield_active
  s_spinner:
    number: A3-B1-2
    tags: playfield_active
  s_topkicker:
    number: A3-B1-4
  s_captiveball:
    number: A3-B1-6
    tags: playfield_active



 

#=======================================================================
#=======================================================================
#=======================================================================
#=======================================================================
#=======================================================================

# KEYBOARD CONFIG
#--------------------------------------------

# keyboard:
#   s:
#     switch: s_start
#   p:
#     switch: s_spinner
#   1:
#     switch: s_trough1
#     toggle: True
#   2:
#     switch: s_trough2
#     toggle: True
#   3:
#     switch: s_trough3
#     toggle: True
#   4:
#     switch: s_trough4
#     toggle: True

# COIL CONFIGURATION
#--------------------------------------------
coils:
  # Blue Coil Loom

  #A0-B0-0: Currently Empty
  #A0-B0-1: Currently Empty

  c_flipper_right_main:
    number: A0-B0-3
    default_pulse_ms: 40
  c_flipper_right_hold:
    number: A0-B0-2
    allow_enable: true 
  c_flipper_upper_main:
    number: A0-B0-4
    default_pulse_ms: 40
  c_flipper_upper_hold:
    number: A0-B0-5
    allow_enable: true 
  c_flipper_gate_main:
    number: A0-B0-6
    default_pulse_ms: 10
  c_flipper_gate_hold:
    number: A0-B0-7
    allow_enable: true

  #Orange Coil Loom
    #gates
  c_rightinlanegate:
    number: A0-B1-2
    allow_enable: true
  c_upperleftgate:
    number: A0-B1-1
    allow_enable: true
  c_upperrightgate:
    number: A0-B1-0
    allow_enable: true
  c_flipper_left_main:
    number: A0-B1-3
    default_pulse_ms: 40
  c_flipper_left_hold:
    number: A0-B1-4
    allow_enable: true 
  c_leftinlanegate:
    number: A0-B1-5
    allow_enable: true
  # A0-B1-6: Currently Empty
  # A0-B1-7: Currently Empty

  # Green Coil Loom   
  c_trough_eject:
    number: A1-B1-7
    default_pulse_ms: 25
  c_popbumper1:
    number: A1-B1-0
    default_pulse_ms: 20 
  c_popbumber2:
    number: A1-B1-1
    default_pulse_ms: 20
  c_popbumber3:
    number: A1-B1-2
    default_pulse_ms: 20
  c_upperdrop_drop:
    number: A1-B1-5
    default_pulse_ms: 10
  c_upperdrop_reset:
    number: A1-B1-3
    default_pulse_ms: 20
  c_slingshot:
    number: A1-B1-6
    default_pulse_ms: 30
  c_topkicker:
    number: A1-B1-4
    default_pulse_ms: 35

  #Brown Coil Loom
  c_scoop_eject:
    number: A1-B0-0
    default_pulse_ms: 13
  c_drop_target_reset:
    number: A1-B0-1
    default_pulse_ms: 45
  c_drop_target1_drop:
    number: A1-B0-2
    default_pulse_ms: 30
  c_drop_target2_drop:
    number: A1-B0-3
    default_pulse_ms: 30
  c_drop_target3_drop:
    number: A1-B0-4
    default_pulse_ms: 30
  c_drop_target4_drop:
    number: A1-B0-5
    default_pulse_ms: 30
  c_drop_target5_drop:
    number: A1-B0-6
    default_pulse_ms: 30
  c_drop_target6_drop:
    number: A1-B0-7
    default_pulse_ms: 30

 

# FLIPPER CONFIGURATION
#--------------------------------------------
flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
  upper_flipper:
    main_coil: c_flipper_upper_main
    hold_coil: c_flipper_upper_hold
    activation_switch: s_left_flipper

# AUTOFIRE COILS CONFIGURATION
#--------------------------------------------
autofire_coils:
  right_slingshot:
    coil: c_slingshot
    switch: s_rightsling
  popbumper1:
    coil: c_popbumper1
    switch: s_popbumper1
  popbumper2:
    coil: c_popbumber2
    switch: s_popbumper2
  popbumper3:
    coil: c_popbumber3
    switch: s_popbumper3

# BALL DEVICES CONFIGURATION
#--------------------------------------------
ball_devices:
  bd_trough:
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_troughjam
    eject_coil: c_trough_eject
    tags: trough, home, drain
    jam_switch: s_troughjam
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_plunger
  bd_plunger:
    ball_switches: s_plungerlane
    mechanical_eject: true
    eject_timeouts: 3s
  bd_scoop:
    ball_switches: s_scoup
    eject_coil: c_scoop_eject
    eject_timeouts: 1s
  bd_topkicker:
    ball_switches: s_topkicker
    eject_coil: c_topkicker
    eject_timeouts: 1s

diverters:
  right_divertergate_fire:
    activation_coil: c_flipper_gate_main
    type: pulse
    activation_time: 1s
    activation_switches: s_loopleft
    enable_events: diverter_travel_enabled
    disable_events: diverter_travel_disabled
  right_divertergate_hold:
    activation_coil: c_flipper_gate_hold
    type: hold
    activation_time: 2s
    activation_switches: s_loopleft
    enable_events: diverter_travel_enabled
    disable_events: diverter_travel_disabled

      
# DROP TARGET CONFIGURATION
#--------------------------------------------
drop_targets:
  dt_drop1:
    switch: s_drop1
    reset_coil: c_drop_target_reset
    knockdown_coil: c_drop_target1_drop
    knockdown_events: drop_drop1
  dt_drop2:
    switch: s_drop2
    reset_coil: c_drop_target_reset
    knockdown_coil: c_drop_target2_drop
    knockdown_events: drop_drop2
  dt_drop3:
    switch: s_drop3
    reset_coil: c_drop_target_reset
    knockdown_coil: c_drop_target3_drop
    knockdown_events: drop_drop3
  dt_drop4:
    switch: s_drop4
    reset_coil: c_drop_target_reset
    knockdown_coil: c_drop_target4_drop
    knockdown_events: drop_drop4
  dt_drop5:
    switch: s_drop5
    reset_coil: c_drop_target_reset
    knockdown_coil: c_drop_target5_drop
    knockdown_events: drop_drop5
  dt_drop6:
    switch: s_drop6
    reset_coil: c_drop_target_reset
    knockdown_coil: c_drop_target6_drop
    knockdown_events: drop_drop6
  
  dt_upperdrop:
    switch: s_upperdrop
    reset_coil: c_upperdrop_reset
    knockdown_coil: c_upperdrop_drop
    knockdown_events: diverter_dropupperdrop
    reset_events: diverter_resetupperdrop


# SOUND CONFIGURATION
#--------------------------------------------
sound_system:
    buffer: 2048
    channels: 2
    enabled: True
    frequency: 44100
    master_volume: 1
    tracks:
       music:
          type: standard
          simultaneous_sounds: 1
          volume: .75
       voice:
          type: standard
          simultaneous_sounds: 1
          volume: 1
       sfx:
          type: standard
          simultaneous_sounds: 8
          volume: .8

assets:
    sounds:
        default:
            load: on_demand
        music:
            track: music
        sfx:
            track: sfx
        voice:
            track: voice

sounds:
  ################   VOICES ####################
  #-- Skill Shots
  skillshot_awarded:
    file: SkillShotAwarded.wav
    volume: 1
    track: voice

  #-- Villager Multiball
  villager_multiball:
    file: VillagerMultiball.wav
    volume: 0.85
    track: voice
  villager_multiball_ready:
    file: VillagerMultiballReady.wav
    volume: 0.85
    track: voice
  villager_jackpot:
    file: VillagerJackpot.wav
    volume: 1
    track: voice

  #-- Worlds
  world_jackpot:
    file: WorldJackpot.wav
    volume: 1
    track: voice
  travel_ready:
    file: TravelReady.wav
    volume: 1
    track: voice

  #-- Extra Ball
  extraball_lit:
    file: ExtraBallLit.wav
    volume: 1
    track: voice
  extraball_awarded:
    file: ExtraBallAwarded.wav
    volume: 1
    track: voice

  #-- Night Mode
  night_mode_started:
    file: NightModeStarted.wav
    volume: 1
    track: voice
  night_zombie_jackpot:
    file: NightZombieJackpot.wav
    volume: 1
    track: voice
  night_creeper_jackpot:
    file: NightCreeperJackpot.wav
    volume: 1
    track: voice
  night_all_jackpot:
    file: NightAllJackpot.wav
    volume: 1
    track: voice
  night_super_jackpot:
    file: NightSuperJackpot.wav
    volume: 1
    track: voice
  night_mega_jackpot:
    file: NightMegaJackpot.wav
    volume: 1
    track: voice
  
  #-- Tools
  craft_ready:
    file: CraftReady.wav
    volume: 1
    track: voice

  ##############  SOUND EFFECTS ############
  bounce_kick:
    file: bounce_kick.wav
    volume: 0.85
    track: sfx
  clock_tick:
    file: clock_tick.wav
    volume: 1
    track: sfx
  collect_tool:
    file: collect_tool.wav
    volume: 1
    track: sfx
  lane_swish:
    file: lane_swish.wav
    volume: 1
    track: sfx
  villager_accept:
    file: village_accept.wav
    volume: 1
    track: sfx
  villager_deny:
    file: village_deny.wav
    volume: 1
    track: sfx
  villager_idle:
    file: village_idle.wav
    volume: 1
    track: sfx
  villager_trade:
    file: village_trade.wav
    volume: 1
    track: sfx
  meatextraball_cow:
    file: meatextraball_cow.wav
    volume: 1
    track: sfx
  meatextraball_pig:
    file: meatextraball_pig.wav
    volume: 1
    track: sfx
  meatextraball_chicken:
    file: meatextraball_chicken.wav
    volume: 1
    track: sfx
  zombie_death:
    file: zombie_death.wav
    volume: 1
    track: sfx
  creeper_death:
    file: creeper_death.wav
    volume: 1
    track: sfx

  #MUSIC TRACKS
  basemode_music:
    file: basemode.wav
    volume: 0.50
    loops: -1
    track: music
  world1mode_music:
    file: world1mode.wav
    volume: 0.50
    loops: -1
    track: music
  world2mode_music:
    file: world2mode.wav
    volume: 0.50
    loops: -1
    track: music
  world3mode_music:
    file: world3mode.wav
    volume: 0.50
    loops: -1
    track: music
  world4mode_music:
    file: world4mode.wav
    volume: 0.50
    loops: -1
    track: music
  world5mode_music:
    file: world5mode.wav
    volume: 0.50
    loops: -1
    track: music

  nightmode_music:
    file: nightmode_kit.wav
    volume: 0.50
    loops: -1
    track: music
  nighthurryup_music:
    file: nighthurryup.wav
    volume: 1
    loops: -1
    track: music
  villagermb_music:
    file: villagermb.wav
    volume: 0.80
    loops: -1
    track: music

  endmode_prepare_music:
    file: endmode_prepare.wav
    volume: 1
    loops: -1
    track: music

  endmode_battle_music:
    file: endmode_battle.wav
    volume: 1
    loops: -1
    track: music

  endmode_victory1_music:
    file: endmode_victory1.wav
    volume: 1
    loops: -1
    track: music

  endmode_victory2_music:
    file: endmode_victory2.wav
    volume: 1
    loops: -1
    track: music

# SOUND POOLS
#--------------------------------------------
sound_pools:
  villagersp:
    type: random_force_all
    track: sfx
    sounds:
      - villager_accept
      - villager_deny
      - villager_idle
      - villager_trade
  meatextraballsp:
    type: random_force_all
    track: sfx
    sounds:
      - meatextraball_cow
      - meatextraball_pig
      - meatextraball_chicken

# PLAYER VARIABLES
#--------------------------------------------
player_vars:
  gate_open:
    initial_value: 0
    value_type: int

  diverter_state:
    initial_value: "start"
    value_type: str

  #Multiball Multiplier
  multiplier_mb:
    initial_value: 1
    value_type: int

  villagermb_ready:
    initial_value: 0
    value_type: int

  villager_jackpot:
    initial_value: 1
    value_type: int

  world_jackpot:
    initial_value: 0
    value_type: int

  world_jackpot_base:
    initial_value: 0
    value_type: int

  world_jackpot_worlds:
    initial_value: 0
    value_type: int
  
  world_jackpot_items:
    initial_value: 0
    value_type: int

  #World Variables
  world_color:  #sets color of world for accent colors
    initial_value: "white"
    value_type: str

  world_name:
    initial_value: "none"
    value_type: str

  world_id:
    initial_value: 0
    value_type: int

  world1_setup:
    initial_value: 0
    value_type: int

  world2_setup:
    initial_value: 0
    value_type: int

  world3_setup:
    initial_value: 0
    value_type: int

  world4_setup:
    initial_value: 0
    value_type: int

  world5_setup:
    initial_value: 0
    value_type: int

  #Item 1 Variables
  world_item1_name:
    initial_value: "none"
    value_type: str

  world_item1_color:
    initial_value: "white"
    value_type: str

  world_item1_remaining:
    initial_value: 0
    value_type: int

  #Item 2 Variables
  world_item2_name:
    initial_value: "none"
    value_type: str

  world_item2_color:
    initial_value: "white"
    value_type: str

  world_item2_remaining:
    initial_value: 0
    value_type: int

  #Item 3 Variables
  world_item3_name:
    initial_value: "none"
    value_type: str

  world_item3_color:
    initial_value: "white"
    value_type: str

  world_item3_remaining:
    initial_value: 0
    value_type: int

  #Item 4 Variables
  world_item4_name:
    initial_value: "none"
    value_type: str

  world_item4_color:
    initial_value: "white"
    value_type: str

  world_item4_remaining:
    initial_value: 0
    value_type: int

  #Bonus
  bonus_items:
    initial_value: 0
    value_type: int
  bonus_multiplier:
    initial_value: 1
    value_type: int

  #Tools
  shovel:
    initial_value: 1
    value_type: int
  pickaxe:
    initial_value: 1
    value_type: int
  axe:
    initial_value: 1
    value_type: int
  sword:
    initial_value: 1
    value_type: int 

  #Tool Helpers
  tools_ready:
    initial_value: 0
    value_type: int

  tools_collected:
    initial_value: 0
    value_type: int

  tools_available:
    initial_value: 4
    value_type: int

  crafting_enabled:
    initial_value: 0
    value_type: int

  crafting_ready:
    initial_value: 0
    value_type: int

  crafting_full:
    initial_value: 0
    value_type: int

  travel_enabled:
    initial_value: 0
    value_type: int

# SLIDES CONFIGURATION
#--------------------------------------------
slides:
  welcome_slide:
    widgets:
      - type: text
        font_name: lazer84
        font_size: 70
        text: "Pincraft"
          
slide_player:
  init_done: welcome_slide
 
# MODES CONFIGURATION
#--------------------------------------------
modes:
  - base
  - lightoverlay
  - outlanegate
  - world1
  - world2
  - world3
  - world4
  - world5
  - theend
  - worldcontroller
  - bonus
  - bonusdisplay
  - villagermb
  - night
  - divertercontrol
  - tools
  - extraball
  - skillshot
  