#config_version=5
# PINCRAFT
# V.03 ALPHA
# WRITTEN BY: BRIAN SMITH, CONNOR SMITH
# KNOWN GOOD VERSION: MPF v0.52.7

# HARDWARE CONFIGURATION
#--------------------------------------------
hardware:
  platform: p3_roc
  driverboards: pdb
  lights: fadecandy

playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger        #this was changed from bd_plunger / reverted back

machine:
  balls_installed: 3
  min_balls: 3

game:
  balls_per_game: 3
  max_players: 4

# p_roc:
#   pd_led_boards:
#     4:       
#       use_ws281x_0: True
#       ws281x_0_first_address: 100
#       ws281x_0_last_address: 350
#     5:
#       use_ws281x_0: True


# DISPLAY CONFIGURATION
#--------------------------------------------
displays:
  lcd:
    width: 1366
    height: 768

window:
  width: 1366
  height: 768
  title: Pincraft
  resizable: false
  fullscreen: false
 # borderless: true
  exit_on_escape: true
  #source_display: lcd









 

#=======================================================================
#=======================================================================
#=======================================================================
#=======================================================================
#=======================================================================

# KEYBOARD CONFIG
#--------------------------------------------

# keyboard:
#   s:
#     switch: s_start
#   p:
#     switch: s_spinner
#   1:
#     switch: s_trough1
#     toggle: True
#   2:
#     switch: s_trough2
#     toggle: True
#   3:
#     switch: s_trough3
#     toggle: True
#   4:
#     switch: s_trough4
#     toggle: True



 

# FLIPPER CONFIGURATION
#--------------------------------------------
flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
  upper_flipper:
    main_coil: c_flipper_upper_main
    hold_coil: c_flipper_upper_hold
    activation_switch: s_left_flipper



# BALL DEVICES CONFIGURATION
#--------------------------------------------
ball_devices:
  bd_trough:
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_troughjam
    eject_coil: c_trough_eject
    tags: trough, home, drain
    jam_switch: s_troughjam
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_plunger
  bd_plunger:
    ball_switches: s_plungerlane
    mechanical_eject: true
    eject_timeouts: 2s
  bd_scoop:
    ball_switches: s_scoup
    eject_coil: c_scoop_eject
    eject_timeouts: 1s
  bd_topkicker:
    ball_switches: s_topkicker
    eject_coil: c_topkicker
    eject_timeouts: 1s
    eject_events: eject_topkicker

diverters:
  right_divertergate_fire:
    activation_coil: c_flipper_gate_main
    type: pulse
    activation_time: 1s
    activate_events: sshot_loopleft_hit
    deactivation_switches: s_portal
    enable_events: diverter_travel_enabled
    disable_events: diverter_travel_disabled, mode_nether_started
    reset_events: diverter_travel_disabled
  right_divertergate_hold:
    activation_coil: c_flipper_gate_hold
    type: hold
    activation_time: 2s
    activate_events: sshot_loopleft_hit
    deactivation_switches: s_portal
    enable_events: diverter_travel_enabled
    disable_events: diverter_travel_disabled, mode_nether_started
    reset_events: diverter_travel_disabled

      
# DROP TARGET CONFIGURATION
#--------------------------------------------
drop_targets:
  dt_drop1:
    switch: s_drop1
    reset_coil: c_drop_target_reset
    knockdown_coil: c_drop_target1_drop
    knockdown_events: drop_drop1
  dt_drop2:
    switch: s_drop2
    reset_coil: c_drop_target_reset
    knockdown_coil: c_drop_target2_drop
    knockdown_events: drop_drop2
  dt_drop3:
    switch: s_drop3
    reset_coil: c_drop_target_reset
    knockdown_coil: c_drop_target3_drop
    knockdown_events: drop_drop3
  dt_drop4:
    switch: s_drop4
    reset_coil: c_drop_target_reset
    knockdown_coil: c_drop_target4_drop
    knockdown_events: drop_drop4
  dt_drop5:
    switch: s_drop5
    reset_coil: c_drop_target_reset
    knockdown_coil: c_drop_target5_drop
    knockdown_events: drop_drop5
  dt_drop6:
    switch: s_drop6
    reset_coil: c_drop_target_reset
    knockdown_coil: c_drop_target6_drop
    knockdown_events: drop_drop6
  
  dt_upperdrop:
    switch: s_upperdrop
    reset_coil: c_upperdrop_reset
    knockdown_coil: c_upperdrop_drop
    knockdown_events: diverter_dropupperdrop
    reset_events: diverter_resetupperdrop


# SOUND CONFIGURATION
#--------------------------------------------
sound_system:
    buffer: 2048
    channels: 2
    enabled: True
    frequency: 44100
    master_volume: 1
    tracks:
       music:
          type: standard
          simultaneous_sounds: 1
          volume: .75
       voice:
          type: standard
          simultaneous_sounds: 1
          volume: 1
       sfx:
          type: standard
          simultaneous_sounds: 8
          volume: .8

assets:
    sounds:
        default:
            load: on_demand
        music:
            track: music
        sfx:
            track: sfx
        voice:
            track: voice

sounds:
  ################   VOICES ####################
  #-- Skill Shots
  skillshot_awarded:
    file: SkillShotAwarded.wav
    volume: 1
    track: voice

  #-- Villager Multiball
  villager_multiball:
    file: VillagerMultiball.wav
    volume: 0.85
    track: voice
  villager_multiball_ready:
    file: VillagerMultiballReady.wav
    volume: 0.85
    track: voice
  villager_jackpot:
    file: VillagerJackpot.wav
    volume: 1
    track: voice

  #-- Worlds
  world_jackpot:
    file: WorldJackpot.wav
    volume: 1
    track: voice
  #-- Travel Ready
  voice_travel_ready:
    file: TravelReady.wav
    volume: 1
    track: voice
  voice_portal_travel:
    file: PortalTravel.wav
    volume: 1
    track: voice

  voice_portal_stronghold:
    file: PortalStronghold.wav
    volume: 1
    track: voice

  #-- Extra Ball
  extraball_lit:
    file: ExtraBallLit.wav
    volume: 1
    track: voice
  extraball_awarded:
    file: ExtraBallAwarded.wav
    volume: 1
    track: voice

  #-- Nether Mode
  voice_nether_arrival:
    file: nether_arrival.wav
    volume: 1
    track: voice
  voice_nether_ghastjackpot:
    file: nether_ghastjackpot.wav
    volume: 1
    track: voice
  voice_nether_jackpot:
    file: nether_jackpot.wav
    volume: 1
    track: voice
  voice_nether_skeletonjackpot:
    file: nether_skeletonjackpot.wav
    volume: 1
    track: voice
  voice_nether_skeletons:
    file: nether_skeletons.wav
    volume: 1
    track: voice
  voice_nether_superjackpot:
    file: nether_superjackpot.wav
    volume: 1
    track: voice
  voice_nether_supermegajackpot:
    file: nether_supermegajackpot.wav
    volume: 1
    track: voice
    
  #-- Night Mode
  night_mode_ready:
    file: NightModeReady.wav
    volume: 1
    track: voice

  night_mode_started:
    file: NightModeStarted.wav
    volume: 1
    track: voice
  night_zombie_jackpot:
    file: NightZombieJackpot.wav
    volume: 1
    track: voice
  night_creeper_jackpot:
    file: NightCreeperJackpot.wav
    volume: 1
    track: voice
  night_all_jackpot:
    file: NightAllJackpot.wav
    volume: 1
    track: voice
  night_super_jackpot:
    file: NightSuperJackpot.wav
    volume: 1
    track: voice
  night_mega_jackpot:
    file: NightMegaJackpot.wav
    volume: 1
    track: voice

  #-- Stronghold

  voice_stronghold_travel:
    file: StrongholdStarted.wav
    volume: 1
    track: voice

  stronghold_collect:
    file: StrongholdCollect.wav
    volume: 1
    track: voice

  stronghold_travel_single:
    file: StrongholdTravelSingle.wav
    volume: 1
    track: voice

  stronghold_travel_multiball:
    file: StrongholdTravelMultiball.wav
    volume: 1
    track: voice

  stronghold_jackpot:
    file: StrongholdJackpot.wav
    volume: 1
    track: voice
  
  #-- Tools
  craft_ready:
    file: CraftReady.wav
    volume: 1
    track: voice

  ##############  SOUND EFFECTS ############
  bounce_kick:
    file: bounce_kick.wav
    volume: 0.85
    track: sfx
  clock_tick:
    file: clock_tick.wav
    volume: 1
    track: sfx
  collect_tool:
    file: collect_tool.wav
    volume: 1
    track: sfx
  lane_swish:
    file: lane_swish.wav
    volume: 1
    track: sfx
  villager_accept:
    file: village_accept.wav
    volume: 1
    track: sfx
  villager_deny:
    file: village_deny.wav
    volume: 1
    track: sfx
  villager_idle:
    file: village_idle.wav
    volume: 1
    track: sfx
  villager_trade:
    file: village_trade.wav
    volume: 1
    track: sfx

  #SFX: Extra Ball
  meatextraball_cow:
    file: meatextraball_cow.wav
    volume: 1
    track: sfx
  meatextraball_pig:
    file: meatextraball_pig.wav
    volume: 1
    track: sfx
  meatextraball_chicken:
    file: meatextraball_chicken.wav
    volume: 1
    track: sfx
  zombie_death:
    file: zombie_death.wav
    volume: 1
    track: sfx
  creeper_death:
    file: creeper_death.wav
    volume: 1
    track: sfx

  #SFX: Nether
  ghast_death:
    file: ghast_death.ogg
    volume: 1
    track: sfx
  
  skeleton_death:
    file: skeleton_death.ogg
    volume: 1
    track: sfx

  #SFX: STRONGHOLD
  eyeplace1:
    file: eyeplace1.ogg
    volume: 1
    track: sfx
  eyeplace2:
    file: eyeplace2.ogg
    volume: 1
    track: sfx
  eyeplace3:
    file: eyeplace3.ogg
    volume: 1
    track: sfx
  endportal:
    file: endportal.ogg
    volume: 1
    track: sfx

  #SFX: THE END
  enderdragon_wings1:
    file: enderdragon_wings1.ogg
    volume: 1
    track: sfx
  enderdragon_wings2:
    file: enderdragon_wings2.ogg
    volume: 1
    track: sfx
  enderdragon_wings3:
    file: enderdragon_wings3.ogg
    volume: 1
    track: sfx
  enderdragon_wings4:
    file: enderdragon_wings4.ogg
    volume: 1
    track: sfx
  enderdragon_wings5:
    file: enderdragon_wings5.ogg
    volume: 1
    track: sfx
  enderdragon_wings6:
    file: enderdragon_wings6.ogg
    volume: 1
    track: sfx

  enderdragon_growl1:
    file: enderdragon_growl1.ogg
    volume: 1
    track: sfx
  enderdragon_growl2:
    file: enderdragon_growl2.ogg
    volume: 1
    track: sfx
  enderdragon_growl3:
    file: enderdragon_growl3.ogg
    volume: 1
    track: sfx
  enderdragon_growl4:
    file: enderdragon_growl4.ogg
    volume: 1
    track: sfx

  enderdragon_hit1:
    file: enderdragon_hit1.ogg
    volume: 1
    track: sfx
  enderdragon_hit2:
    file: enderdragon_hit2.ogg
    volume: 1
    track: sfx
  enderdragon_hit3:
    file: enderdragon_hit3.ogg
    volume: 1
    track: sfx
  enderdragon_hit4:
    file: enderdragon_hit4.ogg
    volume: 1
    track: sfx

  enderdragon_end:
    file: enderdragon_end.ogg
    volume: 1
    track: sfx
  
  #SFX: Blocks
  block_dig1:
    file: dig1.ogg
    volume: 1
    track: sfx
  block_dig2:
    file: dig2.ogg
    volume: 1
    track: sfx
  block_dig3:
    file: dig3.ogg
    volume: 1
    track: sfx
  block_dig4:
    file: dig4.ogg
    volume: 1
    track: sfx

  block_axe1:
    file: axe1.ogg
    volume: 1
    track: sfx
  block_axe2:
    file: axe2.ogg
    volume: 1
    track: sfx
  block_axe3:
    file: axe3.ogg
    volume: 1
    track: sfx
  block_axe4:
    file: axe4.ogg
    volume: 1
    track: sfx


  #MUSIC TRACKS
  basemode_music:
    file: basemode.wav
    volume: 0.60
    loops: -1
    track: music
  world1mode_music:
    file: world1mode.wav
    volume: 0.60
    loops: -1
    track: music
  world2mode_music:
    file: world2mode.wav
    volume: 0.60
    loops: -1
    track: music
  world3mode_music:
    file: world3mode.wav
    volume: 0.60
    loops: -1
    track: music
  world4mode_music:
    file: world4mode.wav
    volume: 0.60
    loops: -1
    track: music
  world5mode_music:
    file: world5mode.wav
    volume: 0.60
    loops: -1
    track: music

  portal_music:
    file: portal_travel.wav
    volume: .80
    loops: -1
    track: music

  nether_music:
    file: nether_music.wav
    volume: 0.80
    loops: -1
    track: music

  nightmode_music:
    file: nightmode_kit.wav
    volume: 0.80
    loops: -1
    track: music
  nighthurryup_music:
    file: nighthurryup.wav
    volume: 1
    loops: -1
    track: music
  villagermb_music:
    file: villagermb.wav
    volume: 0.80
    loops: -1
    track: music
  nightvillager_music:
    file: nightvillager_music.wav
    volume: 0.80
    loops: -1
    track: music

  stronghold_music:
    file: stronghold_music.wav
    volume: 1
    loops: -1
    track: music

  strongholdjackpot_music:
    file: strongholdjackpot_music.wav
    volume: 1
    loops: -1
    track: music

  endmode_prepare_music:
    file: endmode_prepare.wav
    volume: 1
    loops: -1
    track: music

  endmode_battle_music:
    file: endmode_battle.wav
    volume: 1
    loops: -1
    track: music

  endmode_victory1_music:
    file: endmode_victory1.wav
    volume: 1
    loops: -1
    track: music

  endmode_victory2_music:
    file: endmode_victory2.wav
    volume: 1
    loops: -1
    track: music
    
  heatbeat_music:
    file: heartbeat_music.wav
    volume: 1
    loops: -1
    track: music



# SOUND POOLS
#--------------------------------------------
sound_pools:
  villagersp:
    type: random_force_all
    track: sfx
    sounds:
      - villager_accept
      - villager_deny
      - villager_idle
      - villager_trade
  meatextraballsp:
    type: random_force_all
    track: sfx
    sounds:
      - meatextraball_cow
      - meatextraball_pig
      - meatextraball_chicken
  eyeplacesp:
    type: random_force_all
    track: sfx
    sounds:
      - eyeplace1
      - eyeplace2
      - eyeplace3
  enderdragon_wings:
    type: random_force_all
    track: sfx
    sounds:
      - enderdragon_wings1
      - enderdragon_wings2
      - enderdragon_wings3
      - enderdragon_wings4
      - enderdragon_wings5
      - enderdragon_wings6
  enderdragon_growl:
    type: random_force_all
    track: sfx
    sounds:
      - enderdragon_growl1
      - enderdragon_growl2
      - enderdragon_growl3
      - enderdragon_growl4
  enderdragon_hit:
    type: random_force_all
    track: sfx
    sounds:
      - enderdragon_hit1
      - enderdragon_hit2
      - enderdragon_hit3
      - enderdragon_hit4
  block_dig:
    type: random_force_all
    track: sfx
    sounds:
      - block_dig1
      - block_dig2
      - block_dig3
      - block_dig4
  block_axe:
    type: random_force_all
    track: sfx
    sounds:
      - block_axe1
      - block_axe2
      - block_axe3
      - block_axe4



# MACHINE VARIABLES
machine_vars:
  game_mode:
    initial_value: "NORMAL"   # EASY / NORMAL / HARDCORE / COMPETITION / COOP / STORY
    value_type: str 

  game_mode_display:
    initial_value: "Normal Mode"
    value_type: str

  game_num_players:
    initial_value: 1
    value_type: int

  difficulty_villager:
    initial_value: 20
    value_type: int
  
  difficulty_night:
    initial_value: 100
    value_type: int

  difficulty_tools:
    initial_value: 1
    value_type: int

  difficulty_extraball1:
    initial_value: 6
    value_type: int

  difficulty_extraball2:
    initial_value: 12
    value_type: int
    


#SLIDES CONFIGURATION
#--------------------------------------------
slides:
  welcome_slide:
    widgets:
      - type: image
        image: Pincraft_Logo_Icon
          
slide_player:
  init_done: welcome_slide

#LOOP SEQUENCE SHOTS
sequence_shots:
  sshot_loopleft:
    switch_sequence: s_loopleft, s_loopright
    sequence_timeout: 2s
  sshot_loopright:
    switch_sequence: s_loopright, s_loopleft
    sequence_timeout: 2s
  sshot_travel:
    switch_sequence: s_loopleft, s_loopright, s_portal
    sequence_timeout: 5s
 
# MODES CONFIGURATION
#--------------------------------------------
modes:
  - gamecontroller
  - gameselect
  - base
  - lightoverlay
  - outlanegate
  - divertercontrol
  - extraball
  - skillshot
  - tools
  - tooldisplay
  - bonus
  - bonusdisplay
  - worldcontroller
  - worldjackpot
  - world1
  - world2
  - world3
  - world4
  - world5
  - theend
  - nethercontroller
  - nether
  - netherready
  - strongholdcontroller
  - stronghold
  - strongholdready
  - strongholdjackpot
  - nightready
  - nightcontroller
  - night
  - villagercontroller
  - villagerready
  - villagermb
  - nightvillagercontroller
  - nightvillagerready
  - travelready

config:
    - lights.yaml
    - coils.yaml
    - switches.yaml
    - variables.yaml