#config_version=5
mode:
    start_events: multiball_nightvillagermb_started
    stop_events: multiball_nightvillagermb_ended, ball_ending
    priority: 500

#play hurry up sound effect

sound_player:
  mode_nightvillagercontroller_started:
    nightvillager_music:
      action: play
      loops: -1
      mode_end_action: stop

show_player:
   mode_nightvillagercontroller_started:
    show_nightvillager:
      loops: -1
      speed:  10

event_player:
  mode_nightvillager_started:
    outlanegate_close
  