#config_version=5
mode:
    start_events: mode_worldcontroller_started
    stop_events: mode_worldcontroller_stopped
    priority: 500

shot_profiles:
  sp_extraball:
    states:
      - name: flashing  # step 2
        show: flash
      - name: lit  # step 3
        show: on
    loop: no
  collectebshot:
      states:
        - name: lit
          show: on

shots:
  collectitem_special:
    switch: s_collectitem3
    profile: collectebshot
    show_tokens:
      leds: l_collectitem3
    enable_events: enable_extraball
    disable_events: collectitem_special_disabled
  award_extraball:
    switch: s_captiveball
    enable_events: meatextraball_light
    disable_events: meatextraball_award
    show_tokens:
      leds: l_captiveextraball
    profile: sp_extraball

counters:
   counter_meatextraball:
      count_events: collectitem_special_hit
      starting_count: 0
      count_interval: 1
      count_complete_value: 12
      enable_events: enable_extraball
      disable_events: disable_extraball
      persist_state: true
      events_when_hit: extraball_progress
      reset_on_complete: false
      restart_events: meatextraball_award



variable_player:
  meatextraball_light:
    earned_ebcount: 
      int: 1
      action: add

event_player:
  award_extraball_hit:
    meatextraball_award

  award_extraball_hit{current_player.earned_ebcount==1}:
    enable_extraball
    show_extraball

  extraball_progress:
    show_extraball

  extraball_progress{current_player.earned_ebcount==0 and device.counters.counter_meatextraball.value==6}:
    - show_extraball
    - disable_extraball
    - collectitem_special_disabled
    - meatextraball_light

  extraball_progress{current_player.earned_ebcount==1 and device.counters.counter_meatextraball.value==12}:
    - show_extraball
    - disable_extraball
    - collectitem_special_disabled
    - meatextraball_light

  mode_extraball_started{current_player.earned_ebcount==0}:
    enable_extraball
    show_extraball
  mode_extraball_started{current_player.earned_ebcount==1}:
    enable_extraball
    show_extraball
  mode_extraball_started{current_player.earned_ebcount==2}:
    disable_extraball
    remove_extraball


  
sound_player:
  collectitem_special_hit:
    meatextraballsp: 
      action: play
      loops: 1
  meatextraball_award: extraball_awarded
  meatextraball_light: extraball_lit

light_player:
  extra_ball_meatextraball_awarded:
    l_shootagain: red

widgets:
  widget_meat1:
    - type: image        #MEAT 1
      image: meat_empty
      anchor_x: left
      anchor_y: bottom
      y: bottom+140
      x: left+860
      z: 50
  widget_meat2:
    - type: image        #MEAT 2
      image: meat_empty
      anchor_x: left
      anchor_y: bottom
      y: bottom+140
      x: left+890
      z: 50
  widget_meat3:
    - type: image        #MEAT 3
      image: meat_empty
      anchor_x: left
      anchor_y: bottom
      y: bottom+140
      x: left+920
      z: 50
  widget_meat4:
    - type: image        #MEAT 4
      image: meat_empty
      anchor_x: left
      anchor_y: bottom
      y: bottom+140
      x: left+950
      z: 50
  widget_meat5:
    - type: image        #MEAT 5
      image: meat_empty
      anchor_x: left
      anchor_y: bottom
      y: bottom+140
      x: left+980
      z: 50
  widget_meat6: 
    - type: image        #MEAT 6
      image: meat_empty
      anchor_x: left
      anchor_y: bottom
      y: bottom+140
      x: left+1010
      z: 50
  widget_meat7: 
    - type: image        #MEAT 7
      image: meat_empty
      anchor_x: left
      anchor_y: bottom
      y: bottom+140
      x: left+1040
      z: 50
  widget_meat8:
    - type: image        #MEAT 8
      image: meat_empty
      anchor_x: left
      anchor_y: bottom
      y: bottom+140
      x: left+1070
      z: 50
  widget_meat9:
    - type: image        #MEAT 9
      image: meat_empty
      anchor_x: left
      anchor_y: bottom
      y: bottom+140
      x: left+1100
      z: 50
  widget_meat10:
    - type: image        #MEAT 10
      image: meat_empty
      anchor_x: left
      anchor_y: bottom
      y: bottom+140
      x: left+1130
      z: 50
  widget_meat11:
    - type: image        #MEAT 11
      image: meat_empty
      anchor_x: left
      anchor_y: bottom
      y: bottom+140
      x: left+1160
      z: 50
  widget_meat12:
    - type: image        #MEAT 12
      image: meat_empty
      anchor_x: left
      anchor_y: bottom
      y: bottom+140
      x: left+1190
      z: 50

widget_player:
  remove_extraball:
    widget_meat1:
      action: remove
    widget_meat2:
      action: remove
    widget_meat3:
      action: remove
    widget_meat4:
      action: remove
    widget_meat5:
      action: remove
    widget_meat6:
      action: remove
    widget_meat7:
      action: remove
    widget_meat8:
      action: remove
    widget_meat9:
      action: remove
    widget_meat10:
      action: remove
    widget_meat11:
      action: remove
    widget_meat12:
      action: remove

  #COUNTER IS AT 1
  show_extraball{device.counters.counter_meatextraball.value>=1}:
    widget_meat1:
      action: update
      widget_settings:
        image: meat_full_bg
  show_extraball{device.counters.counter_meatextraball.value<1}:
    widget_meat1:
      action: update
      widget_settings:
        image: meat_empty

  #COUNTER IS AT 2
  show_extraball{device.counters.counter_meatextraball.value>=2}:
    widget_meat2:
      action: update
      widget_settings:
        image: meat_full_bg
  show_extraball{device.counters.counter_meatextraball.value<2}:
    widget_meat2:
      action: update
      widget_settings:
        image: meat_empty

  #COUNTER IS AT 3
  show_extraball{device.counters.counter_meatextraball.value>=3}:
    widget_meat3:
      action: update
      widget_settings:
        image: meat_full_bg
  show_extraball{device.counters.counter_meatextraball.value<3}:
    widget_meat3:
      action: update
      widget_settings:
        image: meat_empty

  #COUNTER IS AT 4
  show_extraball{device.counters.counter_meatextraball.value>=4}:
    widget_meat4:
      action: update
      widget_settings:
        image: meat_full_bg
  show_extraball{device.counters.counter_meatextraball.value<4}:
    widget_meat4:
      action: update
      widget_settings:
        image: meat_empty

  #COUNTER IS AT 5
  show_extraball{device.counters.counter_meatextraball.value>=5}:
    widget_meat5:
      action: update
      widget_settings:
        image: meat_full_bg
  show_extraball{device.counters.counter_meatextraball.value<5}:
    widget_meat5:
      action: update
      widget_settings:
        image: meat_empty

  #COUNTER IS AT 6
  show_extraball{device.counters.counter_meatextraball.value>=6}:
    widget_meat6:
      action: update
      widget_settings:
        image: meat_full_bg
  show_extraball{device.counters.counter_meatextraball.value<6}:
    widget_meat6:
      action: update
      widget_settings:
        image: meat_empty

  #COUNTER IS AT 7
  show_extraball{device.counters.counter_meatextraball.value>=7 and current_player.earned_ebcount==1}:
    widget_meat7:
      action: update
      widget_settings:
        image: meat_full_bg
  show_extraball{device.counters.counter_meatextraball.value<7 and current_player.earned_ebcount==1}:
    widget_meat7:
      action: update
      widget_settings:
        image: meat_empty

  #COUNTER IS AT 8
  show_extraball{device.counters.counter_meatextraball.value>=8 and current_player.earned_ebcount==1}:
    widget_meat8:
      action: update
      widget_settings:
        image: meat_full_bg
  show_extraball{device.counters.counter_meatextraball.value<8 and current_player.earned_ebcount==1}:
    widget_meat8:
      action: update
      widget_settings:
        image: meat_empty

  #COUNTER IS AT 9
  show_extraball{device.counters.counter_meatextraball.value>=9 and current_player.earned_ebcount==1}:
    widget_meat9:
      action: update
      widget_settings:
        image: meat_full_bg
  show_extraball{device.counters.counter_meatextraball.value<9 and current_player.earned_ebcount==1}:
    widget_meat9:
      action: update
      widget_settings:
        image: meat_empty

  #COUNTER IS AT 10
  show_extraball{device.counters.counter_meatextraball.value>=10 and current_player.earned_ebcount==1}:
    widget_meat10:
      action: update
      widget_settings:
        image: meat_full_bg
  show_extraball{device.counters.counter_meatextraball.value<10 and current_player.earned_ebcount==1}:
    widget_meat10:
      action: update
      widget_settings:
        image: meat_empty

  #COUNTER IS AT 11
  show_extraball{device.counters.counter_meatextraball.value>=11 and current_player.earned_ebcount==1}:
    widget_meat11:
      action: update
      widget_settings:
        image: meat_full_bg
  show_extraball{device.counters.counter_meatextraball.value<11 and current_player.earned_ebcount==1}:
    widget_meat11:
      action: update
      widget_settings:
        image: meat_empty

  #COUNTER IS AT 12
  show_extraball{device.counters.counter_meatextraball.value>=12 and current_player.earned_ebcount==1}:
    widget_meat12:
      action: update
      widget_settings:
        image: meat_full_bg
  show_extraball{device.counters.counter_meatextraball.value<12 and current_player.earned_ebcount==1}:
    widget_meat12:
      action: update
      widget_settings:
        image: meat_empty