#config_version=5
mode:
    start_events: ball_starting
    stop_events: ball_ended
    priority: 1000

shots:
  collectitem_special:
    switch: s_collectitem3
    show_tokens:
      leds: l_collectitem3
    enable_events: collectitem_special_enabled
    disable_events: collectitem_special_disabled
  award_extraball:
    switch: s_captiveball

counters:
   counter_meatextraball:
      count_events: collectitem_special_hit
      starting_count: 0
      count_interval: 1
      count_complete_value: 10
      enable_events: mode_base_started
      persist_state: true

event_player:
  logicblock_counter_meatextraball_complete:
    - collectitem_special_disabled
    - award_meatextraball

sound_player:
  collectitem_special_hit:
    meatextraballsp: 
      action: play
      loops: 1
  extra_ball_meatextraball_awarded: extraball_awarded    #extraball_lit

light_player:
  extra_ball_meatextraball_awarded:
    l_shootagain: red