#config_version=5
mode:
    start_events: ball_started, multiball_nightmb_ended
    stop_events: ball_ended, multiball_nightmb_started
    priority: 1000

shot_profiles:
  sp_extraball:
    states:
      - name: flashing  # step 2
        show: flash
      - name: lit  # step 3
        show: on
    loop: no
  collectebshot:
      states:
        - name: lit
          show: on

shots:
  collectitem_special:
    switch: s_collectitem3
    profile: collectebshot
    show_tokens:
      leds: l_collectitem3
    enable_events: collectitem_special_enabled
    disable_events: collectitem_special_disabled
  award_extraball:
    switch: s_captiveball
    enable_events: meatextraball_light
    disable_events: meatextraball_award
    show_tokens:
      leds: l_captiveextraball
    profile: sp_extraball

counters:
   counter_meatextraball:
      count_events: collectitem_special_hit
      starting_count: 0
      count_interval: 1
      count_complete_value: 10
      enable_events: mode_base_started
      persist_state: true

event_player:
  award_extraball_hit:
    meatextraball_award
  logicblock_counter_meatextraball_complete:
    - collectitem_special_disabled
    - meatextraball_light
  
sound_player:
  collectitem_special_hit:
    meatextraballsp: 
      action: play
      loops: 1
  meatextraball_award: extraball_awarded
  meatextraball_light: extraball_lit

light_player:
  extra_ball_meatextraball_awarded:
    l_shootagain: red