#config_version=5
mode:
    start_events: ball_starting
    stop_events: ball_ended
    priority: 1000
    
light_player:
  #BONUS ROUND 0 to 12
  item_collected{current_player.bonus_items>=1 and current_player.bonus_items<=11}:
    l_collect1: green
  item_collected{current_player.bonus_items>=2 and current_player.bonus_items<=11}:
    l_collect2: green
  item_collected{current_player.bonus_items>=3 and current_player.bonus_items<=11}:
    l_collect3: green
  item_collected{current_player.bonus_items>=4 and current_player.bonus_items<=11}:
    l_collect4: green
  item_collected{current_player.bonus_items>=5 and current_player.bonus_items<=11}:
    l_collect5: green
  item_collected{current_player.bonus_items>=6 and current_player.bonus_items<=11}:
    l_collect6: green
  item_collected{current_player.bonus_items>=7 and current_player.bonus_items<=11}:
    l_collect7: green
  item_collected{current_player.bonus_items>=8 and current_player.bonus_items<=11}:
    l_collect8: green
  item_collected{current_player.bonus_items>=9 and current_player.bonus_items<=11}:
    l_collect9: green
  item_collected{current_player.bonus_items>=10 and current_player.bonus_items<=11}:
    l_collect10: green
  item_collected{current_player.bonus_items>=11 and current_player.bonus_items<=11}:
    l_collect11: green
  item_collected{current_player.bonus_items==12}:
    l_collect1: off
    l_collect2: off
    l_collect3: off
    l_collect4: off
    l_collect5: off
    l_collect6: off
    l_collect7: off
    l_collect8: off
    l_collect9: off
    l_collect10: off
    l_collect11: off

  #BONUS ROUND 13 to 24
  item_collected{current_player.bonus_items>=13 and current_player.bonus_items<=23}:
    l_collect1: yellow
  item_collected{current_player.bonus_items>=14 and current_player.bonus_items<=23}:
    l_collect2: yellow
  item_collected{current_player.bonus_items>=15 and current_player.bonus_items<=23}:
    l_collect3: yellow
  item_collected{current_player.bonus_items>=16 and current_player.bonus_items<=23}:
    l_collect4: yellow
  item_collected{current_player.bonus_items>=17 and current_player.bonus_items<=23}:
    l_collect5: yellow
  item_collected{current_player.bonus_items>=18 and current_player.bonus_items<=23}:
    l_collect6: yellow
  item_collected{current_player.bonus_items>=19 and current_player.bonus_items<=23}:
    l_collect7: yellow
  item_collected{current_player.bonus_items>=20 and current_player.bonus_items<=23}:
    l_collect8: yellow
  item_collected{current_player.bonus_items>=21 and current_player.bonus_items<=23}:
    l_collect9: yellow
  item_collected{current_player.bonus_items>=22 and current_player.bonus_items<=23}:
    l_collect10: yellow
  item_collected{current_player.bonus_items>=23 and current_player.bonus_items<=23}:
    l_collect11: yellow
  item_collected{current_player.bonus_items==24}:
    l_collect1: off
    l_collect2: off
    l_collect3: off
    l_collect4: off
    l_collect5: off
    l_collect6: off
    l_collect7: off
    l_collect8: off
    l_collect9: off
    l_collect10: off
    l_collect11: off

 #BONUS ROUND 25 to 36
  item_collected{current_player.bonus_items>=25 and current_player.bonus_items<=35}:
    l_collect1: blue
  item_collected{current_player.bonus_items>=26 and current_player.bonus_items<=35}:
    l_collect2: blue
  item_collected{current_player.bonus_items>=27 and current_player.bonus_items<=35}:
    l_collect3: blue
  item_collected{current_player.bonus_items>=28 and current_player.bonus_items<=35}:
    l_collect4: blue
  item_collected{current_player.bonus_items>=29 and current_player.bonus_items<=35}:
    l_collect5: blue
  item_collected{current_player.bonus_items>=30 and current_player.bonus_items<=35}:
    l_collect6: blue
  item_collected{current_player.bonus_items>=31 and current_player.bonus_items<=35}:
    l_collect7: blue
  item_collected{current_player.bonus_items>=32 and current_player.bonus_items<=35}:
    l_collect8: blue
  item_collected{current_player.bonus_items>=33 and current_player.bonus_items<=35}:
    l_collect9: blue
  item_collected{current_player.bonus_items>=34 and current_player.bonus_items<=35}:
    l_collect10: blue
  item_collected{current_player.bonus_items>=35 and current_player.bonus_items<=35}:
    l_collect11: blue
  item_collected{current_player.bonus_items==36}:
    l_collect1: off
    l_collect2: off
    l_collect3: off
    l_collect4: off
    l_collect5: off
    l_collect6: off
    l_collect7: off
    l_collect8: off
    l_collect9: off
    l_collect10: off
    l_collect11: off

 #BONUS ROUND 37 to 48
  item_collected{current_player.bonus_items>=37 and current_player.bonus_items<=47}:
    l_collect1: red
  item_collected{current_player.bonus_items>=38 and current_player.bonus_items<=47}:
    l_collect2: red
  item_collected{current_player.bonus_items>=39 and current_player.bonus_items<=47}:
    l_collect3: red
  item_collected{current_player.bonus_items>=40 and current_player.bonus_items<=47}:
    l_collect4: red
  item_collected{current_player.bonus_items>=41 and current_player.bonus_items<=47}:
    l_collect5: red
  item_collected{current_player.bonus_items>=42 and current_player.bonus_items<=47}:
    l_collect6: red
  item_collected{current_player.bonus_items>=43 and current_player.bonus_items<=47}:
    l_collect7: red
  item_collected{current_player.bonus_items>=44 and current_player.bonus_items<=47}:
    l_collect8: red
  item_collected{current_player.bonus_items>=45 and current_player.bonus_items<=47}:
    l_collect9: red
  item_collected{current_player.bonus_items>=46 and current_player.bonus_items<=47}:
    l_collect10: red
  item_collected{current_player.bonus_items>=47 and current_player.bonus_items<=47}:
    l_collect11: red
  item_collected{current_player.bonus_items==48}:
    l_collect1: off
    l_collect2: off
    l_collect3: off
    l_collect4: off
    l_collect5: off
    l_collect6: off
    l_collect7: off
    l_collect8: off
    l_collect9: off
    l_collect10: off
    l_collect11: off

#BONUS ROUND 49 to 60
  item_collected{current_player.bonus_items>=49 and current_player.bonus_items<=60}:
    l_collect1: purple
  item_collected{current_player.bonus_items>=50 and current_player.bonus_items<=60}:
    l_collect2: purple
  item_collected{current_player.bonus_items>=51 and current_player.bonus_items<=60}:
    l_collect3: purple
  item_collected{current_player.bonus_items>=52 and current_player.bonus_items<=60}:
    l_collect4: purple
  item_collected{current_player.bonus_items>=53 and current_player.bonus_items<=60}:
    l_collect5: purple
  item_collected{current_player.bonus_items>=54 and current_player.bonus_items<=60}:
    l_collect6: purple
  item_collected{current_player.bonus_items>=55 and current_player.bonus_items<=60}:
    l_collect7: purple
  item_collected{current_player.bonus_items>=56 and current_player.bonus_items<=60}:
    l_collect8: purple
  item_collected{current_player.bonus_items>=57 and current_player.bonus_items<=60}:
    l_collect9: purple
  item_collected{current_player.bonus_items>=58 and current_player.bonus_items<=60}:
    l_collect10: purple
  item_collected{current_player.bonus_items>=59 and current_player.bonus_items<=60}:
    l_collect11: purple
  item_collected{current_player.bonus_items==60}:
    l_collect1: purple
    l_collect2: purple
    l_collect3: purple
    l_collect4: purple
    l_collect5: purple
    l_collect6: purple
    l_collect7: purple
    l_collect8: purple
    l_collect9: purple
    l_collect10: purple
    l_collect11: purple

  item_collected{current_player.bonus_items>=12}:
   l_collect12: green
  item_collected{current_player.bonus_items>=24}:
   l_collect13: yellow
  item_collected{current_player.bonus_items>=36}:
   l_collect14: blue
  item_collected{current_player.bonus_items>=48}:
   l_collect15: red
  item_collected{current_player.bonus_items>=60}:
   l_collect16: purple