#config_version=5
mode:
    start_events: theend_started
    stop_events: theend_completed
    priority: 500

#TODO: Return to Travel State if awarded but ball drains

show_player:
  mode_theend_started:  #Setup GI Light Show
    show_theendgi:
      loops: -1
      speed: 1

state_machines:
  statemachine_theend:
    persist_state: false
    states:
      start:
        label: Start state
      state_prepare:
        label: prepare state
        events_when_started: state_prepare_started
        events_when_stopped: state_prepare_stopped
      state_battle:
        label: battle state
        events_when_started: state_battle_started
        events_when_stopped: state_battle_stopped
      state_victory:
        label: victory state
        events_when_started: state_victory_started
        events_when_stopped: state_victory_stopped
      state_travel:
        label: travel state
        events_when_started: state_travel_started
    transitions:
      - source: start 
        target: state_prepare
        events: mode_theend_started, ball_started
      - source: state_prepare
        target: state_battle
        events: multiball_endmb_started
      - source: state_battle
        target: state_prepare
        events: multiball_endmb_ended, ball_started
      - source: state_battle
        target: state_victory
        events: theend_dragon_defeated
      - source: state_victory
        target: state_travel
        events: multiball_endmb_ended



shots:
  shot_victoryloopleft:
    hit_events: sshot_loopleft_hit
    enable_events: state_victory_started
    disable_events: state_victory_stopped
  shot_victoryloopright:
    hit_events: sshot_loopright_hit
    enable_events: state_victory_started
    disable_events: state_victory_stopped

  enderdragon_shot:
    switch: s_centertarget
  enderdragon_shot1:                      #DROP TARGETS
    switch: s_collectitem1
    profile: sp_enderdragon
    advance_events: advance_dragon_shots
    show_tokens:
        light: l_collectitem1
  enderdragon_shot2:
    switch: s_collectitem2
    profile: sp_enderdragon
    advance_events: advance_dragon_shots
    show_tokens:
        light: l_collectitem2
  enderdragon_shot3:
    switch: s_collectitem3
    profile: sp_enderdragon
    show_tokens:
        light: l_collectitem3
  enderdragon_shot4:
    switch: s_collectitem4
    profile: sp_enderdragon
    show_tokens:
        light: l_collectitem4
  enderdragon_shot5:
    switch: s_collectitem5
    profile: sp_enderdragon
    show_tokens:
        light: l_collectitem5
  enderdragon_shot6:                   #TOOLS
    switch: s_tooltarget3
    profile: sp_enderdragon
    show_tokens:
        light: l_toolcollect3
  enderdragon_shot7:
    switch: s_tooltarget2
    profile: sp_enderdragon
    show_tokens:
        light: l_toolcollect2
  enderdragon_shot8:
    switch: s_tooltarget1
    profile: sp_enderdragon
    show_tokens:
        light: l_toolcollect1
  enderdragon_shot9:                   #CRAFT
    switch: s_whitedot1
    profile: sp_enderdragon
    show_tokens:
        light: l_craft1
  enderdragon_shot10:
    switch: s_whitedot2
    profile: sp_enderdragon
    show_tokens:
        light: l_craft2
  enderdragon_shot11:
    switch: s_whitedot3
    profile: sp_enderdragon
    show_tokens:
        light: l_craft3
  enderdragon_shot12:
    switch: s_whitedot4
    profile: sp_enderdragon
    show_tokens:
        light: l_craft4
  enderdragon_shot13:               #SPINNER
    switch: s_spinner
    profile: sp_enderdragon
    show_tokens:
        light: l_spinner4
  enderdragon_shot14:           
    switch: s_spinner
    profile: sp_enderdragon
    show_tokens:
        light: l_spinner3
  enderdragon_shot15:                  
    switch: s_spinner
    profile: sp_enderdragon
    show_tokens:
        light: l_spinner2
  enderdragon_shot16:                   
    switch: s_spinner
    profile: sp_enderdragon
    show_tokens:
        light: l_spinner1
  enderdragon_shot17:                   
    switch: s_centertarget
    profile: sp_enderdragon
    show_tokens:
        light: l_worldtarget


shot_profiles:
  sp_enderdragon:
    states:
      - name: unlit
        show: "off"
      - name: lit
        show: "on"
    loop: true
    advance_on_hit: false

shot_groups:
  sg_enderdragon:
    shots: enderdragon_shot1, enderdragon_shot2, enderdragon_shot3, enderdragon_shot4, enderdragon_shot5, enderdragon_shot6, enderdragon_shot7, enderdragon_shot8, enderdragon_shot9, enderdragon_shot10, enderdragon_shot11, enderdragon_shot12, enderdragon_shot13, enderdragon_shot14, enderdragon_shot15, enderdragon_shot16, enderdragon_shot17
    restart_events: state_battle_started
    disable_events: state_battle_stopped
    rotate_events: timer_enderdragon_multiball_timer_tick

multiball_locks:
  endlocktop:
    balls_to_lock: 1
    locked_ball_counting_strategy: physical_only
    lock_devices: bd_topkicker 
    enable_events: state_prepare_started
    disable_events: theendmultiball_start, endmode_disable
  endlockright:
    balls_to_lock: 1
    locked_ball_counting_strategy: physical_only
    lock_devices: bd_scoop 
    enable_events: multiball_lock_endlocktop_full
    disable_events: theendmultiball_start, endmode_disable

multiballs:
  endmb:
    ball_count: 3
    ball_locks: bd_topkicker, bd_scoop
    enable_events: state_prepare_started
    start_events: theendmultiball_start
    shoot_again: 0s 


timers:
  enderdragon_restore_timer:
    start_value: 0
    end_value: 100
    direction: up
    tick_interval: 1s
    start_running: true
    restart_on_complete: true 
    control_events:
      - event: state_prepare_stopped
        action: stop
      - event: state_prepare_started
        action: restart
  enderdragon_multiball_timer:
    start_value: 0
    end_value: 100
    direction: up
    tick_interval: 1s
    start_running: false
    restart_on_complete: true 
    control_events:
      - event: state_battle_stopped
        action: stop  
      - event: state_battle_started
        action: restart
  enderdragon_growl_timer:
    start_value: 0
    end_value: 17
    direction: up
    tick_interval: 1s
    start_running: true
    restart_on_complete: true 
    control_events:
      - event: state_prepare_started
        action: start
      - event: state_victory_started
        action: stop

slides:
  theend_slide:
    widgets:
      - type: text
        font_name: lazer84
        font_size: 70
        text: "Pincraft\nLoading"
        z: 0

slide_player:
    mode_theend_started: theend_slide

widgets:
  widget_dragonhealth:
    - type: text        #Dragon Health
      text: DRAGON HEALTH (player|enderdragon_health)
      number_grouping: true
      min_digits: 2
      font_name: ARLRDBD
      font_size: 20
      y: center
      x: center
      z: 210
      anchor_x: middle
      anchor_y: middle
  widget_theendswordplayer:
    - type: image        #SCORE BACKGROUND
      image: Sword_FullScreen_Dark_1x
      anchor_x: right
      anchor_y: bottom
      y: bottom
      x: right
      z: 10

widget_player:
  slide_theend_slide_active:
    widget_screenbackground:
      action: update
      widget_settings:
        image: theend_background   

    widget_dragonhealth:
      action: add

#SHOW LARGE SWORD
  slide_theend_slide_active{current_player.sword==1}:
    widget_theendswordplayer:
      action: update
      slide: theend_slide
      widget_settings:
        image: Sword_FullScreen_1x
  slide_theend_slide_active{current_player.sword==2}:
    widget_theendswordplayer:
      action: update
      slide: theend_slide
      widget_settings:
        image: Sword_FullScreen_2x
  slide_theend_slide_active{current_player.sword==3}:
    widget_theendswordplayer:
      action: update
      slide: theend_slide
      widget_settings:
        image: Sword_FullScreen_3x
  slide_theend_slide_active{current_player.sword==4}:
    widget_theendswordplayer:
      action: update
      slide: theend_slide
      widget_settings:
        image: Sword_FullScreen_4x
  slide_theend_slide_active{current_player.sword==5}:
    widget_theendswordplayer:
      action: update
      slide: theend_slide
      widget_settings:
        image: Sword_FullScreen_5x


variable_player:

  #Enderdragon Health Init
  mode_theend_started:
    enderdragon_health:
      int: 100
      action: set
  
  #Enderdragon Health Damage and Scoring
  sg_enderdragon_lit_hit{current_player.enderdragon_health > 0}:
    enderdragon_health: -1 * current_player.multiplier_mb * current_player.sword
    score: 10000 * current_player.multiplier_mb * current_player.sword

  sg_enderdragon_lit_hit{current_player.enderdragon_health < 0}:
    enderdragon_health: 
      int: 0
      action: set 
  
  #Enderdragon Health Restore
  timer_enderdragon_restore_timer_tick{current_player.enderdragon_health < 100}:
    enderdragon_health: 1 

  #Victory Loop Scoring
  shot_victoryloopleft_hit: 
    score: 100000 * current_player.multiplier_mb * current_player.sword
  shot_victoryloopright_hit: 
    score: 100000 * current_player.multiplier_mb * current_player.sword

  #Dragon Defeated Scoring
  theend_dragon_defeated:
    score: 1000000 * current_player.multiplier_mb * current_player.sword

light_player:
  state_prepare_started:
    lbackbox: purple
    lundercab: purple
  state_battle_started:
    lbackbox: red
    lundercab: red
  state_victory_started:
    lbackbox: green
    lundercab: green
  state_travel_started:
    lbackbox: blue
    lundercab: blue 

sound_player:
  state_prepare_started:
    endmode_battle_music: stop
    endmode_prepare_music:
      action: play
      loops: -1
      mode_end_action: stop
  state_battle_started:
     endmode_prepare_music: stop
     endmode_battle_music:
      action: play
      loops: -1
      mode_end_action: stop
  state_victory_started:
    enderdragon_end: play
    endmode_battle_music: stop
    endmode_victory2_music:
      action: play
      loops: -1
      mode_end_action: stop
  timer_enderdragon_restore_timer_tick: enderdragon_wings
  timer_enderdragon_growl_timer_complete: enderdragon_growl
  timer_enderdragon_multiball_timer_tick: enderdragon_wings
  sg_enderdragon_lit_hit: enderdragon_hit


event_player:
  slide_theend_slide_active:
    show_player_score
    show_ball_count
    show_debug

  state_battle_started:
    advance_dragon_shots

  #mode_theend_started:
  #  theendmultiball_ready
  #mode_base_started:
  #  theendmultiball_ready

  #START THE END MULTIBALL ON PLUNGE
  sw_playfield_active_active{device.multiball_locks.endlockright.locked_balls==1 and device.multiball_locks.endlockright.enabled}:
    theendmultiball_start

  multiball_endmb_started:
    endermultiball_started
  timer_enderdragon_multiball_timer_tick{current_player.enderdragon_health == 0}:
    theend_dragon_defeated

  balldevice_bd_trough_ball_count_changed{device.ball_devices.bd_trough.balls==3}:
    trough_allballs

queue_relay_player:
  ball_ending{device.multiball_locks.endlocktop.locked_balls==1}:
    post: eject_topkicker
    wait_for: trough_allballs
