#config_version=5
mode:
    start_events: theend_started
    stop_events: theend_completed
    priority: 500

#TODO: Return to Travel State if awarded but ball drains
#TODO: Ensure all balls are ejected to trough when ball drains

show_player:
  mode_theend_started:  #Setup GI Light Show
    show_theendgi:
      loops: -1
      speed: 1

state_machines:
  statemachine_theend:
    persist_state: false
    states:
      start:
        label: Start state
      state_prepare:
        label: prepare state
        events_when_started: state_prepare_started
        events_when_stopped: state_prepare_stopped
      state_battle:
        label: battle state
        events_when_started: state_battle_started
        events_when_stopped: state_battle_stopped
      state_victory:
        label: victory state
        events_when_started: state_victory_started
        events_when_stopped: state_victory_stopped
      state_travel:
        label: travel state
        events_when_started: state_travel_started
    transitions:
      - source: start
        target: state_prepare
        events: mode_theend_started, ball_started
      - source: state_prepare
        target: state_battle
        events: multiball_endmb_started
      - source: state_battle
        target: state_prepare
        events: multiball_endmb_ended
      - source: state_battle
        target: state_victory
        events: theend_dragon_defeated
      - source: state_victory
        target: state_travel
        events: multiball_endmb_ended

shots:
  enderdragon_shot:
    switch: s_centertarget

multiball_locks:
  endlocktop:
    balls_to_lock: 1
    locked_ball_counting_strategy: physical_only
    lock_devices: bd_topkicker 
    enable_events: theendmultiball_ready
    disable_events: theendmultiball_start, endmode_disable
  endlockright:
    balls_to_lock: 1
    locked_ball_counting_strategy: physical_only
    lock_devices: bd_scoop 
    enable_events: multiball_lock_endlocktop_full
    disable_events: theendmultiball_start, endmode_disable

multiballs:
  endmb:
    ball_count: 3
    ball_locks: bd_topkicker, bd_scoop
    enable_events: theendmultiball_ready
    start_events: theendmultiball_start
    shoot_again: 0s 


timers:
  enderdragon_restore_timer:
    start_value: 0
    end_value: 100
    direction: up
    tick_interval: 1s
    start_running: true
    restart_on_complete: true 
    control_events:
      - event: mode_theend_started
        action: start
      - event: multiball_endmb_started
        action: stop
      - event: multiball_endmb_ended
        action: restart

slides:
  theend_slide:
    widgets:
      - type: text
        font_name: lazer84
        font_size: 70
        text: "Pincraft\nLoading"
        z: 0

slide_player:
    mode_theend_started: theend_slide

widgets:
  widget_dragonhealth:
    - type: text        #Dragon Health
      text: DRAGON HEALTH (player|enderdragon_health)
      number_grouping: true
      min_digits: 2
      font_name: ARLRDBD
      font_size: 20
      y: center
      x: center
      z: 210
      anchor_x: middle
      anchor_y: middle
  widget_theendswordplayer:
    - type: image        #SCORE BACKGROUND
      image: Sword_FullScreen_Dark_1x
      anchor_x: right
      anchor_y: bottom
      y: bottom
      x: right
      z: 10

widget_player:
  slide_theend_slide_active:
    widget_screenbackground:
      action: update
      widget_settings:
        image: theend_background   

    widget_dragonhealth:
      action: add

#SHOW LARGE SWORD
  slide_theend_slide_active{current_player.sword==1}:
    widget_theendswordplayer:
      action: update
      slide: theend_slide
      widget_settings:
        image: Sword_FullScreen_1x
  slide_theend_slide_active{current_player.sword==2}:
    widget_theendswordplayer:
      action: update
      slide: theend_slide
      widget_settings:
        image: Sword_FullScreen_2x
  slide_theend_slide_active{current_player.sword==3}:
    widget_theendswordplayer:
      action: update
      slide: theend_slide
      widget_settings:
        image: Sword_FullScreen_3x
  slide_theend_slide_active{current_player.sword==4}:
    widget_theendswordplayer:
      action: update
      slide: theend_slide
      widget_settings:
        image: Sword_FullScreen_4x
  slide_theend_slide_active{current_player.sword==5}:
    widget_theendswordplayer:
      action: update
      slide: theend_slide
      widget_settings:
        image: Sword_FullScreen_5x


variable_player:
  mode_theend_started:
    enderdragon_health:
      int: 100
      action: set
  enderdragon_shot_hit{current_player.enderdragon_health > 0}:
    enderdragon_health: -1 * current_player.multiplier_mb * current_player.sword
  enderdragon_shot_hit{current_player.enderdragon_health < 0}:
    enderdragon_health: 
      int: 0
      action: set 
  timer_enderdragon_restore_timer_tick{current_player.enderdragon_health < 100}:
    enderdragon_health: 1

event_player:
  slide_theend_slide_active:
    show_player_score
    show_debug
    show_ball_count

  mode_theend_started:
    theendmultiball_ready
  mode_base_started:
    theendmultiball_ready

light_player:
  state_prepare_started:
    lbackbox: purple
    lundercab: purple
  state_battle_started:
    lbackbox: red
    lundercab: red

sound_player:
  state_prepare_started:
    endmode_battle_music: stop
    endmode_prepare_music:
      action: play
      loops: -1
      mode_end_action: stop
  state_battle_started:
     endmode_prepare_music: stop
     endmode_battle_music:
      action: play
      loops: -1
      mode_end_action: stop
  timer_enderdragon_restore_timer_tick: enderdragon_wings
 



