#config_version=5
mode:
    start_events: travel_ready, nethermode_ready, stronghold_ready
    stop_events: nether_started, stronghold_started
    priority: 2100
    restart_on_next_ball: true

# shots:
#  shot_travel:
#     switch: s_portal

sound_player: 
 mode_travelready_started: voice_travel_ready

event_player:
  sshot_travel_hit{current_player.world_id != 5}:
    nether_started
  sshot_travel_hit{current_player.world_id==5}:
    stronghold_started


show_player:
  mode_travelready_started:
    show_travelloop:    
      loops: -1
      speed: 10
    show_travelblinking:    
      loops: -1
      speed: 2
