#config_version=5
mode:
    start_events: travel_ready, nethermode_ready, strongholdmode_ready, theend_ready
    stop_events: nether_started, stronghold_start, stronghold_jackpotcollect
    priority: 2100
    restart_on_next_ball: true

# shots:
#  shot_travel:
#     switch: s_portal

sound_player: 
 mode_travelready_started: voice_travel_ready

event_player:
  sshot_travel_hit:
    travel_hit
  skill_success:
    travel_hit

  travel_hit{current_player.world_id==1}:
    - world1_completed
    - nether_started
  travel_hit{current_player.world_id==2}:
    - world2_completed
    - nether_started
  travel_hit{current_player.world_id==3}:
    - world3_completed
    - nether_started
  travel_hit{current_player.world_id==4}:
    - world4_completed
    - nether_started
  travel_hit{current_player.world_id==5}:
    - world5_completed
    - stronghold_start
  travel_hit{current_player.world_id==51}:
    - stronghold_completed
    - stronghold_jackpotcollect

show_player:
  mode_travelready_started:
    show_travelloop:    
      loops: -1
      speed: 10
    show_travelblinking:    
      loops: -1
      speed: 2

