#config_version=5
mode:
    start_events: world1_started
    stop_events: world1_completed
    priority: 500

show_player:
  mode_world1_started:  #Setup GI Light Show
    show_world1gi:
      loops: -1
      speed: 1

light_player:
  mode_world1_started:
    lbackbox: green
    lundercab: green

sound_player:
  mode_world1_started:
    world1mode_music:
      action: play
      loops: -1
      mode_end_action: stop
  mode_villagermb_stopped:
    world1mode_music:
      action: play
      loops: -1
      mode_end_action: stop
  world1_collected: travel_ready

variable_player:
  #setup environment variables
  mode_world1_started{current_player.world1_setup==0}:  
    #World Settings
    world_id:
      int: 1
      action: set
    world_name: 
      string: "World 1"
      action: set
    world_color: 
      string: "GREEN"
      action: set

    #Item 1 Settings
    world_item1_name:
      string: "Dirt"
      action: set 
    world_item1_color:
      string: "GREEN"
      action: set 
    world_item1_remaining:
      int: 2
      action: set

    #Item 2 Settings
    world_item2_name:
      string: "Stone"
      action: set 
    world_item2_color:
      string: "GRAY"
      action: set 
    world_item2_remaining:
      int: 2
      action: set

    #Item 3 Settings
    world_item3_name:
      string: "Ore"
      action: set 
    world_item3_color:
      string: "BROWN"
      action: set 
    world_item3_remaining:
      int: 2
      action: set

    #Item 4 Settings
    world_item4_name:
      string: "Wood"
      action: set 
    world_item4_color:
      string: "SLATEGRAY"
      action: set 
    world_item4_remaining:
      int: 2
      action: set

    #Mark World as Setup
    world1_setup: 1


event_player:
  world_collected:
    world1_collected