#config_version=5
mode:
    start_events: world1_start
    stop_events: world1_completed
    priority: 500

show_player:
  mode_world1_started:  #Setup GI Light Show
    show_world1gi:
      loops: -1
      speed: 1

sound_player:
  mode_world1_started:
    world1mode_music:
      action: play
      loops: -1
      mode_end_action: stop
  multiball_villagermb_ended:
    world1mode_music:
      action: play
      loops: -1
      mode_end_action: stop
      
variable_player:
  #setup environment variables
  mode_world1_started:  
    #World Settings
    world_id:
      int: 1
      action: set
    world_name: 
      string: "World 1"
      action: set
    world_color: 
      string: "GREEN"
      action: set

    #Item 1 Settings
    world_item1_name:
      string: "Dirt"
      action: set 
    world_item1_color:
      string: "GREEN"
      action: set 
    world_item1_needed:
      int: 2
      action: set

    #Item 2 Settings
    world_item2_name:
      string: "Stone"
      action: set 
    world_item2_color:
      string: "GRAY"
      action: set 
    world_item2_needed:
      int: 2
      action: set

    #Item 3 Settings
    world_item3_name:
      string: "Ore"
      action: set 
    world_item3_color:
      string: "BROWN"
      action: set 
    world_item3_needed:
      int: 2
      action: set

    #Item 4 Settings
    world_item4_name:
      string: "Wood"
      action: set 
    world_item4_color:
      string: "SLATEGRAY"
      action: set 
    world_item4_needed:
      int: 2
      action: set

  logicblock_wc1_item1_counter_updated:
    world_item1_remaining:
      int: value
      action: set
  logicblock_wc1_item2_counter_updated:
    world_item2_remaining:
      int: value
      action: set
  logicblock_wc1_item3_counter_updated:
    world_item3_remaining:
      int: value
      action: set
  logicblock_wc1_item4_counter_updated:
    world_item4_remaining:
      int: value
      action: set

counters:
  wc1_item1_counter:
    count_events: collectitem1_hit
    reset_on_complete: False
    starting_count: 2
    count_complete_value: 0
    direction: down
    persist_state: true
    events_when_complete: w1_itemcheckcomplete
    multiple_hit_window: 500ms
    enable_events: mode_world1_started
  wc1_item2_counter:
    count_events: collectitem2_hit
    reset_on_complete: False
    starting_count: 2
    count_complete_value: 0
    direction: down
    persist_state: true
    events_when_complete: w1_itemcheckcomplete
    multiple_hit_window: 500ms
    enable_events: mode_world1_started
  wc1_item3_counter:
    count_events: collectitem4_hit
    reset_on_complete: False
    starting_count: 2
    count_complete_value: 0
    direction: down
    persist_state: true
    events_when_complete: w1_itemcheckcomplete
    multiple_hit_window: 500ms
    enable_events: mode_world1_started
  wc1_item4_counter:
    count_events: collectitem5_hit
    reset_on_complete: False
    starting_count: 2
    count_complete_value: 0
    direction: down
    persist_state: true
    events_when_complete: w1_itemcheckcomplete
    multiple_hit_window: 500ms
    enable_events: mode_world1_started

event_player:
  mode_world1_started:
    world1_started
    w1_itemcheckcomplete
  w1_itemcheckcomplete{current_player.world_item1_remaining == 0 and current_player.world_item2_remaining == 0 and current_player.world_item3_remaining == 0 and current_player.world_item4_remaining == 0}:
    world1_collected
    nightmode_ready

  w1_itemcheckcomplete{current_player.world_item1_remaining > 0}:
    collectitem1_enabled
  w1_itemcheckcomplete{current_player.world_item1_remaining == 0}:
    collectitem1_disabled
  
  w1_itemcheckcomplete{current_player.world_item2_remaining > 0}:
    collectitem2_enabled
  w1_itemcheckcomplete{current_player.world_item2_remaining == 0}:
    collectitem2_disabled

  w1_itemcheckcomplete{current_player.world_item3_remaining > 0}:
    collectitem3_enabled
  w1_itemcheckcomplete{current_player.world_item3_remaining == 0}:
    collectitem3_disabled

  w1_itemcheckcomplete{current_player.world_item4_remaining > 0}:
    collectitem4_enabled
  w1_itemcheckcomplete{current_player.world_item4_remaining == 0}:
    collectitem4_disabled