#config_version=5
mode:
    start_events: world1_started
    stop_events: world1_completed
    priority: 300

show_player:
  mode_world1_started:  #Setup GI Light Show
    show_world1gi:
      loops: -1
      speed: 1
  collectitem1_hit: 
    show_itemcollected_world1item1:
      loops: 0
  collectitem2_hit:
    show_itemcollected_world1item2:
      loops: 0
  collectitem3_hit:
    show_itemcollected_world1item3:
      loops: 0
  collectitem4_hit:
    show_itemcollected_world1item4:
      loops: 0

light_player:
  mode_world1_started:
    lbackbox: green
    lundercab: green  

sound_player:
  mode_world1_started:
    world1mode_music:
      action: play
      loops: -1
      mode_end_action: stop
  worldmultiball_ended:
    world1mode_music:
      action: play
      loops: -1
      mode_end_action: stop

variable_player:
  #setup environment variables
  mode_world1_started{current_player.world1_setup==0}:  
    #World Settings
    world_id:
      int: 1
      action: set
    world_name: 
      string: "World 1"
      action: set
    world_color: 
      string: "GREEN"
      action: set

    #Item 1 Settings
    world_item1_name:
      string: "Grass"
      action: set 
    world_item1_color:
      string: "GREEN"
      action: set 
    world_item1_remaining:
      int: 2
      action: set

    #Item 2 Settings
    world_item2_name:
      string: "Solid Stone"
      action: set 
    world_item2_color:
      string: "GRAY"
      action: set 
    world_item2_remaining:
      int: 2
      action: set

    #Item 3 Settings
    world_item3_name:
      string: "Iron Ore"
      action: set 
    world_item3_color:
      string: "BROWN"
      action: set 
    world_item3_remaining:
      int: 2
      action: set

    #Item 4 Settings
    world_item4_name:
      string: "Oak Log"
      action: set 
    world_item4_color:
      string: "SLATEGRAY"
      action: set 
    world_item4_remaining:
      int: 2
      action: set

    #Mark World as Setup
    world1_setup: 1



widgets:
  widget_world1videobackground:
    - type: video
      video: video_world1_overview
      auto_play: true
      end_behavior: loop
      z: 6

widget_player:
  mode_world1_started:
    widget_world1videobackground:
      action: add
      slide: world_slide
    widget_item1icon:
      action: update
      slide: world_slide
      widget_settings:
        image: Grass_Small
    widget_item2icon:
      action: update
      slide: world_slide
      widget_settings:
        image: Stone_Small
    widget_item3icon:
      action: update
      slide: world_slide
      widget_settings:
        image: IronOre_Small
    widget_item4icon:
      action: update
      slide: world_slide
      widget_settings:
        image: WoodOak_Small

event_player:
  world_collected:
    world1_collected
  mode_villagercontroller_stopped:
    worldmultiball_ended
  mode_nightcontroller_stopped:
    worldmultiball_ended
  mode_nightvillagercontroller_stopped:
    worldmultiball_ended

