#config_version=5
mode:
    start_events: strongholdmb_start
    stop_events: stronghold_completed
    restart_on_next_ball: true
    priority: 200


variable_player:
  set1_left_flashing_hit:
    score: 100000 * current_player.multiplier_mb * current_player.sword 
  set1_center_flashing_hit:
    score: 100000 * current_player.multiplier_mb * current_player.sword 
  set1_right_flashing_hit:
    score: 100000 * current_player.multiplier_mb * current_player.sword 
  eyeset1_complete:
    score: 250000 * current_player.multiplier_mb * current_player.sword 
    stronghold_progress:
      int: 1
      action: set

  set2_left_flashing_hit:
    score: 100000 * current_player.multiplier_mb * current_player.sword 
  set2_center_flashing_hit:
    score: 100000 * current_player.multiplier_mb * current_player.sword 
  set2_right_flashing_hit:
    score: 100000 * current_player.multiplier_mb * current_player.sword 
  eyeset2_complete:
    score: 500000 * current_player.multiplier_mb * current_player.sword 
    stronghold_progress:
        int: 2
        action: set

  set3_left_flashing_hit:
    score: 100000 * current_player.multiplier_mb * current_player.sword 
  set3_center_flashing_hit:
    score: 100000 * current_player.multiplier_mb * current_player.sword 
  set3_right_flashing_hit:
    score: 100000 * current_player.multiplier_mb * current_player.sword 
  eyeset3_complete:
    score: 750000 * current_player.multiplier_mb * current_player.sword 
    stronghold_progress:
        int: 3
        action: set


  set4_left_flashing_hit:
    score: 100000 * current_player.multiplier_mb * current_player.sword 
  set4_center_flashing_hit:
    score: 100000 * current_player.multiplier_mb * current_player.sword 
  set4_right_flashing_hit:
    score: 100000 * current_player.multiplier_mb * current_player.sword 
  eyeset4_complete:
    score: 1000000 * current_player.multiplier_mb * current_player.sword 
    stronghold_progress:
        int: 4
        action: set

  award_strongholdjackpot:
    score: current_player.stronghold_jackpot * current_player.sword

  eyespinner_hit:
    stronghold_jackpot: 100000

  mode_stronghold_started:
    world_id:
      int: 6
      action: set
    stronghold_progress:
      int: 0
      action: set

sound_player:
  mode_stronghold_started:
    stronghold_music:
      action: play
      loops: -1
      mode_end_action: stop
    stronghold_collect:
      action: play
      loops: 0
  eyeset4_complete{current_player.multiplier_mb==2}:
    stronghold_travel_multiball
  eyeset4_complete{current_player.multiplier_mb==1}:
    stronghold_travel_single
  award_strongholdjackpot:
    stronghold_jackpot

  set1_left_flashing_hit: eyeplacesp
  set1_center_flashing_hit: eyeplacesp
  set1_right_flashing_hit: eyeplacesp
  set2_left_flashing_hit: eyeplacesp
  set2_center_flashing_hit: eyeplacesp
  set2_right_flashing_hit: eyeplacesp
  set3_left_flashing_hit: eyeplacesp
  set3_center_flashing_hit: eyeplacesp
  set3_right_flashing_hit: eyeplacesp
  set4_left_flashing_hit: eyeplacesp
  set4_center_flashing_hit: eyeplacesp
  set4_right_flashing_hit: eyeplacesp
  eyespinner_hit: eyeplacesp
  enable_endportal: endportal

shot_profiles:
  sp_eyeshot:
    states:
      - name: flashing  # step 2
        show: flash
      - name: lit  # step 3
        show: on
    loop: no
  sp_eyespinner:
    states:
      - name: flashing  # step 2
        show: show_superspinner
    loop: yes

shots:
  set1_left:
    switch: s_collectitem1
    profile: sp_eyeshot
    enable_events: enable_eyeset1
    disable_events: eyeset1_complete
    show_tokens:
      leds: l_collectitem1
  set1_center:
    switch: s_tooltarget1
    profile: sp_eyeshot
    enable_events: enable_eyeset1
    disable_events: eyeset1_complete
    show_tokens:
      leds: l_toolcollect1
  set1_right:
    switch: s_spinner
    profile: sp_eyeshot
    enable_events: enable_eyeset1
    disable_events: eyeset1_complete
    show_tokens:
      leds: l_spinner1

  set2_left:
    switch: s_collectitem2
    profile: sp_eyeshot
    enable_events: enable_eyeset2
    disable_events: eyeset2_complete
    show_tokens:
      leds: l_collectitem2
  set2_center:
    switch: s_tooltarget2
    profile: sp_eyeshot
    enable_events: enable_eyeset2
    disable_events: eyeset2_complete
    show_tokens:
      leds: l_toolcollect2
  set2_right:
    switch: s_spinner
    profile: sp_eyeshot
    enable_events: enable_eyeset2
    disable_events: eyeset2_complete
    show_tokens:
      leds: l_spinner2

  set3_left:
    switch: s_collectitem4
    profile: sp_eyeshot
    enable_events: enable_eyeset3
    disable_events: eyeset3_complete
    show_tokens:
      leds: l_collectitem4
  set3_center:
    switch: s_tooltarget3
    profile: sp_eyeshot
    enable_events: enable_eyeset3
    disable_events: eyeset3_complete
    show_tokens:
      leds: l_toolcollect3
  set3_right:
    switch: s_spinner
    profile: sp_eyeshot
    enable_events: enable_eyeset3
    disable_events: eyeset3_complete
    show_tokens:
      leds: l_spinner3

  set4_left:
    switch: s_collectitem5
    profile: sp_eyeshot
    enable_events: enable_eyeset4
    disable_events: eyeset4_complete
    show_tokens:
      leds: l_collectitem5
  set4_center:
    switch: s_topkicker
    profile: sp_eyeshot
    enable_events: enable_eyeset4
    disable_events: eyeset4_complete
    show_tokens:
      leds: l_craftlit
  set4_right:
    switch: s_spinner
    profile: sp_eyeshot
    enable_events: enable_eyeset4
    disable_events: eyeset4_complete
    show_tokens:
      leds: l_spinner4

  eyespinner:
    switch: s_spinner  
    profile: sp_eyespinner
    enable_events: enable_eyespinner
    disable_events: disable_eyespinner

  strongholdtravel:
    switch: s_portal
    profile: sp_eyeshot
    enable_events: enable_endportal


shot_groups:
  eyeset1:
    shots: set1_left, set1_center, set1_right
    restart_events: enable_eyeset1
    disable_events: eyeset1_complete
  eyeset2:
    shots: set2_left, set2_center, set2_right
    restart_events: enable_eyeset2
    disable_events: eyeset2_complete
  eyeset3:
    shots: set3_left, set3_center, set3_right
    restart_events: enable_eyeset3
    disable_events: eyeset3_complete
  eyeset4:
    shots: set4_left, set4_center, set4_right
    restart_events: enable_eyeset4
    disable_events: eyeset4_complete

widgets:
  widget_swordplayer:
    - type: image        #SCORE BACKGROUND
      image: Sword_FullScreen_Dark_1x
      anchor_x: right
      anchor_y: bottom
      y: bottom
      x: right
      z: 10
  widget_endportal:
    - type: image
      image: endportal_0
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 100
  widget_eye1:
    - type: image
      image: endportal_eye1
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye2:
    - type: image
      image: endportal_eye2
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye3:
    - type: image
      image: endportal_eye3
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye4:
    - type: image
      image: endportal_eye4
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye5:
    - type: image
      image: endportal_eye5
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye6:
    - type: image
      image: endportal_eye6
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye7:
    - type: image
      image: endportal_eye7
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye8:
    - type: image
      image: endportal_eye8
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye9:
    - type: image
      image: endportal_eye9
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye10:
    - type: image
      image: endportal_eye10
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye11:
    - type: image
      image: endportal_eye11
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye12:
    - type: image
      image: endportal_eye12
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_portalopen:
    - type: image
      image: endportal_active
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 150

slides:
  stronghold_slide:
    widgets:
      - type: text
        font_name: lazer84
        font_size: 70
        text: "Pincraft\nLoading"
        z: 0

slide_player:
    mode_stronghold_started: stronghold_slide
  
light_player:
  mode_stronghold_started:
    lactionbar: off
  set1_left_flashing_hit: 
    l_actionbar7: blue
    l_actionbar8: blue
    l_actionbar9: blue
  set1_center_flashing_hit: 
    l_actionbar4: blue
    l_actionbar5: blue
    l_actionbar6: blue
  set1_right_flashing_hit: 
    l_actionbar1: blue
    l_actionbar2: blue
    l_actionbar3: blue
  set2_left_flashing_hit: 
    l_actionbar10: blue
    l_actionbar11: blue
    l_actionbar12: blue
  set2_center_flashing_hit: 
    l_actionbar13: blue
    l_actionbar14: blue
    l_actionbar15: blue
  set2_right_flashing_hit: 
    l_actionbar16: blue
    l_actionbar17: blue
    l_actionbar18: blue
  set3_left_flashing_hit: 
    l_actionbar19: blue
    l_actionbar20: blue
    l_actionbar21: blue
  set3_center_flashing_hit: 
    l_actionbar22: blue
    l_actionbar23: blue
    l_actionbar24: blue
  set3_right_flashing_hit: 
    l_actionbar25: blue
    l_actionbar26: blue
    l_actionbar27: blue
  set4_left_flashing_hit:
    l_actionbar34: blue
    l_actionbar35: blue
    l_actionbar36: blue
    l_actionbar37: blue
  set4_center_flashing_hit: 
    l_actionbar31: blue
    l_actionbar32: blue
    l_actionbar33: blue
  set4_right_flashing_hit: 
    l_actionbar28: blue
    l_actionbar29: blue
    l_actionbar30: blue
  update_eye_display{current_player.stronghold_progress >=1}:
    l_actionbar1: blue
    l_actionbar2: blue
    l_actionbar3: blue
    l_actionbar4: blue
    l_actionbar5: blue
    l_actionbar6: blue
    l_actionbar7: blue
    l_actionbar8: blue
    l_actionbar9: blue
  update_eye_display{current_player.stronghold_progress >=2}:
    l_actionbar10: blue
    l_actionbar11: blue
    l_actionbar12: blue
    l_actionbar13: blue
    l_actionbar14: blue
    l_actionbar15: blue
    l_actionbar16: blue
    l_actionbar17: blue
    l_actionbar18: blue
  update_eye_display{current_player.stronghold_progress >=3}:
    l_actionbar19: blue
    l_actionbar20: blue
    l_actionbar21: blue
    l_actionbar22: blue
    l_actionbar23: blue
    l_actionbar24: blue
    l_actionbar25: blue
    l_actionbar26: blue
    l_actionbar27: blue
  update_eye_display{current_player.stronghold_progress >=4}:
    lactionbar: blue

widget_player:
  slide_stronghold_slide_active:
    widget_endportal:
      action: add
      slide: stronghold_slide
    widget_screenbackground:
      action: add
      slide: stronghold_slide
      widget_settings:
        image: stronghold_background
  update_eye_display{current_player.stronghold_progress >=1}:
    widget_eye1
    widget_eye2
    widget_eye3
  update_eye_display{current_player.stronghold_progress >=2}:
    widget_eye4
    widget_eye5
    widget_eye6
  update_eye_display{current_player.stronghold_progress >=3}:
    widget_eye7
    widget_eye8
    widget_eye9
  update_eye_display{current_player.stronghold_progress >=4}:
    widget_eye10
    widget_eye11
    widget_eye12
    widget_portalopen

  set1_left_flashing_hit: widget_eye3
  set1_center_flashing_hit: widget_eye2
  set1_right_flashing_hit: widget_eye1
  set2_left_flashing_hit: widget_eye4
  set2_center_flashing_hit: widget_eye5
  set2_right_flashing_hit: widget_eye6
  set3_left_flashing_hit: widget_eye7
  set3_center_flashing_hit: widget_eye8
  set3_right_flashing_hit: widget_eye9
  set4_left_flashing_hit: widget_eye12
  set4_center_flashing_hit: widget_eye11
  set4_right_flashing_hit: widget_eye10
  enable_endportal: widget_portalopen
   

event_player:
  slide_stronghold_slide_active:
    show_player_score
    show_ball_count
    show_multiplier
    update_eye_display
   # show_debug

  mode_stronghold_started{current_player.stronghold_progress==0}:
    enable_eyeset1
  mode_stronghold_started{current_player.stronghold_progress==1}:
    eyeset1_complete
  mode_stronghold_started{current_player.stronghold_progress==2}:
    eyeset2_complete
  mode_stronghold_started{current_player.stronghold_progress==3}:
    eyeset3_complete
  mode_stronghold_started{current_player.stronghold_progress==4}:
    eyeset4_complete

  
  eyeset1_complete:
    enable_eyeset2
  eyeset2_complete:
    enable_eyeset3
  eyeset3_complete:
    enable_eyeset4
  # eyeset4_complete:
  #   enable_endportal
  eyeset4_complete{current_player.multiplier_mb==2}:
    enable_eyespinner
  eyeset4_complete{current_player.multiplier_mb==1}:
    disable_eyespinner
    theend_ready
    enable_endportal
  multiball_strongholdmb_ended:
    disable_eyespinner
