#config_version=5
mode:
    start_events: strongholdmb_start
    stop_events: stronghold_completed
    restart_on_next_ball: true
    priority: 200


variable_player:
  set1_left_flashing_hit:
    score: 10000 * current_player.multiplier_mb * current_player.sword 
  set1_center_flashing_hit:
    score: 10000 * current_player.multiplier_mb * current_player.sword 
  set1_right_flashing_hit:
    score: 10000 * current_player.multiplier_mb * current_player.sword 
  eyeset1_complete:
    score: 50000 * current_player.multiplier_mb * current_player.sword 
    stronghold_jackpot: 250000
    stronghold_progress:
      int: 1
      action: set
    

  set2_left_flashing_hit:
    score: 10000 * current_player.multiplier_mb * current_player.sword 
  set2_center_flashing_hit:
    score: 10000 * current_player.multiplier_mb * current_player.sword 
  set2_right_flashing_hit:
    score: 10000 * current_player.multiplier_mb * current_player.sword 
  eyeset2_complete:
    score: 50000 * current_player.multiplier_mb * current_player.sword 
    stronghold_jackpot: 500000
    stronghold_progress:
        int: 2
        action: set

  set3_left_flashing_hit:
    score: 10000 * current_player.multiplier_mb * current_player.sword 
  set3_center_flashing_hit:
    score: 10000 * current_player.multiplier_mb * current_player.sword 
  set3_right_flashing_hit:
    score: 10000 * current_player.multiplier_mb * current_player.sword 
  eyeset3_complete:
    score: 50000 * current_player.multiplier_mb * current_player.sword 
    stronghold_jackpot: 750000
    stronghold_progress:
        int: 3
        action: set


  set4_left_flashing_hit:
    score: 10000 * current_player.multiplier_mb * current_player.sword 
  set4_center_flashing_hit:
    score: 10000 * current_player.multiplier_mb * current_player.sword 
  set4_right_flashing_hit:
    score: 10000 * current_player.multiplier_mb * current_player.sword 
  eyeset4_complete:
    score: 50000 * current_player.multiplier_mb * current_player.sword 
    stronghold_jackpot: 1000000
    stronghold_progress:
        int: 4
        action: set

  award_strongholdjackpot:
    score: current_player.stronghold_jackpot * current_player.sword

  eyespinner_hit:
    stronghold_jackpot: 50000

  mode_stronghold_started:
    world_id:
      int: 51
      action: set
    stronghold_progress:
      int: 0
      action: set

sound_player:
  mode_stronghold_started:
    stronghold_music:
      action: play
      loops: -1
      mode_end_action: stop
    stronghold_collect:
      action: play
      loops: 0
  eyeset4_complete{current_player.multiplier_mb==2}:
    stronghold_travel_multiball
  eyeset4_complete{current_player.multiplier_mb==1}:
    stronghold_travel_single
  award_strongholdjackpot:
    stronghold_jackpot

  set1_left_flashing_hit: eyeplacesp
  set1_center_flashing_hit: eyeplacesp
  set1_right_flashing_hit: eyeplacesp
  set2_left_flashing_hit: eyeplacesp
  set2_center_flashing_hit: eyeplacesp
  set2_right_flashing_hit: eyeplacesp
  set3_left_flashing_hit: eyeplacesp
  set3_center_flashing_hit: eyeplacesp
  set3_right_flashing_hit: eyeplacesp
  set4_left_flashing_hit: eyeplacesp
  set4_center_flashing_hit: eyeplacesp
  set4_right_flashing_hit: eyeplacesp
  eyespinner_hit: eyeplacesp
  enable_endportal: endportal

shot_profiles:
  sp_eyeshot:
    states:
      - name: flashing  # step 2
        show: show_altcolor
        show_tokens:
          color1: 417266
          color2: white
      - name: turnon  # step 3
        show: show_singlelight
        show_tokens:
          color: 417266
    loop: no
  sp_eyespinner:
    states:
      - name: flashing  # step 2
        show: show_spinnerenabled
        priority: 10
    loop: yes

shots:
  set1_left:
    switch: s_collectitem1
    profile: sp_eyeshot
    enable_events: enable_eyeset1
    disable_events: eyeset1_complete
    show_tokens:
      leds: l_collectitem1
      light: l_collectitem1
  set1_center:
    switch: s_tooltarget1
    profile: sp_eyeshot
    enable_events: enable_eyeset1
    disable_events: eyeset1_complete
    show_tokens:
      leds: l_toolcollect1
      light: l_toolcollect1
  set1_right:
    switch: s_spinner
    profile: sp_eyeshot
    enable_events: enable_eyeset1
    disable_events: eyeset1_complete
    show_tokens:
      leds: l_spinner1
      light: l_spinner1
  set2_left:
    switch: s_collectitem2
    profile: sp_eyeshot
    enable_events: enable_eyeset2
    disable_events: eyeset2_complete
    show_tokens:
      leds: l_collectitem2
      light: l_collectitem2
  set2_center:
    switch: s_tooltarget2
    profile: sp_eyeshot
    enable_events: enable_eyeset2
    disable_events: eyeset2_complete
    show_tokens:
      leds: l_toolcollect2
      light: l_toolcollect2
  set2_right:
    switch: s_spinner
    profile: sp_eyeshot
    enable_events: enable_eyeset2
    disable_events: eyeset2_complete
    show_tokens:
      leds: l_spinner2
      light: l_spinner2

  set3_left:
    switch: s_collectitem4
    profile: sp_eyeshot
    enable_events: enable_eyeset3
    disable_events: eyeset3_complete
    show_tokens:
      leds: l_collectitem4
      light: l_collectitem4
  set3_center:
    switch: s_tooltarget3
    profile: sp_eyeshot
    enable_events: enable_eyeset3
    disable_events: eyeset3_complete
    show_tokens:
      leds: l_toolcollect3
      light: l_toolcollect3
  set3_right:
    switch: s_spinner
    profile: sp_eyeshot
    enable_events: enable_eyeset3
    disable_events: eyeset3_complete
    show_tokens:
      leds: l_spinner3
      light: l_spinner3

  set4_left:
    switch: s_collectitem5
    profile: sp_eyeshot
    enable_events: enable_eyeset4
    disable_events: eyeset4_complete
    show_tokens:
      leds: l_collectitem5
      light: l_collectitem5
  set4_center:
    switch: s_topkicker
    profile: sp_eyeshot
    enable_events: enable_eyeset4
    disable_events: eyeset4_complete
    show_tokens:
      leds: l_craftlit
      light: l_craftlit
  set4_right:
    switch: s_spinner
    profile: sp_eyeshot
    enable_events: enable_eyeset4
    disable_events: eyeset4_complete
    show_tokens:
      leds: l_spinner4
      light: l_spinner4

  eyespinner:
    switch: s_spinner  
    profile: sp_eyespinner
    enable_events: enable_eyespinner
    disable_events: disable_eyespinner

  # strongholdtravel:
  #   switch: s_portal
  #   profile: sp_eyeshot
  #   enable_events: enable_endportal


shot_groups:
  eyeset1:
    shots: set1_left, set1_center, set1_right
    restart_events: enable_eyeset1
    disable_events: eyeset1_complete
  eyeset2:
    shots: set2_left, set2_center, set2_right
    restart_events: enable_eyeset2
    disable_events: eyeset2_complete
  eyeset3:
    shots: set3_left, set3_center, set3_right
    restart_events: enable_eyeset3
    disable_events: eyeset3_complete
  eyeset4:
    shots: set4_left, set4_center, set4_right
    restart_events: enable_eyeset4
    disable_events: eyeset4_complete

widgets:
  widget_swordplayer:
    - type: image        #SCORE BACKGROUND
      image: Sword_FullScreen_Dark_1x
      anchor_x: right
      anchor_y: bottom
      y: bottom
      x: right
      z: 10
  widget_endportal:
    - type: image
      image: endportal_0
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 100
  widget_eye1:
    - type: image
      image: endportal_eye1
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye2:
    - type: image
      image: endportal_eye2
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye3:
    - type: image
      image: endportal_eye3
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye4:
    - type: image
      image: endportal_eye4
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye5:
    - type: image
      image: endportal_eye5
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye6:
    - type: image
      image: endportal_eye6
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye7:
    - type: image
      image: endportal_eye7
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye8:
    - type: image
      image: endportal_eye8
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye9:
    - type: image
      image: endportal_eye9
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye10:
    - type: image
      image: endportal_eye10
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye11:
    - type: image
      image: endportal_eye11
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye12:
    - type: image
      image: endportal_eye12
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_portalopen:
    - type: image
      image: endportal_active
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 150

  widget_strongholdjackpot:
    - type: image        #STRONGHOLD JACKPOT TEXT
      image: jackpot_stronghold
      anchor_x: center
      anchor_y: center
      y: bottom+100
      x: center+35
      z: 15    
    - type: text        #STRONGHOLD JACKPOT VALUE
      text: (player|stronghold_jackpot)
      number_grouping: true
      min_digits: 2
      font_name: ARLRDBD
      font_size: 24
      y: bottom+75
      x: center+35
      z: 100
      anchor_x: center
      anchor_y: center

slides:
  stronghold_slide:
    widgets:
      - type: image
        image: Pincraft_Logo_Icon

slide_player:
    mode_stronghold_started: stronghold_slide
  
light_player:
  mode_stronghold_started:
    lactionbar: off
  set1_left_flashing_hit: 
    l_actionbar7: 417266
    l_actionbar8: 417266
    l_actionbar9: 417266
  set1_center_flashing_hit: 
    l_actionbar4: 417266
    l_actionbar5: 417266
    l_actionbar6: 417266
  set1_right_flashing_hit: 
    l_actionbar1: 417266
    l_actionbar2: 417266
    l_actionbar3: 417266
  set2_left_flashing_hit: 
    l_actionbar10: 417266
    l_actionbar11: 417266
    l_actionbar12: 417266
  set2_center_flashing_hit: 
    l_actionbar13: 417266
    l_actionbar14: 417266
    l_actionbar15: 417266
  set2_right_flashing_hit: 
    l_actionbar16: 417266
    l_actionbar17: 417266
    l_actionbar18: 417266
  set3_left_flashing_hit: 
    l_actionbar19: 417266
    l_actionbar20: 417266
    l_actionbar21: 417266
  set3_center_flashing_hit: 
    l_actionbar22: 417266
    l_actionbar23: 417266
    l_actionbar24: 417266
  set3_right_flashing_hit: 
    l_actionbar25: 417266
    l_actionbar26: 417266
    l_actionbar27: 417266
  set4_left_flashing_hit:
    l_actionbar34: 417266
    l_actionbar35: 417266
    l_actionbar36: 417266
    l_actionbar37: 417266
  set4_center_flashing_hit: 
    l_actionbar31: 417266
    l_actionbar32: 417266
    l_actionbar33: 417266
  set4_right_flashing_hit: 
    l_actionbar28: 417266
    l_actionbar29: 417266
    l_actionbar30: 417266
  update_eye_display{current_player.stronghold_progress >=1}:
    l_actionbar1: 417266
    l_actionbar2: 417266
    l_actionbar3: 417266
    l_actionbar4: 417266
    l_actionbar5: 417266
    l_actionbar6: 417266
    l_actionbar7: 417266
    l_actionbar8: 417266
    l_actionbar9: 417266
    l_collectitem1: 417266
    l_toolcollect1: 417266
    l_spinner1: 417266
  update_eye_display{current_player.stronghold_progress >=2}:
    l_actionbar10: 417266
    l_actionbar11: 417266
    l_actionbar12: 417266
    l_actionbar13: 417266
    l_actionbar14: 417266
    l_actionbar15: 417266
    l_actionbar16: 417266
    l_actionbar17: 417266
    l_actionbar18: 417266
    l_collectitem2: 417266
    l_toolcollect2: 417266
    l_spinner2: 417266
  update_eye_display{current_player.stronghold_progress >=3}:
    l_actionbar19: 417266
    l_actionbar20: 417266
    l_actionbar21: 417266
    l_actionbar22: 417266
    l_actionbar23: 417266
    l_actionbar24: 417266
    l_actionbar25: 417266
    l_actionbar26: 417266
    l_actionbar27: 417266
    l_collectitem4: 417266
    l_toolcollect3: 417266
    l_spinner3: 417266
  update_eye_display{current_player.stronghold_progress >=4}:
    lactionbar: 417266
    l_collectitem5: 417266
    l_craftlit: 417266
    l_spinner4: 417266

widget_player:
  slide_stronghold_slide_active:
    widget_endportal:
      action: add
      slide: stronghold_slide
    widget_screenbackground:
      action: add
      slide: stronghold_slide
      widget_settings:
        image: stronghold_background
    widget_strongholdjackpot:
      action: add
      slide: stronghold_slide
  update_eye_display{current_player.stronghold_progress >=1}:
    widget_eye1:
      action: add
    widget_eye2:
      action: add
    widget_eye3:
      action: add
  update_eye_display{current_player.stronghold_progress >=2}:
    widget_eye4:
      action: add
    widget_eye5:
      action: add
    widget_eye6:
      action: add
  update_eye_display{current_player.stronghold_progress >=3}:
    widget_eye7:
      action: add
    widget_eye8:
      action: add
    widget_eye9:
      action: add
  update_eye_display{current_player.stronghold_progress >=4}:
    widget_eye10:
      action: add
    widget_eye11:
      action: add
    widget_eye12:
      action: add

  set1_left_flashing_hit: widget_eye3
  set1_center_flashing_hit: widget_eye2
  set1_right_flashing_hit: widget_eye1
  set2_left_flashing_hit: widget_eye4
  set2_center_flashing_hit: widget_eye5
  set2_right_flashing_hit: widget_eye6
  set3_left_flashing_hit: widget_eye7
  set3_center_flashing_hit: widget_eye8
  set3_right_flashing_hit: widget_eye9
  set4_left_flashing_hit: widget_eye12
  set4_center_flashing_hit: widget_eye11
  set4_right_flashing_hit: widget_eye10
  enable_endportal: widget_portalopen
   
show_player:
  mode_stronghold_started:  #Setup GI Light Show
    show_strongholdgi:
      loops: -1
      speed: 4


event_player:
  slide_stronghold_slide_active:
    - show_player_score
    - show_ball_count
    - show_multiplier
    - update_eye_display

  mode_stronghold_started{current_player.stronghold_progress==0 or current_player.stronghold_progress==-1}:
    enable_eyeset1
  mode_stronghold_started{current_player.stronghold_progress==1}:
    eyeset1_complete
  mode_stronghold_started{current_player.stronghold_progress==2}:
    eyeset2_complete
  mode_stronghold_started{current_player.stronghold_progress==3}:
    eyeset3_complete
  mode_stronghold_started{current_player.stronghold_progress==4}:
    eyeset4_complete

  
  eyeset1_complete:
    - enable_eyeset2
    - update_eye_display
  eyeset2_complete:
    - enable_eyeset3
    - update_eye_display
  eyeset3_complete:
    - enable_eyeset4
    - update_eye_display

  eyeset4_complete{current_player.multiplier_mb==2}:
    - enable_eyespinner
    - update_eye_display
  eyeset4_complete{current_player.multiplier_mb==1}:
    - update_eye_display
    - disable_eyespinner
    - theend_ready
    - enable_endportal
  multiball_strongholdmb_ended{current_player.stronghold_progress==4}:
    - disable_eyespinner
    - theend_ready
    - enable_endportal
