#config_version=5
mode:
    start_events: strongholdmb_start
    stop_events: stronghold_completed
    restart_on_next_ball: true
    priority: 200


variable_player:
  shot_eye_flashing_hit:
    score: 10000 * current_player.multiplier_mb * current_player.sword 
  
  award_strongholdjackpot:
    score: current_player.stronghold_jackpot * current_player.sword

  eyespinner_hit:
    stronghold_jackpot: 
      int: 10000 * current_player.multiplier_mb
      action: add
      
  eyeset_complete:
    stronghold_progress:
      int: 1
      action: set

sound_player:
  mode_stronghold_started:
    stronghold_music:
      action: play
      loops: -1
      mode_end_action: stop
    stronghold_collect:
      action: play
      loops: 0
  eyeset_complete{current_player.multiplier_mb==2}: 
    stronghold_travel_multiball
  eyeset_complete{current_player.multiplier_mb==1}:
    stronghold_travel_single
  award_strongholdjackpot:
    stronghold_jackpot

  eyeset_flashing_hit: eyeplacesp
  eyespinner_hit: eyeplacesp
  enable_endportal: endportal

shot_profiles:
  sp_eyeshot:
    states:
      - name: flashing  # step 2
        show: show_altcolor
        show_tokens:
          color1: white
          color2: off
      - name: turnon  # step 3
        show: show_singlelight
        show_tokens:
          color: 417266
    loop: no
  sp_eyespinner:
    states:
      - name: flashing  # step 2
        show: show_spinnerenabled
        priority: 10
    loop: yes

shots:
  shot_eye1:
    switch: s_collectitem1
    profile: sp_eyeshot
    persist_enable: true
    show_tokens:
      leds: l_collectitem1
      light: l_collectitem1
  shot_eye2:
    switch: s_collectitem2
    profile: sp_eyeshot
    persist_enable: true
    show_tokens:
      leds: l_collectitem2
      light: l_collectitem2
  shot_eye3:
    switch: s_collectitem3
    profile: sp_eyeshot
    persist_enable: true
    show_tokens:
      leds: l_collectitem3
      light: l_collectitem3
  shot_eye4:
    switch: s_collectitem4
    profile: sp_eyeshot
    persist_enable: true
    show_tokens:
      leds: l_collectitem4
      light: l_collectitem4
  shot_eye5:
    switch: s_collectitem5
    profile: sp_eyeshot
    persist_enable: true
    show_tokens:
      leds: l_collectitem5
      light: l_collectitem5
  shot_eye6:
    switch: s_tooltarget1
    profile: sp_eyeshot
    persist_enable: true
    show_tokens:
      leds: l_toolcollect1
      light: l_toolcollect1
  shot_eye7:
    switch: s_tooltarget2
    profile: sp_eyeshot
    persist_enable: true
    show_tokens:
      leds: l_toolcollect2
      light: l_toolcollect2
  shot_eye8:
    switch: s_tooltarget3
    profile: sp_eyeshot
    persist_enable: true
    show_tokens:
      leds: l_toolcollect3
      light: l_toolcollect3
  shot_eye9:
    switch: s_whitedot1
    profile: sp_eyeshot
    persist_enable: true
    show_tokens:
      leds: l_craft1
      light: l_craft1
    hit_events: eye9_helper
  shot_eye10:
    switch: s_whitedot2
    profile: sp_eyeshot
    persist_enable: true
    show_tokens:
      leds: l_craft2
      light: l_craft2
    hit_events: eye10_helper
  shot_eye11:
    switch: s_whitedot3
    profile: sp_eyeshot
    persist_enable: true
    show_tokens:
      leds: l_craft3
      light: l_craft3
    hit_events: eye11_helper
  shot_eye12:
    switch: s_whitedot4
    profile: sp_eyeshot
    persist_enable: true
    show_tokens:
      leds: l_craft4
      light: l_craft4
    hit_events: eye12_helper

  eyespinner:
    switch: s_spinner  
    profile: sp_eyespinner
    disable_events: disable_eyespinner

shot_groups:
  eyeset:
    shots: shot_eye1, shot_eye2, shot_eye3, shot_eye4, shot_eye5, shot_eye6, shot_eye7, shot_eye8, shot_eye9, shot_eye10, shot_eye11, shot_eye12

widgets:
  widget_swordplayer:
    - type: image        #SCORE BACKGROUND
      image: Sword_FullScreen_Dark_1x
      anchor_x: right
      anchor_y: bottom
      y: bottom
      x: right
      z: 10
  widget_endportal:
    - type: image
      image: endportal_0
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 100
  widget_eye1:
    - type: image
      image: endportal_eye1
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye2:
    - type: image
      image: endportal_eye2
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye3:
    - type: image
      image: endportal_eye3
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye4:
    - type: image
      image: endportal_eye4
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye5:
    - type: image
      image: endportal_eye5
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye6:
    - type: image
      image: endportal_eye6
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye7:
    - type: image
      image: endportal_eye7
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye8:
    - type: image
      image: endportal_eye8
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye9:
    - type: image
      image: endportal_eye9
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye10:
    - type: image
      image: endportal_eye10
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye11:
    - type: image
      image: endportal_eye11
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_eye12:
    - type: image
      image: endportal_eye12
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 120
  widget_portalopen:
    - type: image
      image: endportal_active
      anchor_x: middle
      anchor_y: middle
      y: middle+100
      x: middle
      z: 150

  widget_strongholdjackpot:
    - type: image        #STRONGHOLD JACKPOT TEXT
      image: jackpot_stronghold
      anchor_x: center
      anchor_y: center
      y: bottom+100
      x: center+35
      z: 15    
    - type: text        #STRONGHOLD JACKPOT VALUE
      text: (player|stronghold_jackpot)
      number_grouping: true
      min_digits: 2
      font_name: ARLRDBD
      font_size: 24
      y: bottom+75
      x: center+35
      z: 100
      anchor_x: center
      anchor_y: center

slides:
  stronghold_slide:
    widgets:
      - type: image
        image: Pincraft_Logo_Icon

slide_player:
    mode_stronghold_started: stronghold_slide
  
light_player:
  mode_stronghold_started:
    lactionbar: off
  # set1_left_flashing_hit: 
  #   l_actionbar7: 417266
  #   l_actionbar8: 417266
  #   l_actionbar9: 417266
  # set1_center_flashing_hit: 
  #   l_actionbar4: 417266
  #   l_actionbar5: 417266
  #   l_actionbar6: 417266
  # set1_right_flashing_hit: 
  #   l_actionbar1: 417266
  #   l_actionbar2: 417266
  #   l_actionbar3: 417266
  # set2_left_flashing_hit: 
  #   l_actionbar10: 417266
  #   l_actionbar11: 417266
  #   l_actionbar12: 417266
  # set2_center_flashing_hit: 
  #   l_actionbar13: 417266
  #   l_actionbar14: 417266
  #   l_actionbar15: 417266
  # set2_right_flashing_hit: 
  #   l_actionbar16: 417266
  #   l_actionbar17: 417266
  #   l_actionbar18: 417266
  # set3_left_flashing_hit: 
  #   l_actionbar19: 417266
  #   l_actionbar20: 417266
  #   l_actionbar21: 417266
  # set3_center_flashing_hit: 
  #   l_actionbar22: 417266
  #   l_actionbar23: 417266
  #   l_actionbar24: 417266
  # set3_right_flashing_hit: 
  #   l_actionbar25: 417266
  #   l_actionbar26: 417266
  #   l_actionbar27: 417266
  # set4_left_flashing_hit:
  #   l_actionbar34: 417266
  #   l_actionbar35: 417266
  #   l_actionbar36: 417266
  #   l_actionbar37: 417266
  # set4_center_flashing_hit: 
  #   l_actionbar31: 417266
  #   l_actionbar32: 417266
  #   l_actionbar33: 417266
  # set4_right_flashing_hit: 
  #   l_actionbar28: 417266
  #   l_actionbar29: 417266
  #   l_actionbar30: 417266
  update_eye_display{current_player.stronghold_progress >=1}:
    # l_actionbar1: 417266
    # l_actionbar2: 417266
    # l_actionbar3: 417266
    # l_actionbar4: 417266
    # l_actionbar5: 417266
    # l_actionbar6: 417266
    # l_actionbar7: 417266
    # l_actionbar8: 417266
    # l_actionbar9: 417266
    l_collectitem1: 417266
    l_toolcollect1: 417266
    l_spinner1: 417266
  update_eye_display{current_player.stronghold_progress >=2}:
    # l_actionbar10: 417266
    # l_actionbar11: 417266
    # l_actionbar12: 417266
    # l_actionbar13: 417266
    # l_actionbar14: 417266
    # l_actionbar15: 417266
    # l_actionbar16: 417266
    # l_actionbar17: 417266
    # l_actionbar18: 417266
    l_collectitem2: 417266
    l_toolcollect2: 417266
    l_spinner2: 417266
  update_eye_display{current_player.stronghold_progress >=3}:
    # l_actionbar19: 417266
    # l_actionbar20: 417266
    # l_actionbar21: 417266
    # l_actionbar22: 417266
    # l_actionbar23: 417266
    # l_actionbar24: 417266
    # l_actionbar25: 417266
    # l_actionbar26: 417266
    # l_actionbar27: 417266
    l_collectitem4: 417266
    l_toolcollect3: 417266
    l_spinner3: 417266
  update_eye_display{current_player.stronghold_progress >=4}:
    lactionbar: 417266
    l_collectitem5: 417266
    l_craftlit: 417266
    l_spinner4: 417266

widget_player:
  slide_stronghold_slide_active:
    widget_endportal:
      action: add
      slide: stronghold_slide
    widget_screenbackground:
      action: add
      slide: stronghold_slide
      widget_settings:
        image: stronghold_background
    widget_strongholdjackpot:
      action: add
      slide: stronghold_slide

  update_eye_display{current_player.shot_shot_eye1==1}:
    widget_eye1
  update_eye_display{current_player.shot_shot_eye2==1}:
    widget_eye2
  update_eye_display{current_player.shot_shot_eye3==1}:
    widget_eye3
  update_eye_display{current_player.shot_shot_eye4==1}:
    widget_eye4
  update_eye_display{current_player.shot_shot_eye5==1}:
    widget_eye5
  update_eye_display{current_player.shot_shot_eye6==1}:
    widget_eye6
  update_eye_display{current_player.shot_shot_eye7==1}:
    widget_eye7
  update_eye_display{current_player.shot_shot_eye8==1}:
    widget_eye8
  update_eye_display{current_player.shot_shot_eye9==1}:
    widget_eye9
  update_eye_display{current_player.shot_shot_eye10==1}:
    widget_eye10
  update_eye_display{current_player.shot_shot_eye11==1}:
    widget_eye11
  update_eye_display{current_player.shot_shot_eye12==1}:
    widget_eye12

  enable_endportal: widget_portalopen
   
show_player:
  mode_stronghold_started:  #Setup GI Light Show
    show_strongholdgi:
      loops: -1
      speed: 6


event_player:
  slide_stronghold_slide_active:
    - show_player_score
    - show_ball_count
    - show_multiplier
    - update_eye_display

  mode_stronghold_started:
    update_eye_display

  eyeset_flashing_hit:
    update_eye_display

  eyeset_complete{current_player.multiplier_mb==2}:
    - enable_eyespinner
  eyeset_complete{current_player.multiplier_mb==1}:
    - disable_eyespinner
    - theend_ready
    - enable_endportal
  multiball_strongholdmb_ended{current_player.stronghold_progress==1}:
    - disable_eyespinner
    - theend_ready
    - enable_endportal

  #LIT A EYE LIGHT IF NOT ALL COLLECTED YET
  balldevice_bd_topkicker_ball_enter{current_player.shot_shot_eye9==0 }:
    eye9_helper
  balldevice_bd_topkicker_ball_enter{current_player.shot_shot_eye9==1 and current_player.shot_shot_eye10==0}:
    eye10_helper
  balldevice_bd_topkicker_ball_enter{current_player.shot_shot_eye9==1 and current_player.shot_shot_eye10==1 and current_player.shot_shot_eye11==0}:
    eye11_helper
  balldevice_bd_topkicker_ball_enter{current_player.shot_shot_eye9==1 and current_player.shot_shot_eye10==1 and current_player.shot_shot_eye11==1 and current_player.shot_shot_eye12==0}:
    eye12_helper