#config_version=5
mode:
    start_events: world3_started
    stop_events: world3_completed
    priority: 300

show_player:
  mode_world3_started:  #Setup GI Light Show
    show_world3gi:
      loops: -1
      speed: 1
  collectitem1_hit: 
    show_itemcollected_world3item1:
      loops: 0
  collectitem2_hit:
    show_itemcollected_world3item2:
      loops: 0
  collectitem3_hit:
    show_itemcollected_world3item3:
      loops: 0
  collectitem4_hit:
    show_itemcollected_world3item4:
      loops: 0

light_player:
  mode_world3_started:
    lbackbox: blue
    lundercab: blue

sound_player:
  mode_world3_started:
    world3mode_music:
      action: play
      loops: -1
      mode_end_action: stop
  worldmultiball_ended:
    world3mode_music:
      action: play
      loops: -1
      mode_end_action: stop

variable_player:
  #setup environment variables
  mode_world3_started{current_player.world3_setup==0}:  
    #World Settings
    world_id:
      int: 3
      action: set
    world_name: 
      string: "World 3"
      action: set
    world_color: 
      string: "BLUE"
      action: set

    #Item 1 Settings
    world_item1_name:
      string: "Snow"
      action: set 
    world_item1_color:
      string: "BLUE"
      action: set 
    world_item1_remaining:
      int: 9
      action: set

    #Item 2 Settings
    world_item2_name:
      string: "Cobblestone"
      action: set 
    world_item2_color:
      string: "BROWN"
      action: set 
    world_item2_remaining:
      int: 9
      action: set

    #Item 3 Settings
    world_item3_name:
      string: "Packed Ice"
      action: set 
    world_item3_color:
      string: "LIGHTBLUE"
      action: set 
    world_item3_remaining:
      int: 9
      action: set

    #Item 4 Settings
    world_item4_name:
      string: "Spruce Log"
      action: set 
    world_item4_color:
      string: "BROWN"
      action: set 
    world_item4_remaining:
      int: 9
      action: set

    #Mark World as Setup
    world3_setup: 1

widgets:
  widget_world3videobackground:
    - type: video
      video: video_world3_overview
      auto_play: true
      end_behavior: loop
      z: 6

widget_player:
  mode_world3_started:
    widget_world3videobackground:
      action: add
      slide: world_slide
    widget_item1icon:
      action: update
      slide: world_slide
      widget_settings:
        image: Snow_Small
    widget_item2icon:
      action: update
      slide: world_slide
      widget_settings:
        image: Cobblestone_Small
    widget_item3icon:
      action: update
      slide: world_slide
      widget_settings:
        image: Ice_Small
    widget_item4icon:
      action: update
      slide: world_slide
      widget_settings:
        image: WoodSpruce_Small

event_player:
  world_collected:
    world3_collected
  mode_villagercontroller_stopped:
    worldmultiball_ended
  mode_nightcontroller_stopped:
    worldmultiball_ended
  mode_nightvillagercontroller_stopped:
    worldmultiball_ended