#config_version=5
mode:
    start_events: world3_started
    stop_events: world3_completed
    priority: 500

show_player:
  mode_world3_started:  #Setup GI Light Show
    show_world3gi:
      loops: -1
      speed: 1

sound_player:
  mode_world3_started:
    world3mode_music:
      action: play
      loops: -1
      mode_end_action: stop
  mode_villagermb_stopped:
    world3mode_music:
      action: play
      loops: -1
      mode_end_action: stop

variable_player:
  #setup environment variables
  mode_world3_started:  
    #World Settings
    world_id:
      int: 3
      action: set
    world_name: 
      string: "World 3"
      action: set
    world_color: 
      string: "BLUE"
      action: set

    #Item 1 Settings
    world_item1_name:
      string: "Ice"
      action: set 
    world_item1_color:
      string: "BLUE"
      action: set 
    world_item1_needed:
      int: 3
      action: set

    #Item 2 Settings
    world_item2_name:
      string: "Stone"
      action: set 
    world_item2_color:
      string: "GRAY"
      action: set 
    world_item2_needed:
      int: 3
      action: set

    #Item 3 Settings
    world_item3_name:
      string: "Ore"
      action: set 
    world_item3_color:
      string: "BROWN"
      action: set 
    world_item3_needed:
      int: 3
      action: set

    #Item 4 Settings
    world_item4_name:
      string: "Wood"
      action: set 
    world_item4_color:
      string: "SLATEGRAY"
      action: set 
    world_item4_needed:
      int: 3
      action: set

  logicblock_wc3_item1_counter_updated:
    world_item1_remaining:
      int: value
      action: set
  logicblock_wc3_item2_counter_updated:
    world_item2_remaining:
      int: value
      action: set
  logicblock_wc3_item3_counter_updated:
    world_item3_remaining:
      int: value
      action: set
  logicblock_wc3_item4_counter_updated:
    world_item4_remaining:
      int: value
      action: set

counters:
  wc3_item1_counter:
    count_events: collectitem1_hit
    reset_on_complete: False
    starting_count: 3
    count_complete_value: 0
    direction: down
    persist_state: true
    events_when_complete: w3_itemcheckcomplete
    multiple_hit_window: 500ms
    enable_events: mode_world3_started
  wc3_item2_counter:
    count_events: collectitem2_hit
    reset_on_complete: False
    starting_count: 3
    count_complete_value: 0
    direction: down
    persist_state: true
    events_when_complete: w3_itemcheckcomplete
    multiple_hit_window: 500ms
    enable_events: mode_world3_started
  wc3_item3_counter:
    count_events: collectitem3_hit
    reset_on_complete: False
    starting_count: 3
    count_complete_value: 0
    direction: down
    persist_state: true
    events_when_complete: w3_itemcheckcomplete
    multiple_hit_window: 500ms
    enable_events: mode_world3_started
  wc3_item4_counter:
    count_events: collectitem4_hit
    reset_on_complete: False
    starting_count: 3
    count_complete_value: 0
    direction: down
    persist_state: true
    events_when_complete: w3_itemcheckcomplete
    multiple_hit_window: 500ms
    enable_events: mode_world3_started

event_player:
  mode_world3_started:
    world3_started
    w3_itemcheckcomplete

  w3_itemcheckcomplete{current_player.world_item1_remaining == 0 and current_player.world_item2_remaining == 0 and current_player.world_item3_remaining == 0 and current_player.world_item4_remaining == 0}:
    world3_collected

  w3_itemcheckcomplete{current_player.world_item1_remaining > 0}:
    collectitem1_enabled
  w3_itemcheckcomplete{current_player.world_item1_remaining == 0}:
    collectitem1_disabled
  
  w3_itemcheckcomplete{current_player.world_item2_remaining > 0}:
    collectitem2_enabled
  w3_itemcheckcomplete{current_player.world_item2_remaining == 0}:
    collectitem2_disabled

  w3_itemcheckcomplete{current_player.world_item3_remaining > 0}:
    collectitem3_enabled
  w3_itemcheckcomplete{current_player.world_item3_remaining == 0}:
    collectitem3_disabled

  w3_itemcheckcomplete{current_player.world_item4_remaining > 0}:
    collectitem4_enabled
  w3_itemcheckcomplete{current_player.world_item4_remaining == 0}:
    collectitem4_disabled