#config_version=5
mode:
    start_events: world3_started
    stop_events: world3_completed
    priority: 500

show_player:
  mode_world3_started:  #Setup GI Light Show
    show_world3gi:
      loops: -1
      speed: 1

light_player:
  mode_world3_started:
    lbackbox: blue
    lundercab: blue

sound_player:
  mode_world3_started:
    world3mode_music:
      action: play
      loops: -1
      mode_end_action: stop
  mode_villagermb_stopped:
    world3mode_music:
      action: play
      loops: -1
      mode_end_action: stop
  world3_collected: travel_ready

variable_player:
  #setup environment variables
  mode_world3_started{current_player.world3_setup==0}:  
    #World Settings
    world_id:
      int: 3
      action: set
    world_name: 
      string: "World 3"
      action: set
    world_color: 
      string: "BLUE"
      action: set

    #Item 1 Settings
    world_item1_name:
      string: "Ice"
      action: set 
    world_item1_color:
      string: "BLUE"
      action: set 
    world_item1_remaining:
      int: 9
      action: set

    #Item 2 Settings
    world_item2_name:
      string: "Stone"
      action: set 
    world_item2_color:
      string: "GRAY"
      action: set 
    world_item2_remaining:
      int: 9
      action: set

    #Item 3 Settings
    world_item3_name:
      string: "Ore"
      action: set 
    world_item3_color:
      string: "BROWN"
      action: set 
    world_item3_remaining:
      int: 9
      action: set

    #Item 4 Settings
    world_item4_name:
      string: "Wood"
      action: set 
    world_item4_color:
      string: "SLATEGRAY"
      action: set 
    world_item4_remaining:
      int: 9
      action: set

    #Mark World as Setup
    world3_setup: 1

widget_player:
  mode_world3_started:
    widget_screenbackground:
      action: update
      widget_settings:
        image: world3_background

event_player:
   world_collected:
    world3_collected