#config_version=5
mode:
    start_events: award_world3
    stop_events: world3_completed
    priority: 500

show_player:
  mode_world3_started:  #Setup GI Light Show
    show_world3gi:
      loops: -1
      speed: 1

sound_player:
  world_started:
    world3mode_music:
      action: play
      loops: -1
      mode_end_action: stop
  multiball_villagermb_ended:
    world3mode_music:
      action: play
      loops: -1
      mode_end_action: stop

variable_player:
  #setup environment variables
  mode_world3_started:  
    #World Settings
    world_id:
      int: 3
      action: set
    world_name: 
      string: "World 3"
      action: set
    world_color: 
      string: "BLUE"
      action: set

    #Item 1 Settings
    world_item1_name:
      string: "Ice"
      action: set 
    world_item1_color:
      string: "BLUE"
      action: set 
    world_item1_needed:
      int: 3
      action: set

    #Item 2 Settings
    world_item2_name:
      string: "Stone"
      action: set 
    world_item2_color:
      string: "GRAY"
      action: set 
    world_item2_needed:
      int: 3
      action: set

    #Item 3 Settings
    world_item3_name:
      string: "Ore"
      action: set 
    world_item3_color:
      string: "BROWN"
      action: set 
    world_item3_needed:
      int: 3
      action: set

    #Item 4 Settings
    world_item4_name:
      string: "Wood"
      action: set 
    world_item4_color:
      string: "SLATEGRAY"
      action: set 
    world_item4_needed:
      int: 3
      action: set
  

event_player:
  mode_world3_started:
    world_started