#config_version=5
mode:
    start_events: mode_nightcontroller_started, mode_nightvillagercontroller_started
    stop_events: mode_nightcontroller_stopped, mode_nightvillagercontroller_stopped
    priority: 500




event_player:
  mode_night_started:
    show_multiplier

  