#config_version=5
mode:
    start_events: mode_nightcontroller_started, mode_nightvillagercontroller_started
    stop_events: mode_nightcontroller_stopped, mode_nightvillagercontroller_stopped
    priority: 500


sound_player:
  night_drop1_hit: creeper_death
  night_drop6_hit: creeper_death

variable_player:
  mode_night_started:
    night_jackpot: 
      int: 1000000
      action: set

  night_drop1_hit:
    score: 10000 * current_player.multiplier_mb * current_player.sword
    night_jackpot: 100000 * current_player.sword
  night_drop6_hit:
    score: 10000 * current_player.multiplier_mb * current_player.sword
    night_jackpot: 100000 * current_player.sword

  night_jackpot_collected:
    score: current_player.night_jackpot * current_player.multiplier_mb
    night_jackpot:
      int: 1000000
      action: set

show_player:
  mode_night_started:
    show_creepersetup:
      loops: 0
      speed: 1

  mbcreepers_complete:
    show_creepersetup:
      loops: 0
      speed: 1

  creepersetup_retry:
    show_creepersetup:
      loops: 0
      speed: 1

  night_jackpot_hit:
    show_nightjackpot:
      loops: 0
      speed: 1

shots:
  night_drop1:
    switch: s_drop1
    profile: mbtarget
    show_tokens:
      light: l_drop1
    reset_events: creepersetup_complete
    enable_events: creepersetup_complete
    disable_events: mode_night_started
  night_drop6:
    switch: s_drop6
    profile: mbtarget
    show_tokens:
      light: l_drop6
    reset_events: creepersetup_complete
    enable_events: creepersetup_complete
    disable_events: mode_night_started
  night_jackpot:
    switch: s_captiveball
    profile: mbtarget
    show_tokens:
      light: l_captivejackpot
    disable_events: night_jackpot_hit
    enable_events: mode_night_started, night_jackpot_collected

shot_groups:
  mbcreepers:
    shots: night_drop1, night_drop6
    disable_events: mode_night_started
    reset_events: creepersetup_complete
    enable_events: creepersetup_complete

widget_player:
  mode_night_started:
    widget_nightjackpot:
      action: add
  creepersetup_complete:
    widget_leftcreeper:
      action: add
    widget_rightcreeper:
      action: add

#Remove Mobs When Hit
  night_drop1_hit:
    widget_leftcreeper:
      action: remove
  night_drop6_hit:
    widget_rightcreeper:
      action: remove

widgets:
  widget_leftcreeper:
    - type: image        
      image: CreeperLeft
      anchor_x: middle
      anchor_y: top
      y: top-50
      x: middle-500
      z: 10

  widget_rightcreeper:
    - type: image        
      image: CreeperRight
      anchor_x: middle
      anchor_y: top
      y: top-50
      x: middle+350
      z: 10

  widget_nightjackpot:
    - type: image        #ITEM BACKGROUND
      image: jackpot_night
      anchor_x: center
      anchor_y: center
      y: bottom+200
      x: center+35
      z: 15    
    - type: text        #PLAYER 1 SCORE
      text: (player|night_jackpot)
      number_grouping: true
      min_digits: 2
      font_name: ARLRDBD
      font_size: 24
      y: bottom+175
      x: center+35
      z: 100
      anchor_x: center
      anchor_y: center

  widget_nightjackpot_collected:  #WORLD JACKPOT
    - type: text       
      text: NIGHT JACKPOT COLLECTED
      font_name: ARLRDBD
      font_size: 36
      color: white
      y: center + 75
      x: center + 75
      z: 205
      anchor_x: center
      anchor_y: center   
    - type: text       
      text: (player|night_jackpot) x (player|multiplier_mb) 
      number_grouping: true
      font_name: ARLRDBD
      font_size: 52
      color: white
      y: center + 25
      x: center + 50
      z: 205
      anchor_x: center
      anchor_y: center     
    - type: image       
      image: popup_background
      anchor_x: center
      anchor_y: center
      y: center + 50
      x: center
      z: 200
    - type: image       
      image: CreeperFace
      anchor_x: center
      anchor_y: center
      y: center + 50
      x: center - 300
      z: 205


event_player:
  mode_night_started:
    show_multiplier

  creepersetup_attempted{device.switches.s_drop1.state==0 and device.switches.s_drop6.state==0}:
    creepersetup_complete
  creepersetup_attempted{device.switches.s_drop1.state==1 or device.switches.s_drop6.state==1}:
    creepersetup_retry

  